# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-02 06:54
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jvtype', '0002_auto_20170202_1454'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branch', '0002_auto_20170202_1454'),
        ('department', '0002_auto_20170202_1454'),
        ('currency', '0002_auto_20170202_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jvmain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jvnum', models.CharField(max_length=10, unique=True)),
                ('jvprefix', models.CharField(default=b'JV', max_length=5)),
                ('jvdate', models.DateTimeField()),
                ('refnum', models.CharField(blank=True, max_length=150, null=True)),
                ('particular', models.TextField()),
                ('status', models.CharField(choices=[(b'A', b'Active'), (b'I', b'Inactive'), (b'C', b'Cancelled'), (b'O', b'Posted'), (b'P', b'Printed')], default=b'A', max_length=1)),
                ('enterdate', models.DateTimeField(auto_now_add=True)),
                ('modifydate', models.DateTimeField(default=datetime.datetime(2017, 2, 2, 14, 54, 8, 771106))),
                ('postdate', models.DateTimeField(default=datetime.datetime(2017, 2, 2, 14, 54, 8, 771198))),
                ('isdeleted', models.IntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_jvmain_id', to='branch.Branch')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_jvmain_id', to='currency.Currency')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_jvmain_id', to='department.Department')),
                ('enterby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jvmain_enter', to=settings.AUTH_USER_MODEL)),
                ('jvtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jvtype_jvmain_id', to='jvtype.Jvtype')),
                ('modifyby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jvmain_modify', to=settings.AUTH_USER_MODEL)),
                ('postby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jvmain_post', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'jvmain',
                'permissions': (('view_jvmain', 'Can view jvmain'),),
            },
        ),
    ]
