# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-27 17:12
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wtax', '0002_auto_20170227_1712'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bankaccount', '0002_auto_20170227_1712'),
        ('product', '0002_auto_20170227_1712'),
        ('employee', '0002_auto_20170227_1712'),
        ('outputvat', '0002_auto_20170227_1712'),
        ('chartofaccount', '0005_auto_20170227_1712'),
        ('ataxcode', '0002_auto_20170227_1712'),
        ('vat', '0002_auto_20170227_1712'),
        ('department', '0005_auto_20170227_1712'),
        ('customer', '0002_auto_20170227_1712'),
        ('inputvat', '0002_auto_20170227_1712'),
        ('unit', '0004_auto_20170227_1712'),
        ('branch', '0003_auto_20170227_1712'),
        ('supplier', '0002_auto_20170227_1712'),
        ('journalvoucher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jvdetail',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('item_counter', models.IntegerField()),
                ('jv_num', models.CharField(max_length=10)),
                ('jv_date', models.DateTimeField()),
                ('debitamount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('creditamount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('balancecode', models.CharField(blank=True, max_length=1, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('status', models.CharField(choices=[(b'A', b'Active'), (b'I', b'Inactive'), (b'C', b'Cancelled'), (b'O', b'Posted'), (b'P', b'Printed')], default=b'A', max_length=1)),
                ('enterdate', models.DateTimeField(auto_now_add=True)),
                ('modifydate', models.DateTimeField(default=datetime.datetime(2017, 2, 27, 17, 12, 53, 878607))),
                ('postdate', models.DateTimeField(default=datetime.datetime(2017, 2, 27, 17, 12, 53, 878713))),
                ('isdeleted', models.IntegerField(default=0)),
                ('ataxcode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ataxcode_jvdetail_id', to='ataxcode.Ataxcode')),
                ('bankaccount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bankaccount_jvdetail_id', to='bankaccount.Bankaccount')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_jvdetail_id', to='branch.Branch')),
                ('chartofaccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chartofaccount_jvdetail_id', to='chartofaccount.Chartofaccount')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_jvdetail_id', to='customer.Customer')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_jvdetail_id', to='department.Department')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_jvdetail_id', to='employee.Employee')),
                ('enterby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jvdetail_enter', to=settings.AUTH_USER_MODEL)),
                ('inputvat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inputvat_jvdetail_id', to='inputvat.Inputvat')),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'jv',
            },
        ),
        migrations.AlterField(
            model_name='jvmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 27, 17, 12, 53, 874024)),
        ),
        migrations.AlterField(
            model_name='jvmain',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 27, 17, 12, 53, 874268)),
        ),
        migrations.AddField(
            model_name='jvdetail',
            name='jvmain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jvmain_jvdetail_id', to='journalvoucher.Jvmain'),
        ),
        migrations.AddField(
            model_name='jvdetail',
            name='modifyby',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jvdetail_modify', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jvdetail',
            name='outputvat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outputvat_jvdetail_id', to='outputvat.Outputvat'),
        ),
        migrations.AddField(
            model_name='jvdetail',
            name='postby',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jvdetail_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jvdetail',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_jvdetail_id', to='product.Product'),
        ),
        migrations.AddField(
            model_name='jvdetail',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_jvdetail_id', to='supplier.Supplier'),
        ),
        migrations.AddField(
            model_name='jvdetail',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_jvdetail_id', to='unit.Unit'),
        ),
        migrations.AddField(
            model_name='jvdetail',
            name='vat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vat_jvdetail_id', to='vat.Vat'),
        ),
        migrations.AddField(
            model_name='jvdetail',
            name='wtax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wtax_jvdetail_id', to='wtax.Wtax'),
        ),
    ]
