# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-27 17:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalvoucher', '0002_auto_20170227_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jvdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 27, 17, 14, 1, 986063)),
        ),
        migrations.AlterField(
            model_name='jvdetail',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 27, 17, 14, 1, 986178)),
        ),
        migrations.AlterField(
            model_name='jvmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 27, 17, 14, 1, 982067)),
        ),
        migrations.AlterField(
            model_name='jvmain',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 27, 17, 14, 1, 982189)),
        ),
        migrations.AlterModelTable(
            name='jvdetail',
            table='jvdetail',
        ),
    ]
