# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-28 11:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalvoucher', '0003_auto_20170227_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jvdetail',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='jvdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 28, 11, 45, 2, 468295)),
        ),
        migrations.AlterField(
            model_name='jvdetail',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 28, 11, 45, 2, 468399)),
        ),
        migrations.AlterField(
            model_name='jvmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 28, 11, 45, 2, 463934)),
        ),
        migrations.AlterField(
            model_name='jvmain',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 28, 11, 45, 2, 464082)),
        ),
    ]
