# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-28 16:44
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journalvoucher', '0004_auto_20170228_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jvdetailtemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_counter', models.IntegerField()),
                ('jvmain', models.DateTimeField()),
                ('jv_num', models.CharField(max_length=10)),
                ('jv_date', models.DateTimeField()),
                ('chartofaccount', models.IntegerField()),
                ('bankaccount', models.IntegerField()),
                ('department', models.IntegerField()),
                ('employee', models.IntegerField()),
                ('supplier', models.IntegerField()),
                ('customer', models.IntegerField()),
                ('unit', models.IntegerField()),
                ('branch', models.IntegerField()),
                ('product', models.IntegerField()),
                ('inputvat', models.IntegerField()),
                ('outputvat', models.IntegerField()),
                ('vat', models.IntegerField()),
                ('wtax', models.IntegerField()),
                ('ataxcode', models.IntegerField()),
                ('debitamount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('creditamount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('balancecode', models.CharField(blank=True, max_length=1, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('status', models.CharField(choices=[(b'A', b'Active'), (b'I', b'Inactive'), (b'C', b'Cancelled'), (b'O', b'Posted'), (b'P', b'Printed')], default=b'A', max_length=1)),
                ('enterdate', models.DateTimeField(auto_now_add=True)),
                ('modifydate', models.DateTimeField(default=datetime.datetime(2017, 2, 28, 16, 44, 24, 275225))),
                ('postdate', models.DateTimeField(default=datetime.datetime(2017, 2, 28, 16, 44, 24, 275332))),
                ('isdeleted', models.IntegerField(default=0)),
                ('enterby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jvdetailtemp_enter', to=settings.AUTH_USER_MODEL)),
                ('modifyby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jvdetailtemp_modify', to=settings.AUTH_USER_MODEL)),
                ('postby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jvdetailtemp_post', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'jvdetailtemp',
            },
        ),
        migrations.AlterField(
            model_name='jvdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 28, 16, 44, 24, 271442)),
        ),
        migrations.AlterField(
            model_name='jvdetail',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 28, 16, 44, 24, 271564)),
        ),
        migrations.AlterField(
            model_name='jvmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 28, 16, 44, 24, 267463)),
        ),
        migrations.AlterField(
            model_name='jvmain',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 28, 16, 44, 24, 267549)),
        ),
    ]
