# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-28 16:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalvoucher', '0006_auto_20170228_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jvdetail',
            old_name='secretkey',
            new_name='skey',
        ),
        migrations.AlterField(
            model_name='jvdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 28, 16, 48, 53, 658997)),
        ),
        migrations.AlterField(
            model_name='jvdetail',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 28, 16, 48, 53, 659082)),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 28, 16, 48, 53, 662006)),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 28, 16, 48, 53, 662096)),
        ),
        migrations.AlterField(
            model_name='jvmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 28, 16, 48, 53, 656036)),
        ),
        migrations.AlterField(
            model_name='jvmain',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 28, 16, 48, 53, 656125)),
        ),
    ]
