# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-28 16:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalvoucher', '0007_auto_20170228_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jvdetail',
            name='skey',
        ),
        migrations.AddField(
            model_name='jvdetailtemp',
            name='secretkey',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jvdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 28, 16, 49, 59, 483864)),
        ),
        migrations.AlterField(
            model_name='jvdetail',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 28, 16, 49, 59, 483954)),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 28, 16, 49, 59, 486915)),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 28, 16, 49, 59, 486999)),
        ),
        migrations.AlterField(
            model_name='jvmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 28, 16, 49, 59, 480962)),
        ),
        migrations.AlterField(
            model_name='jvmain',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 28, 16, 49, 59, 481046)),
        ),
    ]
