# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-24 16:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journalvoucher', '0012_auto_20170324_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jvdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 24, 16, 12, 35, 358349)),
        ),
        migrations.AlterField(
            model_name='jvdetail',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 24, 16, 12, 35, 358459)),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='ataxcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ataxcode_jvdetailtemp_id', to='ataxcode.Ataxcode'),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_jvdetailtemp_id', to='branch.Branch'),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='chartofaccount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chartofaccount_jvdetailtemp_id', to='chartofaccount.Chartofaccount'),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_jvdetailtemp_id', to='customer.Customer'),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_jvdetailtemp_id', to='employee.Employee'),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='inputvat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inputvat_jvdetailtemp_id', to='inputvat.Inputvat'),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 24, 16, 12, 35, 362528)),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='outputvat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outputvat_jvdetailtemp_id', to='outputvat.Outputvat'),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 24, 16, 12, 35, 362653)),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_jvdetailtemp_id', to='product.Product'),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_jvdetailtemp_id', to='supplier.Supplier'),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_jvdetailtemp_id', to='unit.Unit'),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='vat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vat_jvdetailtemp_id', to='vat.Vat'),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='wtax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wtax_jvdetailtemp_id', to='wtax.Wtax'),
        ),
        migrations.AlterField(
            model_name='jvmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 24, 16, 12, 35, 354724)),
        ),
        migrations.AlterField(
            model_name='jvmain',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 24, 16, 12, 35, 354836)),
        ),
    ]
