# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-24 16:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalvoucher', '0020_auto_20170324_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jvdetailtemp',
            name='department',
        ),
        migrations.AddField(
            model_name='jvdetailtemp',
            name='departmentxxxx',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 24, 16, 24, 15, 606815)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jvdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 24, 16, 23, 57, 456349)),
        ),
        migrations.AlterField(
            model_name='jvdetail',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 24, 16, 23, 57, 456459)),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 24, 16, 23, 57, 460472)),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 24, 16, 23, 57, 460567)),
        ),
        migrations.AlterField(
            model_name='jvmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 24, 16, 23, 57, 452721)),
        ),
        migrations.AlterField(
            model_name='jvmain',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 24, 16, 23, 57, 452833)),
        ),
    ]
