# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-24 17:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journalvoucher', '0028_auto_20170324_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jvdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 24, 17, 17, 58, 649970)),
        ),
        migrations.AlterField(
            model_name='jvdetail',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 24, 17, 17, 58, 650074)),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='bankaccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bankaccount_jvdetailtemp_id', to='bankaccount.Bankaccount'),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='chartofaccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chartofaccount_jvdetailtemp_id', to='chartofaccount.Chartofaccount'),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 24, 17, 17, 58, 653442)),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 24, 17, 17, 58, 653539)),
        ),
        migrations.AlterField(
            model_name='jvmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 24, 17, 17, 58, 646347)),
        ),
        migrations.AlterField(
            model_name='jvmain',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 24, 17, 17, 58, 646459)),
        ),
    ]
