# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-24 17:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalvoucher', '0030_auto_20170324_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jvdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 24, 17, 39, 14, 159348)),
        ),
        migrations.AlterField(
            model_name='jvdetail',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 24, 17, 39, 14, 159459)),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='ataxcode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='bankaccount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='branch',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='chartofaccount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='customer',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='department',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='employee',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='inputvat',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 24, 17, 39, 14, 163239)),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='outputvat',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 24, 17, 39, 14, 163354)),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='product',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='supplier',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='unit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='vat',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='wtax',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='jvmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 24, 17, 39, 14, 154425)),
        ),
        migrations.AlterField(
            model_name='jvmain',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 24, 17, 39, 14, 154535)),
        ),
    ]
