# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-24 17:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalvoucher', '0031_auto_20170324_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jvdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 24, 17, 43, 56, 710290)),
        ),
        migrations.AlterField(
            model_name='jvdetail',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 24, 17, 43, 56, 710401)),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='ataxcode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='bankaccount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='branch',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='chartofaccount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='customer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='department',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='employee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='inputvat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='jv_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 24, 17, 43, 56, 713796)),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='outputvat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 24, 17, 43, 56, 713893)),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='product',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='supplier',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='unit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='vat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='wtax',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jvmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 24, 17, 43, 56, 706698)),
        ),
        migrations.AlterField(
            model_name='jvmain',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 24, 17, 43, 56, 706809)),
        ),
    ]
