# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-06 11:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalvoucher', '0035_auto_20170331_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='jvdetailtemp',
            name='customerbreakstatus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jvdetailtemp',
            name='employeebreakstatus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jvdetailtemp',
            name='supplierbreakstatus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jvdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 6, 11, 15, 14, 495527)),
        ),
        migrations.AlterField(
            model_name='jvdetail',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 6, 11, 15, 14, 495648)),
        ),
        migrations.AlterField(
            model_name='jvdetailbreakdowntemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 6, 11, 15, 14, 504514)),
        ),
        migrations.AlterField(
            model_name='jvdetailbreakdowntemp',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 6, 11, 15, 14, 504616)),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 6, 11, 15, 14, 499933)),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 6, 11, 15, 14, 500041)),
        ),
        migrations.AlterField(
            model_name='jvmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 6, 11, 15, 14, 491233)),
        ),
        migrations.AlterField(
            model_name='jvmain',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 6, 11, 15, 14, 491355)),
        ),
    ]
