# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-20 11:04
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journalvoucher', '0038_auto_20170407_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jvdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 20, 11, 3, 58, 880632)),
        ),
        migrations.AlterField(
            model_name='jvdetail',
            name='postby',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jvdetail_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jvdetail',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 20, 11, 3, 58, 880729)),
        ),
        migrations.AlterField(
            model_name='jvdetailbreakdown',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 20, 11, 3, 58, 885122)),
        ),
        migrations.AlterField(
            model_name='jvdetailbreakdown',
            name='postby',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jvdetailbreakdown_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jvdetailbreakdown',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 20, 11, 3, 58, 885227)),
        ),
        migrations.AlterField(
            model_name='jvdetailbreakdowntemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 20, 11, 3, 58, 894473)),
        ),
        migrations.AlterField(
            model_name='jvdetailbreakdowntemp',
            name='postby',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jvdetailbreakdowntemp_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jvdetailbreakdowntemp',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 20, 11, 3, 58, 894583)),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 20, 11, 3, 58, 890858)),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='postby',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jvdetailtemp_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 20, 11, 3, 58, 890970)),
        ),
        migrations.AlterField(
            model_name='jvmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 20, 11, 3, 58, 877346)),
        ),
        migrations.AlterField(
            model_name='jvmain',
            name='postby',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jvmain_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jvmain',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 20, 11, 3, 58, 877445)),
        ),
    ]
