# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-10-02 06:31
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journalvoucher', '0045_auto_20170421_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='jvmain',
            name='actualapprover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jvmain_actual_approver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jvmain',
            name='approverremarks',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='jvmain',
            name='approverresponse',
            field=models.CharField(blank=True, choices=[('A', 'Approved'), ('D', 'Disapproved')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jvmain',
            name='designatedapprover',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='jvmain_designated_approver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jvmain',
            name='jvstatus',
            field=models.CharField(choices=[('F', 'For Approval'), ('A', 'Approved'), ('D', 'Disapproved'), ('I', 'In Process'), ('R', 'Released')], default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='jvmain',
            name='print_ctr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jvmain',
            name='releaseby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jvmain_release', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jvmain',
            name='releasedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jvmain',
            name='remarks',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='jvmain',
            name='responsedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jvdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 2, 14, 31, 10, 570000)),
        ),
        migrations.AlterField(
            model_name='jvdetail',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 2, 14, 31, 10, 570000)),
        ),
        migrations.AlterField(
            model_name='jvdetailbreakdown',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 2, 14, 31, 10, 574000)),
        ),
        migrations.AlterField(
            model_name='jvdetailbreakdown',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 2, 14, 31, 10, 574000)),
        ),
        migrations.AlterField(
            model_name='jvdetailbreakdowntemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 2, 14, 31, 10, 580000)),
        ),
        migrations.AlterField(
            model_name='jvdetailbreakdowntemp',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 2, 14, 31, 10, 580000)),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 2, 14, 31, 10, 577000)),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 2, 14, 31, 10, 578000)),
        ),
        migrations.AlterField(
            model_name='jvmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 2, 14, 31, 10, 567000)),
        ),
        migrations.AlterField(
            model_name='jvmain',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 2, 14, 31, 10, 567000)),
        ),
    ]
