# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-10-02 07:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jvsubtype', '0002_auto_20171002_1538'),
        ('journalvoucher', '0046_auto_20171002_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='jvmain',
            name='jvsubtype',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='jvsubtype_jvmain_id', to='jvsubtype.Jvsubtype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jvdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 2, 15, 38, 18, 996000)),
        ),
        migrations.AlterField(
            model_name='jvdetail',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 2, 15, 38, 18, 996000)),
        ),
        migrations.AlterField(
            model_name='jvdetailbreakdown',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 2, 15, 38, 19)),
        ),
        migrations.AlterField(
            model_name='jvdetailbreakdown',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 2, 15, 38, 19)),
        ),
        migrations.AlterField(
            model_name='jvdetailbreakdowntemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 2, 15, 38, 19, 6000)),
        ),
        migrations.AlterField(
            model_name='jvdetailbreakdowntemp',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 2, 15, 38, 19, 6000)),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 2, 15, 38, 19, 3000)),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 2, 15, 38, 19, 3000)),
        ),
        migrations.AlterField(
            model_name='jvmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 2, 15, 38, 18, 992000)),
        ),
        migrations.AlterField(
            model_name='jvmain',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 2, 15, 38, 18, 992000)),
        ),
    ]
