# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-03-21 08:27
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journalvoucher', '0053_auto_20180124_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='jvdetail',
            name='closeby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jvdetail_close', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jvdetail',
            name='closedate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 16, 27, 40, 850000)),
        ),
        migrations.AddField(
            model_name='jvdetailbreakdown',
            name='closeby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jvdetailbreakdown_close', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jvdetailbreakdown',
            name='closedate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 16, 27, 40, 852000)),
        ),
        migrations.AddField(
            model_name='jvdetailbreakdowntemp',
            name='closeby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jvdetailbreakdowntemp_close', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jvdetailbreakdowntemp',
            name='closedate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 16, 27, 40, 856000)),
        ),
        migrations.AddField(
            model_name='jvdetailtemp',
            name='closeby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jvdetailtemp_close', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jvdetailtemp',
            name='closedate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 16, 27, 40, 855000)),
        ),
        migrations.AddField(
            model_name='jvmain',
            name='closeby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jvmain_close', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jvmain',
            name='closedate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 16, 27, 40, 847000)),
        ),
        migrations.AlterField(
            model_name='jvdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 16, 27, 40, 849000)),
        ),
        migrations.AlterField(
            model_name='jvdetail',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 16, 27, 40, 849000)),
        ),
        migrations.AlterField(
            model_name='jvdetailbreakdown',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 16, 27, 40, 852000)),
        ),
        migrations.AlterField(
            model_name='jvdetailbreakdown',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 16, 27, 40, 852000)),
        ),
        migrations.AlterField(
            model_name='jvdetailbreakdowntemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 16, 27, 40, 856000)),
        ),
        migrations.AlterField(
            model_name='jvdetailbreakdowntemp',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 16, 27, 40, 856000)),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 16, 27, 40, 854000)),
        ),
        migrations.AlterField(
            model_name='jvdetailtemp',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 16, 27, 40, 854000)),
        ),
        migrations.AlterField(
            model_name='jvmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 16, 27, 40, 847000)),
        ),
        migrations.AlterField(
            model_name='jvmain',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 16, 27, 40, 847000)),
        ),
    ]
