# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-04-23 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalvoucher', '0055_auto_20180322_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jvmain',
            name='jvdate',
            field=models.DateField(),
        ),
    ]
