# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-20 11:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvasssheet', '0007_auto_20170420_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csdetailtemp',
            name='csdetail',
        ),
        migrations.RemoveField(
            model_name='csdetailtemp',
            name='csmain',
        ),
        migrations.RemoveField(
            model_name='csdetailtemp',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='csdetailtemp',
            name='enterby',
        ),
        migrations.RemoveField(
            model_name='csdetailtemp',
            name='invitem',
        ),
        migrations.RemoveField(
            model_name='csdetailtemp',
            name='modifyby',
        ),
        migrations.RemoveField(
            model_name='csdetailtemp',
            name='postby',
        ),
        migrations.RemoveField(
            model_name='csdetailtemp',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='csdetailtemp',
            name='vat',
        ),
        migrations.AlterField(
            model_name='csdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 20, 11, 9, 36, 612000)),
        ),
        migrations.AlterField(
            model_name='csdetail',
            name='postdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 20, 11, 9, 36, 612000), null=True),
        ),
        migrations.AlterField(
            model_name='csmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 20, 11, 9, 36, 606000)),
        ),
        migrations.DeleteModel(
            name='Csdetailtemp',
        ),
    ]
