# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-20 11:10
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryitem', '0011_auto_20170420_1110'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vat', '0008_auto_20170420_1110'),
        ('supplier', '0010_auto_20170420_1110'),
        ('currency', '0006_auto_20170420_1110'),
        ('canvasssheet', '0008_auto_20170420_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Csdetailtemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitem_code', models.CharField(max_length=25)),
                ('invitem_name', models.CharField(max_length=250)),
                ('item_counter', models.IntegerField()),
                ('suppliercode', models.CharField(blank=True, max_length=10, null=True)),
                ('suppliername', models.CharField(blank=True, max_length=250, null=True)),
                ('vatrate', models.IntegerField(default=0)),
                ('unitcost', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('negocost', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('secretkey', models.CharField(max_length=255)),
                ('csstatus', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('C', 'Cancelled'), ('O', 'Posted'), ('P', 'Printed')], default='A', max_length=1)),
                ('enterdate', models.DateTimeField(auto_now_add=True)),
                ('modifydate', models.DateTimeField(default=datetime.datetime(2017, 4, 20, 11, 10, 45, 743000))),
                ('postdate', models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 20, 11, 10, 45, 743000), null=True)),
                ('isdeleted', models.IntegerField(default=0)),
                ('vatable', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('vatexempt', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('vatzerorated', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('grossamount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('vatamount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('netamount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'csdetailtemp',
            },
        ),
        migrations.AlterField(
            model_name='csdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 20, 11, 10, 45, 737000)),
        ),
        migrations.AlterField(
            model_name='csdetail',
            name='postdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 20, 11, 10, 45, 737000), null=True),
        ),
        migrations.AlterField(
            model_name='csmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 20, 11, 10, 45, 731000)),
        ),
        migrations.AddField(
            model_name='csdetailtemp',
            name='csdetail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='csdetailtemp_csdetail_id', to='canvasssheet.Csdetail'),
        ),
        migrations.AddField(
            model_name='csdetailtemp',
            name='csmain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csdetailtemp_csmain_id', to='canvasssheet.Csmain'),
        ),
        migrations.AddField(
            model_name='csdetailtemp',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csdetailtemp_currency', to='currency.Currency'),
        ),
        migrations.AddField(
            model_name='csdetailtemp',
            name='enterby',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='csdetailtemp_enter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='csdetailtemp',
            name='invitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csdetailtemp_invitem_id', to='inventoryitem.Inventoryitem'),
        ),
        migrations.AddField(
            model_name='csdetailtemp',
            name='modifyby',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='csdetailtemp_modify', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='csdetailtemp',
            name='postby',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='csdetailtemp_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='csdetailtemp',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csdetailtemp_supplier_id', to='supplier.Supplier'),
        ),
        migrations.AddField(
            model_name='csdetailtemp',
            name='vat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csdetailtemp_vat_id', to='vat.Vat'),
        ),
    ]
