# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-20 14:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchaserequisitionform', '0017_auto_20170420_1400'),
        ('canvasssheet', '0009_auto_20170420_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Csdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secretkey', models.CharField(max_length=255)),
                ('isdeleted', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'csdata',
            },
        ),
        migrations.AlterField(
            model_name='csdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 20, 14, 0, 4, 433000)),
        ),
        migrations.AlterField(
            model_name='csdetail',
            name='postdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 20, 14, 0, 4, 433000), null=True),
        ),
        migrations.AlterField(
            model_name='csdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 20, 14, 0, 4, 436000)),
        ),
        migrations.AlterField(
            model_name='csdetailtemp',
            name='postdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 20, 14, 0, 4, 436000), null=True),
        ),
        migrations.AlterField(
            model_name='csmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 20, 14, 0, 4, 427000)),
        ),
        migrations.AddField(
            model_name='csdata',
            name='csmain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csdata_csmain_id', to='canvasssheet.Csmain'),
        ),
        migrations.AddField(
            model_name='csdata',
            name='prfmain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csdata_prfmain_id', to='purchaserequisitionform.Prfmain'),
        ),
    ]
