# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-26 06:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvasssheet', '0015_auto_20170425_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='csmain',
            name='grossamount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='csmain',
            name='netamount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='csmain',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csmain',
            name='vatable',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='csmain',
            name='vatamount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='csmain',
            name='vatexempt',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='csmain',
            name='vatzerorated',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='csdata',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 26, 6, 39, 8, 738000)),
        ),
        migrations.AlterField(
            model_name='csdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 26, 6, 39, 8, 743000)),
        ),
        migrations.AlterField(
            model_name='csdetail',
            name='postdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 26, 6, 39, 8, 743000), null=True),
        ),
        migrations.AlterField(
            model_name='csdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 26, 6, 39, 8, 751000)),
        ),
        migrations.AlterField(
            model_name='csdetailtemp',
            name='postdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 26, 6, 39, 8, 751000), null=True),
        ),
        migrations.AlterField(
            model_name='csmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 26, 6, 39, 8, 726000)),
        ),
    ]
