# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-26 16:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvasssheet', '0017_auto_20170426_0714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csmain',
            options={'ordering': ['-pk'], 'permissions': (('view_canvasssheet', 'Can view canvasssheet'),)},
        ),
        migrations.AlterField(
            model_name='csdata',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 26, 16, 30, 2, 557000)),
        ),
        migrations.AlterField(
            model_name='csdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 26, 16, 30, 2, 560000)),
        ),
        migrations.AlterField(
            model_name='csdetail',
            name='postdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 26, 16, 30, 2, 560000), null=True),
        ),
        migrations.AlterField(
            model_name='csdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 26, 16, 30, 2, 563000)),
        ),
        migrations.AlterField(
            model_name='csdetailtemp',
            name='postdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 26, 16, 30, 2, 563000), null=True),
        ),
        migrations.AlterField(
            model_name='csmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 26, 16, 30, 2, 553000)),
        ),
    ]
