# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-05-10 15:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchaserequisitionform', '0035_auto_20170510_1515'),
        ('canvasssheet', '0020_auto_20170503_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='csdetail',
            name='prfmain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prfmain_csdetail', to='purchaserequisitionform.Prfmain'),
        ),
        migrations.AddField(
            model_name='csdetailtemp',
            name='prfmain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prfmain_csdetailtemp', to='purchaserequisitionform.Prfmain'),
        ),
        migrations.AlterField(
            model_name='csdata',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 10, 15, 15, 6, 742000)),
        ),
        migrations.AlterField(
            model_name='csdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 10, 15, 15, 6, 743000)),
        ),
        migrations.AlterField(
            model_name='csdetail',
            name='postdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 5, 10, 15, 15, 6, 744000), null=True),
        ),
        migrations.AlterField(
            model_name='csdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 10, 15, 15, 6, 747000)),
        ),
        migrations.AlterField(
            model_name='csdetailtemp',
            name='postdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 5, 10, 15, 15, 6, 747000), null=True),
        ),
        migrations.AlterField(
            model_name='csmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 10, 15, 15, 6, 739000)),
        ),
    ]
