# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-05-10 15:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchaserequisitionform', '0036_auto_20170510_1527'),
        ('canvasssheet', '0021_auto_20170510_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='csdetail',
            name='prfdetail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prfdetail_csdetail', to='purchaserequisitionform.Prfdetail'),
        ),
        migrations.AddField(
            model_name='csdetailtemp',
            name='prfdetail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prfdetail_csdetailtemp', to='purchaserequisitionform.Prfdetail'),
        ),
        migrations.AlterField(
            model_name='csdata',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 10, 15, 27, 3, 764000)),
        ),
        migrations.AlterField(
            model_name='csdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 10, 15, 27, 3, 766000)),
        ),
        migrations.AlterField(
            model_name='csdetail',
            name='postdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 5, 10, 15, 27, 3, 766000), null=True),
        ),
        migrations.AlterField(
            model_name='csdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 10, 15, 27, 3, 769000)),
        ),
        migrations.AlterField(
            model_name='csdetailtemp',
            name='postdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 5, 10, 15, 27, 3, 769000), null=True),
        ),
        migrations.AlterField(
            model_name='csmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 10, 15, 27, 3, 761000)),
        ),
    ]
