# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-05-15 11:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvasssheet', '0022_auto_20170510_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='csdetail',
            name='itemdetailkey',
            field=models.CharField(default=datetime.datetime(2017, 5, 15, 11, 40, 24, 148000), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csdetailtemp',
            name='itemdetailkey',
            field=models.CharField(default=datetime.datetime(2017, 5, 15, 11, 40, 31, 372000), max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='csdata',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 15, 11, 39, 50, 749000)),
        ),
        migrations.AlterField(
            model_name='csdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 15, 11, 39, 50, 755000)),
        ),
        migrations.AlterField(
            model_name='csdetail',
            name='postdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 5, 15, 11, 39, 50, 755000), null=True),
        ),
        migrations.AlterField(
            model_name='csdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 15, 11, 39, 50, 766000)),
        ),
        migrations.AlterField(
            model_name='csdetailtemp',
            name='postdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 5, 15, 11, 39, 50, 767000), null=True),
        ),
        migrations.AlterField(
            model_name='csmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 15, 11, 39, 50, 739000)),
        ),
    ]
