# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-05-19 03:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unitofmeasure', '0006_auto_20170519_1125'),
        ('department', '0020_auto_20170519_1125'),
        ('canvasssheet', '0023_auto_20170515_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='csdetail',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='csdetail_department_id', to='department.Department'),
        ),
        migrations.AddField(
            model_name='csdetail',
            name='department_code',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='csdetail',
            name='department_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='csdetail',
            name='invitem_unitofmeasure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='csdetail_unitofmeasure_id', to='unitofmeasure.Unitofmeasure'),
        ),
        migrations.AddField(
            model_name='csdetail',
            name='invitem_unitofmeasure_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='csdetailtemp',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='csdetailtemp_department_id', to='department.Department'),
        ),
        migrations.AddField(
            model_name='csdetailtemp',
            name='department_code',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='csdetailtemp',
            name='department_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='csdetailtemp',
            name='invitem_unitofmeasure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='csdetailtemp_unitofmeasure_id', to='unitofmeasure.Unitofmeasure'),
        ),
        migrations.AddField(
            model_name='csdetailtemp',
            name='invitem_unitofmeasure_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='csdata',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 19, 11, 25, 26, 956000)),
        ),
        migrations.AlterField(
            model_name='csdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 19, 11, 25, 26, 958000)),
        ),
        migrations.AlterField(
            model_name='csdetail',
            name='postdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 5, 19, 11, 25, 26, 958000), null=True),
        ),
        migrations.AlterField(
            model_name='csdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 19, 11, 25, 26, 961000)),
        ),
        migrations.AlterField(
            model_name='csdetailtemp',
            name='postdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 5, 19, 11, 25, 26, 961000), null=True),
        ),
        migrations.AlterField(
            model_name='csmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 19, 11, 25, 26, 953000)),
        ),
    ]
