# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-11-21 07:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankbranch', '0006_auto_20171107_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankbranch',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 21, 15, 18, 37, 415000)),
        ),
    ]
