# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-27 02:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptype', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aptype',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 27, 10, 40, 19, 224000)),
        ),
    ]
