# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-03-26 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outputvattype', '0005_auto_20180322_1106'),
        ('outputvat', '0013_auto_20180322_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='outputvat',
            name='outputvattype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='outputvat_outputvattype', to='outputvattype.Outputvattype'),
            preserve_default=False,
        ),
    ]
