# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-20 09:18
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rfdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_counter', models.IntegerField()),
                ('item_name', models.CharField(max_length=250)),
                ('unitofmeasure', models.CharField(max_length=15)),
                ('quantity', models.IntegerField()),
                ('remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('C', 'Cancelled'), ('O', 'Posted'), ('P', 'Printed')], default='A', max_length=1)),
                ('enterdate', models.DateTimeField(auto_now_add=True)),
                ('modifydate', models.DateTimeField(default=datetime.datetime(2017, 3, 20, 9, 18, 44, 802000))),
                ('postdate', models.DateTimeField(default=datetime.datetime(2017, 3, 20, 9, 18, 44, 802000))),
                ('isdeleted', models.IntegerField(default=0)),
                ('enterby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rfdetail_enter', to=settings.AUTH_USER_MODEL)),
                ('modifyby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rfdetail_modify', to=settings.AUTH_USER_MODEL)),
                ('postby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rfdetail_post', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'rfdetail',
            },
        ),
        migrations.CreateModel(
            name='Rfdetailtemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_counter', models.IntegerField()),
                ('item_name', models.CharField(max_length=250)),
                ('unitofmeasure', models.CharField(max_length=15)),
                ('quantity', models.IntegerField()),
                ('remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('secretkey', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('C', 'Cancelled'), ('O', 'Posted'), ('P', 'Printed')], default='A', max_length=1)),
                ('enterdate', models.DateTimeField(auto_now_add=True)),
                ('modifydate', models.DateTimeField(default=datetime.datetime(2017, 3, 20, 9, 18, 44, 802000))),
                ('postdate', models.DateTimeField(default=datetime.datetime(2017, 3, 20, 9, 18, 44, 802000))),
                ('isdeleted', models.IntegerField(default=0)),
                ('enterby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rfdetailtemp_enter', to=settings.AUTH_USER_MODEL)),
                ('modifyby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rfdetailtemp_modify', to=settings.AUTH_USER_MODEL)),
                ('postby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rfdetailtemp_post', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'rfdetailtemp',
            },
        ),
        migrations.CreateModel(
            name='Rfmain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfnum', models.CharField(max_length=10, unique=True)),
                ('rfdate', models.DateField()),
                ('refnum', models.CharField(blank=True, max_length=150, null=True)),
                ('jonum', models.CharField(blank=True, max_length=150, null=True)),
                ('sonum', models.CharField(blank=True, max_length=150, null=True)),
                ('urgencytype', models.CharField(choices=[('N', 'Normal'), ('R', 'Rush')], default='N', max_length=1)),
                ('dateneeded', models.DateField()),
                ('particulars', models.TextField()),
                ('rfstatus', models.CharField(choices=[('F', 'For Approval'), ('A', 'Approved'), ('D', 'Disapproved')], default='F', max_length=1)),
                ('approverresponse', models.CharField(blank=True, choices=[('A', 'Approved'), ('D', 'Disapproved')], max_length=1, null=True)),
                ('responsedate', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('C', 'Cancelled'), ('O', 'Posted'), ('P', 'Printed')], default='A', max_length=1)),
                ('enterdate', models.DateTimeField(auto_now_add=True)),
                ('modifydate', models.DateTimeField(default=datetime.datetime(2017, 3, 20, 9, 18, 44, 802000))),
                ('postdate', models.DateTimeField(default=datetime.datetime(2017, 3, 20, 9, 18, 44, 802000))),
                ('isdeleted', models.IntegerField(default=0)),
                ('actualapprover', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actual_approver', to=settings.AUTH_USER_MODEL)),
                ('designatedapprover', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='designated_approver', to=settings.AUTH_USER_MODEL)),
                ('enterby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rfmain_enter', to=settings.AUTH_USER_MODEL)),
                ('modifyby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rfmain_modify', to=settings.AUTH_USER_MODEL)),
                ('postby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rfmain_post', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'rfmain',
            },
        ),
        migrations.AddField(
            model_name='rfdetailtemp',
            name='rfmain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_rfmain_id', to='requisitionform.Rfmain'),
        ),
        migrations.AddField(
            model_name='rfdetail',
            name='rfmain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfmain_id', to='requisitionform.Rfmain'),
        ),
    ]
