# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-20 13:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_auto_20170320_1335'),
        ('department', '0006_auto_20170320_1335'),
        ('requisitionform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfmain',
            name='branch',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='rfbranch_id', to='branch.Branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rfmain',
            name='department',
            field=models.ForeignKey(default=69, on_delete=django.db.models.deletion.CASCADE, related_name='rfdepartment_id', to='department.Department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rfdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 20, 13, 34, 28, 332000)),
        ),
        migrations.AlterField(
            model_name='rfdetail',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 20, 13, 34, 28, 332000)),
        ),
        migrations.AlterField(
            model_name='rfdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 20, 13, 34, 28, 333000)),
        ),
        migrations.AlterField(
            model_name='rfdetailtemp',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 20, 13, 34, 28, 333000)),
        ),
        migrations.AlterField(
            model_name='rfmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 20, 13, 34, 28, 330000)),
        ),
        migrations.AlterField(
            model_name='rfmain',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 20, 13, 34, 28, 330000)),
        ),
    ]
