# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-23 11:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitionform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 23, 11, 15, 23, 93000)),
        ),
        migrations.AlterField(
            model_name='rfdetail',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 23, 11, 15, 23, 93000)),
        ),
        migrations.AlterField(
            model_name='rfdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 23, 11, 15, 23, 95000)),
        ),
        migrations.AlterField(
            model_name='rfdetailtemp',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 23, 11, 15, 23, 95000)),
        ),
        migrations.AlterField(
            model_name='rfmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 23, 11, 15, 23, 91000)),
        ),
    ]
