# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-23 11:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitionform', '0003_auto_20170323_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rfdetail',
            old_name='invitem_id',
            new_name='invitem',
        ),
        migrations.RenameField(
            model_name='rfdetailtemp',
            old_name='invitem_id',
            new_name='invitem',
        ),
        migrations.AlterField(
            model_name='rfdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 23, 11, 32, 18, 539000)),
        ),
        migrations.AlterField(
            model_name='rfdetail',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 23, 11, 32, 18, 539000)),
        ),
        migrations.AlterField(
            model_name='rfdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 23, 11, 32, 18, 541000)),
        ),
        migrations.AlterField(
            model_name='rfdetailtemp',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 23, 11, 32, 18, 541000)),
        ),
        migrations.AlterField(
            model_name='rfmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 23, 11, 32, 18, 536000)),
        ),
    ]
