# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-21 13:41
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requisitionform', '0003_auto_20170321_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 21, 13, 41, 35, 368000)),
        ),
        migrations.AlterField(
            model_name='rfdetail',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 21, 13, 41, 35, 368000)),
        ),
        migrations.AlterField(
            model_name='rfdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 21, 13, 41, 35, 369000)),
        ),
        migrations.AlterField(
            model_name='rfdetailtemp',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 21, 13, 41, 35, 370000)),
        ),
        migrations.AlterField(
            model_name='rfmain',
            name='designatedapprover',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='designated_approver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rfmain',
            name='inventoryitemtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfmain_inventoryitemtype_id', to='inventoryitemtype.Inventoryitemtype'),
        ),
        migrations.AlterField(
            model_name='rfmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 21, 13, 41, 35, 366000)),
        ),
        migrations.AlterField(
            model_name='rfmain',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 21, 13, 41, 35, 366000)),
        ),
    ]
