# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-23 11:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requisitionform', '0004_auto_20170323_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfdetailtemp',
            name='rfdetail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfdetailtemp_rfdetail_id', to='requisitionform.Rfdetail'),
        ),
        migrations.AlterField(
            model_name='rfdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 23, 11, 36, 49, 96000)),
        ),
        migrations.AlterField(
            model_name='rfdetail',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 23, 11, 36, 49, 97000)),
        ),
        migrations.AlterField(
            model_name='rfdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 23, 11, 36, 49, 98000)),
        ),
        migrations.AlterField(
            model_name='rfdetailtemp',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 23, 11, 36, 49, 98000)),
        ),
        migrations.AlterField(
            model_name='rfmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 23, 11, 36, 49, 94000)),
        ),
    ]
