# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-21 15:53
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requisitionform', '0004_auto_20170321_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 21, 15, 53, 23, 617000)),
        ),
        migrations.AlterField(
            model_name='rfdetail',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 21, 15, 53, 23, 617000)),
        ),
        migrations.AlterField(
            model_name='rfdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 21, 15, 53, 23, 619000)),
        ),
        migrations.AlterField(
            model_name='rfdetailtemp',
            name='postby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfdetailtemp_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rfdetailtemp',
            name='postdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rfmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 21, 15, 53, 23, 614000)),
        ),
        migrations.AlterField(
            model_name='rfmain',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 21, 15, 53, 23, 615000)),
        ),
    ]
