# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-23 09:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitionform', '0006_auto_20170321_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rfmain',
            old_name='jonum',
            new_name='rftype',
        ),
        migrations.RenameField(
            model_name='rfmain',
            old_name='sonum',
            new_name='unit',
        ),
        migrations.AlterField(
            model_name='rfdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 23, 9, 27, 20, 228000)),
        ),
        migrations.AlterField(
            model_name='rfdetail',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 23, 9, 27, 20, 228000)),
        ),
        migrations.AlterField(
            model_name='rfdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 23, 9, 27, 20, 230000)),
        ),
        migrations.AlterField(
            model_name='rfmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 23, 9, 27, 20, 226000)),
        ),
    ]
