# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-06 11:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitionform', '0010_auto_20170403_1353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rfmain',
            options={'ordering': ['-pk'], 'permissions': (('view_requisitionform', 'Can view requisitionform'), ('view_assignrf', 'Can view assignrf'), ('view_allassignrf', 'Can view allsasignrf'))},
        ),
        migrations.AlterField(
            model_name='rfdetail',
            name='enterdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 6, 11, 34, 52, 467000)),
        ),
        migrations.AlterField(
            model_name='rfdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 6, 11, 34, 52, 467000)),
        ),
        migrations.AlterField(
            model_name='rfdetailtemp',
            name='enterdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 6, 11, 34, 52, 469000)),
        ),
        migrations.AlterField(
            model_name='rfdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 6, 11, 34, 52, 469000)),
        ),
        migrations.AlterField(
            model_name='rfmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 6, 11, 34, 52, 464000)),
        ),
    ]
