# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-06 11:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitionform', '0011_auto_20170406_1134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rfmain',
            options={'ordering': ['-pk'], 'permissions': (('view_requisitionform', 'Can view requisitionform'), ('view_assignrf', 'Can view only assigned rf'), ('view_allassignrf', 'Can view all rf'), ('can_approverf', 'Can approve rf'), ('can_disapproverf', 'Can disapprove rf'))},
        ),
        migrations.AlterField(
            model_name='rfdetail',
            name='enterdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 6, 11, 53, 19, 455000)),
        ),
        migrations.AlterField(
            model_name='rfdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 6, 11, 53, 19, 455000)),
        ),
        migrations.AlterField(
            model_name='rfdetailtemp',
            name='enterdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 6, 11, 53, 19, 458000)),
        ),
        migrations.AlterField(
            model_name='rfdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 6, 11, 53, 19, 458000)),
        ),
        migrations.AlterField(
            model_name='rfmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 6, 11, 53, 19, 453000)),
        ),
    ]
