# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-10 12:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unitofmeasure', '0003_auto_20170410_1249'),
        ('requisitionform', '0023_auto_20170410_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfdetail',
            name='invitem_unitofmeasure',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='rfdetail_unitofmeasure_id', to='unitofmeasure.Unitofmeasure'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rfdetail',
            name='invitem_unitofmeasure_code',
            field=models.CharField(default='pc', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rfdetailtemp',
            name='invitem_unitofmeasure',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='rfdetailtemp_unitofmeasure_id', to='unitofmeasure.Unitofmeasure'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rfdetailtemp',
            name='invitem_unitofmeasure_code',
            field=models.CharField(default='pc', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rfdetail',
            name='enterdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 10, 12, 48, 34, 154000)),
        ),
        migrations.AlterField(
            model_name='rfdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 10, 12, 48, 34, 154000)),
        ),
        migrations.AlterField(
            model_name='rfdetailtemp',
            name='enterdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 10, 12, 48, 34, 156000)),
        ),
        migrations.AlterField(
            model_name='rfdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 10, 12, 48, 34, 156000)),
        ),
        migrations.AlterField(
            model_name='rfmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 10, 12, 48, 34, 152000)),
        ),
    ]
