# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-26 10:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitionform', '0024_auto_20170410_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfdetail',
            name='enterdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 26, 10, 19, 55, 951000)),
        ),
        migrations.AlterField(
            model_name='rfdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 26, 10, 19, 55, 951000)),
        ),
        migrations.AlterField(
            model_name='rfdetailtemp',
            name='enterdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 26, 10, 19, 55, 953000)),
        ),
        migrations.AlterField(
            model_name='rfdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 26, 10, 19, 55, 953000)),
        ),
        migrations.AlterField(
            model_name='rfmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 26, 10, 19, 55, 949000)),
        ),
        migrations.AlterField(
            model_name='rfmain',
            name='rftype',
            field=models.CharField(choices=[('REG', 'Regular')], default='REG', max_length=10),
        ),
    ]
