# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-05-04 16:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchaserequisitionform', '0025_auto_20170504_1644'),
        ('requisitionform', '0032_auto_20170504_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfdetail',
            name='rfprftransaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfprftransaction_id', to='purchaserequisitionform.rfprftransaction'),
        ),
        migrations.AlterField(
            model_name='rfdetail',
            name='enterdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 4, 16, 44, 25, 983000)),
        ),
        migrations.AlterField(
            model_name='rfdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 4, 16, 44, 25, 983000)),
        ),
        migrations.AlterField(
            model_name='rfdetailtemp',
            name='enterdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 4, 16, 44, 25, 988000)),
        ),
        migrations.AlterField(
            model_name='rfdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 4, 16, 44, 25, 988000)),
        ),
        migrations.AlterField(
            model_name='rfmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 4, 16, 44, 25, 981000)),
        ),
    ]
