# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-05-05 16:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitionform', '0034_auto_20170505_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfdetailtemp',
            name='isfullyprf',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rfdetailtemp',
            name='prfremainingquantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rfdetailtemp',
            name='prftotalquantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rfdetail',
            name='enterdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 5, 16, 47, 27, 503000)),
        ),
        migrations.AlterField(
            model_name='rfdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 5, 16, 47, 27, 503000)),
        ),
        migrations.AlterField(
            model_name='rfdetailtemp',
            name='enterdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 5, 16, 47, 27, 510000)),
        ),
        migrations.AlterField(
            model_name='rfdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 5, 16, 47, 27, 510000)),
        ),
        migrations.AlterField(
            model_name='rfmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 5, 16, 47, 27, 499000)),
        ),
    ]
