# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-05-10 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisitionform', '0035_auto_20170505_1647'),
        ('requisitionform', '0031_auto_20170504_1635'),
    ]

    operations = [
    ]
