# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-03-26 02:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitionform', '0038_auto_20180322_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfdetail',
            name='enterdate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 26, 10, 35, 31, 236000)),
        ),
        migrations.AlterField(
            model_name='rfdetailtemp',
            name='enterdate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 26, 10, 35, 31, 238000)),
        ),
    ]
