# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-08-14 14:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenttype', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenttype',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 14, 14, 13, 9, 521000)),
        ),
    ]
