# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-03-21 08:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenttype', '0003_auto_20180321_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenttype',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 16, 55, 43, 871000)),
        ),
    ]
