# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-22 15:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20170322_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 22, 15, 6, 1, 119000)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='multiplestatus',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1),
        ),
    ]
