# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-28 15:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20170727_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 28, 15, 19, 2, 217000)),
        ),
    ]
