# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-05-09 11:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vat', '0026_auto_20180322_1106'),
        ('customer', '0018_auto_20180322_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='vat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_vat_id', to='vat.Vat', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='customer',
            name='vatrate',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
