# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-11-27 06:13
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0025_auto_20180322_1106'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supplier', '0041_auto_20180424_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplieraccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountno', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('phoneno', models.CharField(blank=True, max_length=20, null=True)),
                ('duono', models.CharField(blank=True, max_length=20, null=True)),
                ('serialno', models.CharField(blank=True, max_length=20, null=True)),
                ('imeino', models.CharField(blank=True, max_length=20, null=True)),
                ('amountsubsidy', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('accountgroup', models.CharField(choices=[('B', 'HO/Business Group'), ('E', 'Editorial Group'), ('R', 'Branches'), ('L', 'LRP Bldg/Finance Group'), ('M', 'Modem Lines'), ('W', 'WeRoam'), ('C', 'Corporate Account'), ('O', 'Others')], max_length=1)),
                ('accountcategory', models.CharField(choices=[('T', 'Trunk Line'), ('D', 'Direct Line'), ('F', 'Telefax'), ('C', 'Cellphone'), ('M', 'Modem Lines'), ('W', 'WeRoam'), ('O', 'Others')], max_length=1)),
                ('remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('C', 'Cancelled'), ('O', 'Posted'), ('P', 'Printed')], default='A', max_length=1)),
                ('enterdate', models.DateTimeField(auto_now_add=True)),
                ('modifydate', models.DateTimeField(auto_now_add=True)),
                ('isdeleted', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplieraccount_employee_id', to='employee.Employee', validators=[django.core.validators.MinValueValidator(1)])),
                ('enterby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='supplieraccount_enter', to=settings.AUTH_USER_MODEL)),
                ('modifyby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='supplieraccount_modify', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplieraccount_supplier_id', to='supplier.Supplier', validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'supplieraccount',
                'permissions': (('view_supplieraccount', 'Can view supplieraccount'),),
            },
        ),
    ]
