# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-11-27 06:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplieraccount', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplieraccount',
            old_name='amountsubsidy',
            new_name='subsidyamount',
        ),
    ]
