# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-06-22 06:04
from __future__ import unicode_literals
from django.db import migrations, models
import django.db.models.deletion

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccountmaingroup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ChartofAccountMainGroup',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='chartofaccountmaingroup_group', to='chartofaccountmaingroup.ChartofAccountMainGroup'),
        ),
    ]
