# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-06-22 07:13
from __future__ import unicode_literals
from django.db import migrations, models
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccountmaingroup', '0002_auto_20180622_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccountmaingroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='chartofaccountmaingroup_groupings',
                                    to='chartofaccountmaingroup.ChartofAccountMainGroup', blank=True, null=True,),
            preserve_default=False,
        ),
    ]
