# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-06-26 09:49
from __future__ import unicode_literals
from django.db import migrations, models
import django.db.models.deletion

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccountmaingroup', '0003_auto_20180622_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccountmaingroup',
            name='balancecode',
            field=models.CharField(choices=[('D', 'Debit'), ('C', 'Credit')], default='D', max_length=1),
        ),
    ]
