# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-11-15 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccountmaingroup', '0004_auto_20180626_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccountmaingroup',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
