# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-10-10 11:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orsubtype', '0002_auto_20171010_1952'),
        ('creditcard', '0002_auto_20171010_1952'),
        ('outputvattype', '0002_auto_20171010_1952'),
        ('officialreceipt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oritem',
            name='creditcard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oritem_creditcard_id', to='creditcard.Creditcard'),
        ),
        migrations.AddField(
            model_name='oritemtemp',
            name='creditcard',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ormain',
            name='orsubtype',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='ormain_orsubtype_id', to='orsubtype.Orsubtype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ormain',
            name='outputvattype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ormain_outvattype_id', to='outputvattype.Outputvattype'),
        ),
        migrations.AlterField(
            model_name='ordetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 10, 19, 50, 54, 968000)),
        ),
        migrations.AlterField(
            model_name='ordetailbreakdown',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 10, 19, 50, 54, 972000)),
        ),
        migrations.AlterField(
            model_name='ordetailbreakdowntemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 10, 19, 50, 54, 981000)),
        ),
        migrations.AlterField(
            model_name='ordetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 10, 19, 50, 54, 978000)),
        ),
        migrations.AlterField(
            model_name='oritem',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 10, 19, 50, 54, 965000)),
        ),
        migrations.AlterField(
            model_name='oritemtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 10, 19, 50, 54, 976000)),
        ),
        migrations.AlterField(
            model_name='ormain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 10, 19, 50, 54, 961000)),
        ),
    ]
