# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-10-10 12:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0016_auto_20171010_2005'),
        ('officialreceipt', '0002_auto_20171010_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='ormain',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ormain_currency_id', to='currency.Currency'),
        ),
        migrations.AddField(
            model_name='ormain',
            name='fxrate',
            field=models.DecimalField(decimal_places=5, default=1.0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='ordetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 10, 20, 5, 37, 839000)),
        ),
        migrations.AlterField(
            model_name='ordetailbreakdown',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 10, 20, 5, 37, 843000)),
        ),
        migrations.AlterField(
            model_name='ordetailbreakdowntemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 10, 20, 5, 37, 851000)),
        ),
        migrations.AlterField(
            model_name='ordetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 10, 20, 5, 37, 848000)),
        ),
        migrations.AlterField(
            model_name='oritem',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 10, 20, 5, 37, 837000)),
        ),
        migrations.AlterField(
            model_name='oritemtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 10, 20, 5, 37, 846000)),
        ),
        migrations.AlterField(
            model_name='ormain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 10, 20, 5, 37, 833000)),
        ),
    ]
