# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-10-11 08:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20171011_1604'),
        ('agent', '0002_auto_20171011_1604'),
        ('customer', '0013_auto_20171011_1604'),
        ('officialreceipt', '0004_auto_20171010_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oritem',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='oritem',
            name='bankbranch',
        ),
        migrations.RemoveField(
            model_name='oritem',
            name='creditcard',
        ),
        migrations.RemoveField(
            model_name='oritem',
            name='enterby',
        ),
        migrations.RemoveField(
            model_name='oritem',
            name='modifyby',
        ),
        migrations.RemoveField(
            model_name='oritem',
            name='ormain',
        ),
        migrations.RemoveField(
            model_name='oritem',
            name='paytype',
        ),
        migrations.RemoveField(
            model_name='oritem',
            name='postby',
        ),
        migrations.RemoveField(
            model_name='oritemtemp',
            name='enterby',
        ),
        migrations.RemoveField(
            model_name='oritemtemp',
            name='modifyby',
        ),
        migrations.RemoveField(
            model_name='oritemtemp',
            name='postby',
        ),
        migrations.RemoveField(
            model_name='ormain',
            name='adtype',
        ),
        migrations.RemoveField(
            model_name='ormain',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='ormain',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='ormain',
            name='customer_address1',
        ),
        migrations.RemoveField(
            model_name='ormain',
            name='customer_address2',
        ),
        migrations.RemoveField(
            model_name='ormain',
            name='customer_address3',
        ),
        migrations.RemoveField(
            model_name='ormain',
            name='customer_celno',
        ),
        migrations.RemoveField(
            model_name='ormain',
            name='customer_code',
        ),
        migrations.RemoveField(
            model_name='ormain',
            name='customer_faxno',
        ),
        migrations.RemoveField(
            model_name='ormain',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='ormain',
            name='customer_telno1',
        ),
        migrations.RemoveField(
            model_name='ormain',
            name='customer_telno2',
        ),
        migrations.RemoveField(
            model_name='ormain',
            name='customer_tin',
        ),
        migrations.RemoveField(
            model_name='ormain',
            name='customer_zipcode',
        ),
        migrations.RemoveField(
            model_name='ormain',
            name='orsubtype',
        ),
        migrations.AddField(
            model_name='ormain',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ormain_agency_id', to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='ormain',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ormain_agent_id', to='agent.Agent'),
        ),
        migrations.AddField(
            model_name='ormain',
            name='approverremarks',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='ormain',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ormain_client_id', to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='ormain',
            name='collector_code',
            field=models.CharField(default='TEST', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ormain',
            name='collector_name',
            field=models.CharField(default='Test Collector 100', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ormain',
            name='orsource',
            field=models.CharField(choices=[('A', 'Advertising'), ('C', 'Circulation')], default='A', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ormain',
            name='payee_code',
            field=models.CharField(default='4J', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ormain',
            name='payee_name',
            field=models.CharField(default='4J INDUSTRIES', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ormain',
            name='payee_type',
            field=models.CharField(choices=[('AG', 'Agency'), ('C', 'Client'), ('A', 'Agent')], default='AG', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ormain',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ormain_product_id', to='product.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ormain',
            name='product_code',
            field=models.CharField(default='DLY', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ormain',
            name='product_name',
            field=models.CharField(default='DAILY', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 11, 16, 2, 15, 988000)),
        ),
        migrations.AlterField(
            model_name='ordetailbreakdown',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 11, 16, 2, 15, 992000)),
        ),
        migrations.AlterField(
            model_name='ordetailbreakdowntemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 11, 16, 2, 15, 999000)),
        ),
        migrations.AlterField(
            model_name='ordetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 11, 16, 2, 15, 996000)),
        ),
        migrations.AlterField(
            model_name='ormain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 11, 16, 2, 15, 982000)),
        ),
        migrations.AlterField(
            model_name='ormain',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Oritem',
        ),
        migrations.DeleteModel(
            name='Oritemtemp',
        ),
    ]
