# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-10-25 02:45
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('officialreceipt', '0005_auto_20171011_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 25, 10, 45, 16, 995000)),
        ),
        migrations.AlterField(
            model_name='ordetailbreakdown',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 25, 10, 45, 16, 999000)),
        ),
        migrations.AlterField(
            model_name='ordetailbreakdowntemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 25, 10, 45, 17, 5000)),
        ),
        migrations.AlterField(
            model_name='ordetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 25, 10, 45, 17, 2000)),
        ),
        migrations.AlterField(
            model_name='ormain',
            name='designatedapprover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ormain_designated_approver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ormain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 25, 10, 45, 16, 989000)),
        ),
    ]
