# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-11-06 05:38
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('officialreceipt', '0006_auto_20171025_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='ormain',
            name='glsdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ormain',
            name='glsmark',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ormain',
            name='importby',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ormain_import', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ormain',
            name='importdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ormain',
            name='importordate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ormain',
            name='importornum',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ormain',
            name='initmark',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ordetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 6, 13, 38, 48, 634000)),
        ),
        migrations.AlterField(
            model_name='ordetailbreakdown',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 6, 13, 38, 48, 639000)),
        ),
        migrations.AlterField(
            model_name='ordetailbreakdowntemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 6, 13, 38, 48, 645000)),
        ),
        migrations.AlterField(
            model_name='ordetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 6, 13, 38, 48, 643000)),
        ),
        migrations.AlterField(
            model_name='ormain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 6, 13, 38, 48, 629000)),
        ),
    ]
