# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-11-07 09:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productgroup', '0002_auto_20171107_1712'),
        ('circulationproduct', '0002_auto_20171107_1712'),
        ('officialreceipt', '0007_auto_20171106_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordetailbreakdown',
            old_name='of_date',
            new_name='or_date',
        ),
        migrations.RenameField(
            model_name='ordetailbreakdown',
            old_name='of_num',
            new_name='or_num',
        ),
        migrations.AddField(
            model_name='ormain',
            name='circulationproduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ormain_circulationproduct_id', to='circulationproduct.Circulationproduct'),
        ),
        migrations.AddField(
            model_name='ormain',
            name='productgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ormain_productgroup_id', to='productgroup.Productgroup'),
        ),
        migrations.AlterField(
            model_name='ordetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 7, 17, 12, 1, 86000)),
        ),
        migrations.AlterField(
            model_name='ordetailbreakdown',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 7, 17, 12, 1, 94000)),
        ),
        migrations.AlterField(
            model_name='ordetailbreakdowntemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 7, 17, 12, 1, 104000)),
        ),
        migrations.AlterField(
            model_name='ordetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 7, 17, 12, 1, 100000)),
        ),
        migrations.AlterField(
            model_name='ormain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 7, 17, 12, 1, 81000)),
        ),
    ]
