# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-11-08 05:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('officialreceipt', '0008_auto_20171107_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 13, 49, 15, 897000)),
        ),
        migrations.AlterField(
            model_name='ordetailbreakdown',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 13, 49, 15, 902000)),
        ),
        migrations.AlterField(
            model_name='ordetailbreakdowntemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 13, 49, 15, 911000)),
        ),
        migrations.AlterField(
            model_name='ordetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 13, 49, 15, 906000)),
        ),
        migrations.AlterField(
            model_name='ormain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 13, 49, 15, 891000)),
        ),
        migrations.AlterField(
            model_name='ormain',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ormain_product_id', to='product.Product'),
        ),
        migrations.AlterField(
            model_name='ormain',
            name='product_code',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='ormain',
            name='product_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
