# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-12-21 02:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officialreceipt', '0010_auto_20171108_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='ormain',
            name='acctentry_incomplete',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ormain',
            name='transaction_type',
            field=models.CharField(default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='ordetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 21, 10, 55, 45, 447000)),
        ),
        migrations.AlterField(
            model_name='ordetailbreakdown',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 21, 10, 55, 45, 455000)),
        ),
        migrations.AlterField(
            model_name='ordetailbreakdowntemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 21, 10, 55, 45, 466000)),
        ),
        migrations.AlterField(
            model_name='ordetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 21, 10, 55, 45, 461000)),
        ),
        migrations.AlterField(
            model_name='ormain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 21, 10, 55, 45, 437000)),
        ),
    ]
