# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-01 08:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officialreceipt', '0011_auto_20171221_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ormain',
            name='product',
        ),
        migrations.AlterField(
            model_name='ordetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 1, 16, 18, 57, 183000)),
        ),
        migrations.AlterField(
            model_name='ordetailbreakdown',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 1, 16, 18, 57, 186000)),
        ),
        migrations.AlterField(
            model_name='ordetailbreakdowntemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 1, 16, 18, 57, 193000)),
        ),
        migrations.AlterField(
            model_name='ordetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 1, 16, 18, 57, 191000)),
        ),
        migrations.AlterField(
            model_name='ormain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 1, 16, 18, 57, 178000)),
        ),
    ]
