# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-01 08:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circulationproduct', '0003_auto_20180201_1620'),
        ('officialreceipt', '0012_auto_20180201_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='ormain',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ormain_circulationprod_id', to='circulationproduct.Circulationproduct'),
        ),
        migrations.AlterField(
            model_name='ordetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 1, 16, 20, 50, 951000)),
        ),
        migrations.AlterField(
            model_name='ordetailbreakdown',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 1, 16, 20, 50, 956000)),
        ),
        migrations.AlterField(
            model_name='ordetailbreakdowntemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 1, 16, 20, 50, 966000)),
        ),
        migrations.AlterField(
            model_name='ordetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 1, 16, 20, 50, 962000)),
        ),
        migrations.AlterField(
            model_name='ormain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 1, 16, 20, 50, 944000)),
        ),
    ]
