# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-01 08:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('officialreceipt', '0013_auto_20180201_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 1, 16, 29, 34, 482000)),
        ),
        migrations.AlterField(
            model_name='ordetailbreakdown',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 1, 16, 29, 34, 487000)),
        ),
        migrations.AlterField(
            model_name='ordetailbreakdowntemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 1, 16, 29, 34, 493000)),
        ),
        migrations.AlterField(
            model_name='ordetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 1, 16, 29, 34, 490000)),
        ),
        migrations.AlterField(
            model_name='ormain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 1, 16, 29, 34, 477000)),
        ),
        migrations.AlterField(
            model_name='ormain',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ormain_product_id', to='product.Product'),
        ),
    ]
