# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-07 11:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officialreceipt', '0015_auto_20180201_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='ormain',
            name='logs',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ordetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 7, 19, 19, 25, 639000)),
        ),
        migrations.AlterField(
            model_name='ordetailbreakdown',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 7, 19, 19, 25, 639000)),
        ),
        migrations.AlterField(
            model_name='ordetailbreakdowntemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 7, 19, 19, 25, 647000)),
        ),
        migrations.AlterField(
            model_name='ordetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 7, 19, 19, 25, 643000)),
        ),
        migrations.AlterField(
            model_name='ormain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 7, 19, 19, 25, 635000)),
        ),
    ]
