# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-23 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryitem', '0003_auto_20170322_1501'),
        ('inventoryitem', '0004_auto_20170323_1109'),
    ]

    operations = [
    ]
