# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-27 13:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryitem', '0005_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 27, 13, 46, 35, 439000)),
        ),
    ]
