# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-04 20:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryitem', '0006_auto_20170327_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 4, 20, 11, 10, 796000)),
        ),
    ]
