# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-06 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryitem', '0007_auto_20170404_2011'),
        ('inventoryitem', '0007_auto_20170403_2049'),
    ]

    operations = [
    ]
