# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-03-23 03:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chartofaccount', '0038_auto_20180323_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subledgersummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('month', models.CharField(max_length=2)),
                ('beginning_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('beginning_code', models.CharField(blank=True, max_length=10, null=True)),
                ('beginning_date', models.DateTimeField(blank=True, null=True)),
                ('end_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('end_code', models.CharField(blank=True, max_length=10, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('year_to_date_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('year_to_date_code', models.CharField(blank=True, max_length=10, null=True)),
                ('year_to_date_date', models.DateTimeField(blank=True, null=True)),
                ('journal_voucher_credit_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('journal_voucher_debit_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('check_voucher_credit_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('check_voucher_debit_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('accounts_payable_voucher_credit_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('accounts_payable_voucher_debit_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('official_receipt_credit_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('official_receipt_debit_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('debit_credit_memo_credit_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('debit_credit_memo_debit_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('acknowledgement_receipt_credit_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('acknowledgement_receipt_debit_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('C', 'Cancelled'), ('O', 'Posted'), ('P', 'Printed')], default='A', max_length=1)),
                ('enterdate', models.DateTimeField(auto_now_add=True)),
                ('modifydate', models.DateTimeField(auto_now_add=True)),
                ('isdeleted', models.IntegerField(default=0)),
                ('chartofaccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subledgersumm_chartofaccount', to='chartofaccount.Chartofaccount')),
                ('enterby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subledgersumm_enter', to=settings.AUTH_USER_MODEL)),
                ('modifyby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subledgersumm_modify', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'subledgersummary',
                'permissions': (('view_subledgersummary', 'Can view subledgersummary'),),
            },
        ),
    ]
