# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-05-22 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subledgersummary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subledgersummary',
            name='accounts_payable_voucher_credit_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='subledgersummary',
            name='accounts_payable_voucher_debit_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='subledgersummary',
            name='acknowledgement_receipt_credit_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='subledgersummary',
            name='acknowledgement_receipt_debit_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='subledgersummary',
            name='check_voucher_credit_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='subledgersummary',
            name='check_voucher_debit_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='subledgersummary',
            name='debit_credit_memo_credit_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='subledgersummary',
            name='debit_credit_memo_debit_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='subledgersummary',
            name='journal_voucher_credit_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='subledgersummary',
            name='journal_voucher_debit_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='subledgersummary',
            name='official_receipt_credit_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='subledgersummary',
            name='official_receipt_debit_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
    ]
