# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-11-28 07:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorymaingroup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chartofaccount', '0038_auto_20180323_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMainGroupSubGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('C', 'Cancelled'), ('O', 'Posted'), ('P', 'Printed')], default='A', max_length=1)),
                ('enterdate', models.DateTimeField(auto_now_add=True)),
                ('modifydate', models.DateTimeField(auto_now_add=True)),
                ('isdeleted', models.IntegerField(default=0)),
                ('enterby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_maingroupsubgroup_enter', to=settings.AUTH_USER_MODEL)),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_mapped_maingroup', to='categorymaingroup.CategoryMainGroup')),
                ('modifyby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_maingroupsubgroup_modify', to=settings.AUTH_USER_MODEL)),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_mapped_subgroup', to='chartofaccount.Chartofaccount')),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'categorymainsubgroup',
                'permissions': (('view_categorymainsubgroup', 'Can view categorymainsubgroup'),),
            },
        ),
    ]
