# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-11-20 12:41
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debitcreditmemosubtype', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitcreditmemosubtype',
            name='applicationstatus',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='debitcreditmemosubtype',
            name='credit1chartofaccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit1chartofaccount_id', to='chartofaccount.Chartofaccount', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='debitcreditmemosubtype',
            name='credit2chartofaccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit2chartofaccount', to='chartofaccount.Chartofaccount', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='debitcreditmemosubtype',
            name='debit1chartofaccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debit1chartofaccount_id', to='chartofaccount.Chartofaccount', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='debitcreditmemosubtype',
            name='debit2chartofaccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debit2chartofaccount_id', to='chartofaccount.Chartofaccount', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='debitcreditmemosubtype',
            name='group',
            field=models.CharField(blank=True, choices=[('D', 'Debit'), ('C', 'Credit')], max_length=1, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='debitcreditmemosubtype',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 20, 20, 41, 18, 273000)),
        ),
    ]
