# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-11-20 12:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debitcreditmemosubtype', '0002_auto_20171120_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitcreditmemosubtype',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 20, 20, 44, 1, 14000)),
        ),
    ]
