# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-23 03:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcclasstype', '0002_auto_20180123_1124'),
        ('debitcreditmemosubtype', '0003_auto_20171120_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitcreditmemosubtype',
            name='dcclasstype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dcclasstype', to='dcclasstype.Dcclasstype'),
        ),
        migrations.AlterField(
            model_name='debitcreditmemosubtype',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 23, 11, 24, 31, 248000)),
        ),
    ]
