# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-11-07 10:06
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chartofaccount', '0024_auto_20171107_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arsubtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('C', 'Cancelled'), ('O', 'Posted'), ('P', 'Printed')], default='A', max_length=1)),
                ('enterdate', models.DateTimeField(auto_now_add=True)),
                ('modifydate', models.DateTimeField(default=datetime.datetime(2017, 11, 7, 18, 6, 9, 356000))),
                ('isdeleted', models.IntegerField(default=0)),
                ('arsubtypechartofaccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arsubtype_creditchartofaccount', to='chartofaccount.Chartofaccount')),
                ('enterby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='arsubtype_enter', to=settings.AUTH_USER_MODEL)),
                ('modifyby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='arsubtype_modify', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'arsubtype',
                'permissions': (('view_arsubtype', 'Can view arsubtype'),),
            },
        ),
    ]
