# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-06-19 06:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankbranchdisburse', '0002_auto_20170619_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankbranchdisburse',
            name='branch',
            field=models.CharField(max_length=75, unique=True),
        ),
        migrations.AlterField(
            model_name='bankbranchdisburse',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 19, 14, 29, 39, 685000)),
        ),
    ]
