# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-08-18 02:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccount', '0017_auto_20170818_1035'),
        ('ofsubtype', '0002_auto_20170718_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofsubtype',
            name='debitchartofaccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofsubtype_debitchartofaccount', to='chartofaccount.Chartofaccount'),
        ),
        migrations.AlterField(
            model_name='ofsubtype',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 18, 10, 35, 32, 117000)),
        ),
    ]
