# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-08-24 07:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofsubtype', '0006_auto_20170823_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ofsubtype',
            name='debitchartofaccount',
        ),
        migrations.AlterField(
            model_name='ofsubtype',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 24, 15, 6, 55, 857000)),
        ),
    ]
