# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-28 06:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofsubtype', '0008_auto_20170824_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofsubtype',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 28, 14, 10, 32, 155000)),
        ),
    ]
