# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-03-21 08:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofsubtype', '0009_auto_20180228_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofsubtype',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 16, 27, 40, 788000)),
        ),
    ]
