# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-20 13:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_auto_20170227_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 20, 13, 34, 28, 231000)),
        ),
    ]
