# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-23 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0008_auto_20170323_1109'),
        ('branch', '0005_auto_20170323_1027'),
    ]

    operations = [
    ]
