# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-27 15:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0017_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 27, 15, 39, 53, 227000)),
        ),
    ]
