# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-08-17 10:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccount', '0013_auto_20170817_1811'),
        ('branch', '0021_auto_20170807_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='bankaccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_bankaccount', to='bankaccount.Bankaccount'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 17, 18, 11, 13, 697000)),
        ),
    ]
