# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-24 02:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs_jvdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jvnum', models.CharField(blank=True, max_length=500, null=True)),
                ('jvdate', models.CharField(blank=True, max_length=500, null=True)),
                ('chartofaccount', models.CharField(blank=True, max_length=500, null=True)),
                ('department', models.CharField(blank=True, max_length=500, null=True)),
                ('charttype', models.CharField(blank=True, max_length=500, null=True)),
                ('amount', models.CharField(blank=True, max_length=500, null=True)),
                ('datecreated', models.CharField(blank=True, max_length=500, null=True)),
                ('datemodified', models.CharField(blank=True, max_length=500, null=True)),
                ('sortnum', models.CharField(blank=True, max_length=500, null=True)),
                ('batchkey', models.CharField(blank=True, max_length=255, null=True)),
                ('importstatus', models.CharField(choices=[('F', 'Failed'), ('S', 'Success'), ('P', 'Posted')], default='S', max_length=1)),
                ('importremarks', models.CharField(blank=True, max_length=255, null=True)),
                ('importdate', models.DateTimeField(auto_now_add=True)),
                ('importby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='logs_jvdetail_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'logs_jvdetail',
            },
        ),
        migrations.CreateModel(
            name='Logs_jvmain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jvnum', models.CharField(blank=True, max_length=500, null=True)),
                ('jvdate', models.CharField(blank=True, max_length=500, null=True)),
                ('particulars', models.CharField(blank=True, max_length=500, null=True)),
                ('remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, max_length=500, null=True)),
                ('datecreated', models.CharField(blank=True, max_length=500, null=True)),
                ('datemodified', models.CharField(blank=True, max_length=500, null=True)),
                ('batchkey', models.CharField(blank=True, max_length=255, null=True)),
                ('importstatus', models.CharField(choices=[('F', 'Failed'), ('S', 'Success'), ('P', 'Posted')], default='S', max_length=1)),
                ('importremarks', models.CharField(blank=True, max_length=255, null=True)),
                ('importdate', models.DateTimeField(auto_now_add=True)),
                ('importby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='logs_jvmain_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'logs_jvmain',
            },
        ),
    ]
