# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-24 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing_jv', '0002_temp_jvdetail_temp_jvmain'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp_jvdetail',
            name='importedjvnum',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='temp_jvdetail',
            name='item_counter',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='temp_jvmain',
            name='importedjvnum',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
