# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-01 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing_jv', '0003_auto_20180124_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs_jvdetail',
            name='bankaccount',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='logs_jvdetail',
            name='branch',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='logs_jvmain',
            name='year',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='logs_jvmain',
            name='year2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='temp_jvdetail',
            name='bankaccount',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='temp_jvdetail',
            name='branch',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
