# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-03 20:49
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryitem', '0007_auto_20170403_2049'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branch', '0010_auto_20170403_2049'),
        ('department', '0017_auto_20170403_2049'),
        ('purchaseorder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_counter', models.IntegerField()),
                ('invitem_code', models.CharField(max_length=25)),
                ('invitem_name', models.CharField(max_length=250)),
                ('invitem_unitofmeasure', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('unitcost', models.FloatField(default=0.0)),
                ('discountrate', models.IntegerField(blank=True, default=0, null=True)),
                ('remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('C', 'Cancelled'), ('O', 'Posted'), ('P', 'Printed')], default='A', max_length=1)),
                ('enterdate', models.DateTimeField(default=datetime.datetime(2017, 4, 3, 20, 49, 3, 742000))),
                ('modifydate', models.DateTimeField(default=datetime.datetime(2017, 4, 3, 20, 49, 3, 742000))),
                ('postdate', models.DateTimeField(blank=True, null=True)),
                ('isdeleted', models.IntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podetail_branch_id', to='branch.Branch')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='podetail_department_id', to='department.Department')),
                ('enterby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='podetail_enter', to=settings.AUTH_USER_MODEL)),
                ('invitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podetail_invitem_id', to='inventoryitem.Inventoryitem')),
                ('modifyby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='podetail_modify', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'podetail',
            },
        ),
        migrations.CreateModel(
            name='Podetailtemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_counter', models.IntegerField()),
                ('invitem_code', models.CharField(max_length=25)),
                ('invitem_name', models.CharField(max_length=250)),
                ('invitem_unitofmeasure', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('unitcost', models.FloatField(default=0.0)),
                ('discountrate', models.IntegerField(blank=True, default=0, null=True)),
                ('remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('C', 'Cancelled'), ('O', 'Posted'), ('P', 'Printed')], default='A', max_length=1)),
                ('enterdate', models.DateTimeField(default=datetime.datetime(2017, 4, 3, 20, 49, 3, 745000))),
                ('modifydate', models.DateTimeField(default=datetime.datetime(2017, 4, 3, 20, 49, 3, 745000))),
                ('postdate', models.DateTimeField(blank=True, null=True)),
                ('isdeleted', models.IntegerField(default=0)),
                ('secretkey', models.CharField(max_length=255)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podetailtemp_branch_id', to='branch.Branch')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='podetailtemp_department_id', to='department.Department')),
                ('enterby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='podetailtemp_enter', to=settings.AUTH_USER_MODEL)),
                ('invitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podetailtemp_invitem_id', to='inventoryitem.Inventoryitem')),
                ('modifyby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='podetailtemp_modify', to=settings.AUTH_USER_MODEL)),
                ('podetail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='podetailtemp_podetail_id', to='purchaseorder.Podetail')),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'podetailtemp',
            },
        ),
        migrations.AlterField(
            model_name='pomain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 3, 20, 49, 3, 740000)),
        ),
        migrations.AddField(
            model_name='podetailtemp',
            name='pomain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='podetailtemp_pomain_id', to='purchaseorder.Pomain'),
        ),
        migrations.AddField(
            model_name='podetailtemp',
            name='postby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='podetailtemp_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='podetail',
            name='pomain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='podetail_pomain_id', to='purchaseorder.Pomain'),
        ),
        migrations.AddField(
            model_name='podetail',
            name='postby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='podetail_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
