# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-03 22:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseorder', '0002_auto_20170403_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pomain',
            name='actualapprover',
        ),
        migrations.RemoveField(
            model_name='pomain',
            name='approverresponse',
        ),
        migrations.RemoveField(
            model_name='pomain',
            name='designatedapprover',
        ),
        migrations.RemoveField(
            model_name='pomain',
            name='responsedate',
        ),
        migrations.AlterField(
            model_name='podetail',
            name='enterdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 3, 22, 33, 30, 420000)),
        ),
        migrations.AlterField(
            model_name='podetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 3, 22, 33, 30, 421000)),
        ),
        migrations.AlterField(
            model_name='podetailtemp',
            name='enterdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 3, 22, 33, 30, 424000)),
        ),
        migrations.AlterField(
            model_name='podetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 3, 22, 33, 30, 424000)),
        ),
        migrations.AlterField(
            model_name='pomain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 3, 22, 33, 30, 418000)),
        ),
        migrations.AlterField(
            model_name='pomain',
            name='postatus',
            field=models.CharField(choices=[('F', 'For Approval'), ('A', 'Approved'), ('D', 'Disapproved')], default='A', max_length=1),
        ),
    ]
