# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-04 17:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseorder', '0003_auto_20170403_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podetail',
            name='branch',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='podetail_branch_id', to='branch.Branch'),
        ),
        migrations.AlterField(
            model_name='podetail',
            name='enterdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 4, 17, 32, 46, 238000)),
        ),
        migrations.AlterField(
            model_name='podetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 4, 17, 32, 46, 239000)),
        ),
        migrations.AlterField(
            model_name='podetailtemp',
            name='branch',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='podetailtemp_branch_id', to='branch.Branch'),
        ),
        migrations.AlterField(
            model_name='podetailtemp',
            name='enterdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 4, 17, 32, 46, 243000)),
        ),
        migrations.AlterField(
            model_name='podetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 4, 17, 32, 46, 243000)),
        ),
        migrations.AlterField(
            model_name='pomain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 4, 17, 32, 46, 236000)),
        ),
    ]
