# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-20 13:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0007_auto_20170420_1342'),
        ('purchaseorder', '0007_auto_20170418_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='podetail',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='podetail_currency', to='currency.Currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='podetailtemp',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='podetailtemp_currency', to='currency.Currency'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='podetail',
            name='enterdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 20, 13, 42, 5, 32000)),
        ),
        migrations.AlterField(
            model_name='podetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 20, 13, 42, 5, 33000)),
        ),
        migrations.AlterField(
            model_name='podetailtemp',
            name='enterdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 20, 13, 42, 5, 35000)),
        ),
        migrations.AlterField(
            model_name='podetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 20, 13, 42, 5, 35000)),
        ),
        migrations.AlterField(
            model_name='pomain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 20, 13, 42, 5, 29000)),
        ),
    ]
