# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-21 13:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unitofmeasure', '0005_auto_20170421_1351'),
        ('purchaseorder', '0008_auto_20170420_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='podetail',
            name='unitofmeasure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='podetail_unitofmeasure', to='unitofmeasure.Unitofmeasure'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='podetailtemp',
            name='unitofmeasure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='podetailtemp_unitofmeasure', to='unitofmeasure.Unitofmeasure'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='podetail',
            name='enterdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 21, 13, 51, 25, 851000)),
        ),
        migrations.AlterField(
            model_name='podetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 21, 13, 51, 25, 852000)),
        ),
        migrations.AlterField(
            model_name='podetailtemp',
            name='enterdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 21, 13, 51, 25, 854000)),
        ),
        migrations.AlterField(
            model_name='podetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 21, 13, 51, 25, 855000)),
        ),
        migrations.AlterField(
            model_name='pomain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 21, 13, 51, 25, 849000)),
        ),
    ]
