# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-05-16 14:10
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wtax', '0004_auto_20170516_1410'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('currency', '0010_auto_20170516_1410'),
        ('inputvattype', '0003_auto_20170516_1410'),
        ('ataxcode', '0006_auto_20170516_1410'),
        ('employee', '0005_auto_20170516_1410'),
        ('purchaseorder', '0010_auto_20170502_0930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pomain',
            options={'ordering': ['-pk'], 'permissions': (('view_purchaseorder', 'Can view purchaseorder'),)},
        ),
        migrations.RemoveField(
            model_name='pomain',
            name='ataxcode',
        ),
        migrations.AddField(
            model_name='podetail',
            name='assetnum',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='podetail',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='podetail_employee_id', to='employee.Employee'),
        ),
        migrations.AddField(
            model_name='podetail',
            name='employee_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='podetail',
            name='employee_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='podetail',
            name='expirationdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='podetail',
            name='serialnum',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='podetailtemp',
            name='assetnum',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='podetailtemp',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='podetailtemp_employee_id', to='employee.Employee'),
        ),
        migrations.AddField(
            model_name='podetailtemp',
            name='employee_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='podetailtemp',
            name='employee_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='podetailtemp',
            name='expirationdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='podetailtemp',
            name='serialnum',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pomain',
            name='actualapprover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pomain_actual_approver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pomain',
            name='approverremarks',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pomain',
            name='approverresponse',
            field=models.CharField(blank=True, choices=[('A', 'Approved'), ('D', 'Disapproved')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='pomain',
            name='atc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pomain_atc_id', to='ataxcode.Ataxcode', validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pomain',
            name='atcrate',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='pomain',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pomain_currency_id', to='currency.Currency'),
        ),
        migrations.AddField(
            model_name='pomain',
            name='deferredvat',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='pomain',
            name='deliverydate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pomain',
            name='deliverystatus',
            field=models.CharField(blank=True, choices=[('O', 'Ordered'), ('P', 'Partial Delivery'), ('C', 'Complete'), ('S', 'Stop')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='pomain',
            name='designatedapprover',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='pomain_designated_approver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pomain',
            name='fxrate',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='pomain',
            name='inputvattype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pomain_inputvattype_id', to='inputvattype.Inputvattype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pomain',
            name='print_ctr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pomain',
            name='responsedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pomain',
            name='totalamount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='pomain',
            name='totalquantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pomain',
            name='wtax',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pomain_wtax_id', to='wtax.Wtax', validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pomain',
            name='wtaxamount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='pomain',
            name='wtaxrate',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='podata',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 16, 14, 10, 20, 826000)),
        ),
        migrations.AlterField(
            model_name='podetail',
            name='enterdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 16, 14, 10, 20, 820000)),
        ),
        migrations.AlterField(
            model_name='podetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 16, 14, 10, 20, 820000)),
        ),
        migrations.AlterField(
            model_name='podetailtemp',
            name='enterdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 16, 14, 10, 20, 823000)),
        ),
        migrations.AlterField(
            model_name='podetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 16, 14, 10, 20, 823000)),
        ),
        migrations.AlterField(
            model_name='pomain',
            name='creditterm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pomain_creditterm_id', to='creditterm.Creditterm'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pomain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 16, 14, 10, 20, 816000)),
        ),
        migrations.AlterField(
            model_name='pomain',
            name='postatus',
            field=models.CharField(choices=[('F', 'For Approval'), ('A', 'Approved'), ('D', 'Disapproved')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='pomain',
            name='vat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pomain_vat_id', to='vat.Vat', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='pomain',
            name='vatrate',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
