# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-05-17 10:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseorder', '0011_auto_20170516_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podata',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 17, 10, 39, 56, 845000)),
        ),
        migrations.AlterField(
            model_name='podetail',
            name='enterdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 17, 10, 39, 56, 839000)),
        ),
        migrations.AlterField(
            model_name='podetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 17, 10, 39, 56, 839000)),
        ),
        migrations.AlterField(
            model_name='podetailtemp',
            name='enterdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 17, 10, 39, 56, 842000)),
        ),
        migrations.AlterField(
            model_name='podetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 17, 10, 39, 56, 842000)),
        ),
        migrations.AlterField(
            model_name='pomain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 17, 10, 39, 56, 835000)),
        ),
        migrations.AlterField(
            model_name='pomain',
            name='potype',
            field=models.CharField(choices=[('REG', 'Regular')], default='REG', max_length=10),
        ),
    ]
