# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-05-19 11:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseorder', '0013_auto_20170517_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='podetail',
            name='department_code',
            field=models.CharField(default='TEST', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='podetail',
            name='department_name',
            field=models.CharField(default='TEST', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='podetailtemp',
            name='department_code',
            field=models.CharField(default='TEST', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='podetailtemp',
            name='department_name',
            field=models.CharField(default='TEST', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='podata',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 19, 11, 35, 56, 799000)),
        ),
        migrations.AlterField(
            model_name='podetail',
            name='enterdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 19, 11, 35, 56, 793000)),
        ),
        migrations.AlterField(
            model_name='podetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 19, 11, 35, 56, 793000)),
        ),
        migrations.AlterField(
            model_name='podetailtemp',
            name='enterdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 19, 11, 35, 56, 797000)),
        ),
        migrations.AlterField(
            model_name='podetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 19, 11, 35, 56, 797000)),
        ),
        migrations.AlterField(
            model_name='pomain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 19, 11, 35, 56, 789000)),
        ),
    ]
