# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-05-26 10:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchaserequisitionform', '0043_auto_20170526_1024'),
        ('purchaseorder', '0016_auto_20170524_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prfpotransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poquantity', models.IntegerField()),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('C', 'Cancelled'), ('O', 'Posted'), ('P', 'Printed')], default='A', max_length=1)),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'prfpotransaction',
            },
        ),
        migrations.AlterField(
            model_name='podata',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 26, 10, 24, 8, 722000)),
        ),
        migrations.AlterField(
            model_name='podetail',
            name='enterdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 26, 10, 24, 8, 716000)),
        ),
        migrations.AlterField(
            model_name='podetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 26, 10, 24, 8, 716000)),
        ),
        migrations.AlterField(
            model_name='podetailtemp',
            name='enterdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 26, 10, 24, 8, 720000)),
        ),
        migrations.AlterField(
            model_name='podetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 26, 10, 24, 8, 720000)),
        ),
        migrations.AlterField(
            model_name='pomain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 26, 10, 24, 8, 710000)),
        ),
        migrations.AddField(
            model_name='prfpotransaction',
            name='podetail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podetail_prfpotransaction', to='purchaseorder.Podetail'),
        ),
        migrations.AddField(
            model_name='prfpotransaction',
            name='pomain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pomain_prfpotransaction', to='purchaseorder.Pomain'),
        ),
        migrations.AddField(
            model_name='prfpotransaction',
            name='prfdetail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prfdetail_prfpotransaction', to='purchaserequisitionform.Prfdetail'),
        ),
        migrations.AddField(
            model_name='prfpotransaction',
            name='prfmain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prfmain_prfpotransaction', to='purchaserequisitionform.Prfmain'),
        ),
    ]
