# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-05-26 16:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchaserequisitionform', '0045_auto_20170526_1629'),
        ('purchaseorder', '0018_auto_20170526_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='podetail',
            name='prfdetail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prfdetail_podetail', to='purchaserequisitionform.Prfdetail'),
        ),
        migrations.AddField(
            model_name='podetail',
            name='prfmain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prfmain_podetail', to='purchaserequisitionform.Prfmain'),
        ),
        migrations.AddField(
            model_name='podetailtemp',
            name='prfdetail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prfdetail_podetailtemp', to='purchaserequisitionform.Prfdetail'),
        ),
        migrations.AddField(
            model_name='podetailtemp',
            name='prfmain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prfmain_podetailtemp', to='purchaserequisitionform.Prfmain'),
        ),
        migrations.AlterField(
            model_name='podata',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 26, 16, 29, 22, 337000)),
        ),
        migrations.AlterField(
            model_name='podetail',
            name='enterdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 26, 16, 29, 22, 329000)),
        ),
        migrations.AlterField(
            model_name='podetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 26, 16, 29, 22, 329000)),
        ),
        migrations.AlterField(
            model_name='podetailtemp',
            name='enterdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 26, 16, 29, 22, 333000)),
        ),
        migrations.AlterField(
            model_name='podetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 26, 16, 29, 22, 333000)),
        ),
        migrations.AlterField(
            model_name='pomain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 26, 16, 29, 22, 324000)),
        ),
    ]
