# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-06-27 14:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseorder', '0020_auto_20170605_1447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pomain',
            options={'ordering': ['-pk'], 'permissions': (('view_purchaseorder', 'Can view purchaseorder'), ('approve_assignedpo', 'Can approve assigned po'), ('approve_allpo', 'Can approve all po'))},
        ),
        migrations.AlterField(
            model_name='podata',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 27, 14, 16, 57, 443000)),
        ),
        migrations.AlterField(
            model_name='podetail',
            name='enterdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 27, 14, 16, 57, 436000)),
        ),
        migrations.AlterField(
            model_name='podetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 27, 14, 16, 57, 436000)),
        ),
        migrations.AlterField(
            model_name='podetailtemp',
            name='enterdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 27, 14, 16, 57, 440000)),
        ),
        migrations.AlterField(
            model_name='podetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 27, 14, 16, 57, 440000)),
        ),
        migrations.AlterField(
            model_name='pomain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 27, 14, 16, 57, 430000)),
        ),
    ]
