# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-12-19 07:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseorder', '0021_auto_20170627_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='pomain',
            name='apvamount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='pomain',
            name='isfullyapv',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='podata',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 19, 15, 3, 34, 200000)),
        ),
        migrations.AlterField(
            model_name='podetail',
            name='enterdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 19, 15, 3, 34, 190000)),
        ),
        migrations.AlterField(
            model_name='podetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 19, 15, 3, 34, 190000)),
        ),
        migrations.AlterField(
            model_name='podetailtemp',
            name='enterdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 19, 15, 3, 34, 197000)),
        ),
        migrations.AlterField(
            model_name='podetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 19, 15, 3, 34, 197000)),
        ),
        migrations.AlterField(
            model_name='pomain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 19, 15, 3, 34, 185000)),
        ),
    ]
