# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-08 08:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseorder', '0023_auto_20171220_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='podetail',
            name='apvremainingamount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='podetail',
            name='apvtotalamount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='podetail',
            name='isfullyapv',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='podetailtemp',
            name='apvremainingamount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='podetailtemp',
            name='apvtotalamount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='podetailtemp',
            name='isfullyapv',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pomain',
            name='totalremainingamount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='podata',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 8, 16, 21, 33, 18000)),
        ),
        migrations.AlterField(
            model_name='podetail',
            name='enterdate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 8, 16, 21, 33, 12000)),
        ),
        migrations.AlterField(
            model_name='podetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 8, 16, 21, 33, 12000)),
        ),
        migrations.AlterField(
            model_name='podetailtemp',
            name='enterdate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 8, 16, 21, 33, 15000)),
        ),
        migrations.AlterField(
            model_name='podetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 8, 16, 21, 33, 15000)),
        ),
        migrations.AlterField(
            model_name='pomain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 8, 16, 21, 33, 9000)),
        ),
    ]
