# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-09 02:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseorder', '0026_auto_20180209_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podata',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 9, 10, 34, 41, 484000)),
        ),
        migrations.AlterField(
            model_name='podetail',
            name='enterdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='podetail',
            name='modifydate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='podetailtemp',
            name='enterdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='podetailtemp',
            name='modifydate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pomain',
            name='modifydate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
