# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-09 02:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inputvattype', '0010_auto_20180209_1035'),
        ('purchaseorder', '0027_auto_20180209_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='podetailtemp',
            name='inputvattype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='podetailtemp_inputvattype', to='inputvattype.Inputvattype'),
        ),
        migrations.AlterField(
            model_name='podata',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 9, 10, 35, 26, 5000)),
        ),
    ]
