# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-03-12 07:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseorder', '0028_auto_20180209_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podata',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 12, 15, 22, 55, 656000)),
        ),
        migrations.AlterField(
            model_name='pomain',
            name='potype',
            field=models.CharField(choices=[('REG', 'Regular'), ('EXD', 'Exdeal')], default='REG', max_length=10),
        ),
    ]
