# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-04-24 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subledger', '0002_logs_subledger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs_subledger',
            name='supplier',
        ),
        migrations.AlterField(
            model_name='logs_subledger',
            name='document_num',
            field=models.CharField(max_length=10),
        ),
    ]
