# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-04-24 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subledger', '0004_auto_20180424_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs_subledger',
            name='atcrate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='subledger',
            name='atcrate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
