# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-04-24 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subledger', '0005_auto_20180424_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs_subledger',
            name='atcrate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='logs_subledger',
            name='document_supplieratcrate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subledger',
            name='atcrate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subledger',
            name='document_supplieratcrate',
            field=models.IntegerField(default=0),
        ),
    ]
