# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-04-24 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subledger', '0006_auto_20180424_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs_subledger',
            name='atcrate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='logs_subledger',
            name='document_customervatrate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='logs_subledger',
            name='document_supplieratcrate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='logs_subledger',
            name='document_suppliervatrate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='logs_subledger',
            name='vatrate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='subledger',
            name='atcrate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='subledger',
            name='document_supplieratcrate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='subledger',
            name='document_suppliervatrate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='subledger',
            name='vatrate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
