# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-04-24 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subledger', '0007_auto_20180424_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs_subledger',
            name='document_customerwtaxrate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='logs_subledger',
            name='wtaxrate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='subledger',
            name='document_customerwtaxrate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='subledger',
            name='wtaxrate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
