# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-04-26 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subledger', '0009_auto_20180424_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs_subledger',
            name='particulars',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='subledger',
            name='particulars',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
