# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-04-26 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subledger', '0010_auto_20180426_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subledger',
            name='document_num',
            field=models.CharField(max_length=10),
        ),
    ]
