# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-05-15 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subledger', '0013_logs_subledger_breakdownsource_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs_subledger',
            name='particulars',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subledger',
            name='particulars',
            field=models.TextField(blank=True, null=True),
        ),
    ]
