# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-05-15 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subledger', '0015_auto_20180515_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs_subledger',
            name='particulars',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subledger',
            name='particulars',
            field=models.TextField(blank=True, null=True),
        ),
    ]
