# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-23 03:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcclasstype', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcclasstype',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 23, 11, 24, 31, 515000)),
        ),
    ]
