# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-09-27 08:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apsubtype', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apsubtype',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 27, 16, 10, 39, 505000)),
        ),
    ]
