# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-11-21 07:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paytype', '0005_auto_20171107_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paytype',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 21, 15, 30, 6, 422000)),
        ),
    ]
