# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-11-20 01:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outputvattype', '0003_auto_20171120_0919'),
        ('debitcreditmemo', '0005_auto_20171120_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcmain',
            name='outputvattype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dcmain_outvattype_id', to='outputvattype.Outputvattype'),
        ),
        migrations.AlterField(
            model_name='dcdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 20, 9, 19, 36, 512000)),
        ),
        migrations.AlterField(
            model_name='dcdetail',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 20, 9, 19, 36, 512000)),
        ),
        migrations.AlterField(
            model_name='dcdetailbreakdown',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 20, 9, 19, 36, 519000)),
        ),
        migrations.AlterField(
            model_name='dcdetailbreakdown',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 20, 9, 19, 36, 519000)),
        ),
        migrations.AlterField(
            model_name='dcdetailbreakdowntemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 20, 9, 19, 36, 530000)),
        ),
        migrations.AlterField(
            model_name='dcdetailbreakdowntemp',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 20, 9, 19, 36, 530000)),
        ),
        migrations.AlterField(
            model_name='dcdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 20, 9, 19, 36, 525000)),
        ),
        migrations.AlterField(
            model_name='dcdetailtemp',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 20, 9, 19, 36, 525000)),
        ),
        migrations.AlterField(
            model_name='dcmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 20, 9, 19, 36, 506000)),
        ),
    ]
