# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-23 06:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0033_auto_20180123_1405'),
        ('currency', '0017_auto_20180123_1405'),
        ('dcclasstype', '0003_auto_20180123_1405'),
        ('department', '0032_auto_20180123_1405'),
        ('bankaccount', '0018_auto_20180123_1405'),
        ('inventoryitem', '0012_auto_20180123_1405'),
        ('employee', '0022_auto_20180123_1405'),
        ('debitcreditmemo', '0011_auto_20171122_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dcmain',
            old_name='customer_code',
            new_name='payee_code',
        ),
        migrations.RenameField(
            model_name='dcmain',
            old_name='customer_name',
            new_name='payee_name',
        ),
        migrations.RemoveField(
            model_name='dcmain',
            name='dcartype',
        ),
        migrations.AddField(
            model_name='dcdetail',
            name='refdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dcdetail',
            name='refnum',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dcdetail',
            name='reftype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dcdetailtemp',
            name='refdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dcdetailtemp',
            name='refnum',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dcdetailtemp',
            name='reftype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dcmain',
            name='bankaccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dcmain_bankaccount_id', to='bankaccount.Bankaccount'),
        ),
        migrations.AddField(
            model_name='dcmain',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dcmain_currency_id', to='currency.Currency'),
        ),
        migrations.AddField(
            model_name='dcmain',
            name='dcclasstype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dcmain_dcclasstype_id', to='dcclasstype.Dcclasstype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dcmain',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dcmain_department_id', to='department.Department'),
        ),
        migrations.AddField(
            model_name='dcmain',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dcmain_employee_id', to='employee.Employee'),
        ),
        migrations.AddField(
            model_name='dcmain',
            name='fxrate',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=18),
        ),
        migrations.AddField(
            model_name='dcmain',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dcmain_inventoryitem_id', to='inventoryitem.Inventoryitem'),
        ),
        migrations.AddField(
            model_name='dcmain',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dcmain_supplier_id', to='supplier.Supplier'),
        ),
        migrations.AlterField(
            model_name='dcdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 23, 14, 5, 9, 308000)),
        ),
        migrations.AlterField(
            model_name='dcdetail',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 23, 14, 5, 9, 308000)),
        ),
        migrations.AlterField(
            model_name='dcdetailbreakdown',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 23, 14, 5, 9, 313000)),
        ),
        migrations.AlterField(
            model_name='dcdetailbreakdown',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 23, 14, 5, 9, 313000)),
        ),
        migrations.AlterField(
            model_name='dcdetailbreakdowntemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 23, 14, 5, 9, 319000)),
        ),
        migrations.AlterField(
            model_name='dcdetailbreakdowntemp',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 23, 14, 5, 9, 319000)),
        ),
        migrations.AlterField(
            model_name='dcdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 23, 14, 5, 9, 317000)),
        ),
        migrations.AlterField(
            model_name='dcdetailtemp',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 23, 14, 5, 9, 317000)),
        ),
        migrations.AlterField(
            model_name='dcmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 23, 14, 5, 9, 304000)),
        ),
    ]
