# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-23 07:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debitcreditmemo', '0013_auto_20180223_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 23, 15, 27, 32, 169000)),
        ),
        migrations.AlterField(
            model_name='dcdetail',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 23, 15, 27, 32, 169000)),
        ),
        migrations.AlterField(
            model_name='dcdetailbreakdown',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 23, 15, 27, 32, 169000)),
        ),
        migrations.AlterField(
            model_name='dcdetailbreakdown',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 23, 15, 27, 32, 169000)),
        ),
        migrations.AlterField(
            model_name='dcdetailbreakdowntemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 23, 15, 27, 32, 185000)),
        ),
        migrations.AlterField(
            model_name='dcdetailbreakdowntemp',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 23, 15, 27, 32, 185000)),
        ),
        migrations.AlterField(
            model_name='dcdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 23, 15, 27, 32, 185000)),
        ),
        migrations.AlterField(
            model_name='dcdetailtemp',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 23, 15, 27, 32, 185000)),
        ),
        migrations.AlterField(
            model_name='dcmain',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dcmain_currency_id', to='currency.Currency'),
        ),
        migrations.AlterField(
            model_name='dcmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 23, 15, 27, 32, 169000)),
        ),
    ]
