# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-03-21 08:27
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('debitcreditmemo', '0015_auto_20180223_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcdetail',
            name='closeby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dcdetail_close', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dcdetail',
            name='closedate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 16, 27, 40, 933000)),
        ),
        migrations.AddField(
            model_name='dcdetailbreakdown',
            name='closeby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dcdetailbreakdown_close', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dcdetailbreakdown',
            name='closedate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 16, 27, 40, 936000)),
        ),
        migrations.AddField(
            model_name='dcdetailbreakdowntemp',
            name='closeby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dcdetailbreakdowntemp_close', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dcdetailbreakdowntemp',
            name='closedate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 16, 27, 40, 940000)),
        ),
        migrations.AddField(
            model_name='dcdetailtemp',
            name='closeby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dcdetailtemp_close', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dcdetailtemp',
            name='closedate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 16, 27, 40, 938000)),
        ),
        migrations.AddField(
            model_name='dcmain',
            name='closeby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dcmain_close', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dcmain',
            name='closedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dcdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 16, 27, 40, 933000)),
        ),
        migrations.AlterField(
            model_name='dcdetail',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 16, 27, 40, 933000)),
        ),
        migrations.AlterField(
            model_name='dcdetailbreakdown',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 16, 27, 40, 936000)),
        ),
        migrations.AlterField(
            model_name='dcdetailbreakdown',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 16, 27, 40, 936000)),
        ),
        migrations.AlterField(
            model_name='dcdetailbreakdowntemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 16, 27, 40, 940000)),
        ),
        migrations.AlterField(
            model_name='dcdetailbreakdowntemp',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 16, 27, 40, 940000)),
        ),
        migrations.AlterField(
            model_name='dcdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 16, 27, 40, 938000)),
        ),
        migrations.AlterField(
            model_name='dcdetailtemp',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 16, 27, 40, 938000)),
        ),
        migrations.AlterField(
            model_name='dcmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 16, 27, 40, 930000)),
        ),
    ]
