# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-11-07 09:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulationproduct', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circulationproduct',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 7, 17, 12, 0, 714000)),
        ),
    ]
