# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-09-13 09:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvsubtype', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvsubtype',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 13, 17, 29, 5, 996000)),
        ),
    ]
