# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-10 13:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_auto_20170202_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 10, 13, 32, 38, 664000)),
        ),
    ]
