# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-19 15:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_auto_20170410_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 19, 15, 25, 13, 322000)),
        ),
    ]
