# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-20 13:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0006_auto_20170420_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 20, 13, 42, 4, 892000)),
        ),
    ]
