# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-05-04 18:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0008_auto_20170504_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 4, 18, 5, 46, 686000)),
        ),
    ]
