# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-08-18 08:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0014_auto_20170726_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 18, 16, 40, 24, 790000)),
        ),
    ]
