# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-10-10 12:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0015_auto_20170818_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 10, 20, 5, 37, 495000)),
        ),
    ]
