# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-05-04 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactionposting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs_posted',
            name='doctype',
            field=models.CharField(default='ap', max_length=2),
            preserve_default=False,
        ),
    ]
