# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-12-06 06:55
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('currency', '0019_auto_20180322_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fxrate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('fxrate', models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=18, null=True)),
                ('fxrateselling', models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=18, null=True)),
                ('remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('C', 'Cancelled'), ('O', 'Posted'), ('P', 'Printed')], default='A', max_length=1)),
                ('enterdate', models.DateTimeField(auto_now_add=True)),
                ('modifydate', models.DateTimeField(auto_now_add=True)),
                ('isdeleted', models.IntegerField(default=0)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fxrate_currency_id', to='currency.Currency', validators=[django.core.validators.MinValueValidator(1)])),
                ('enterby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fxrate_enter', to=settings.AUTH_USER_MODEL)),
                ('modifyby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fxrate_modify', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'fxrate',
                'permissions': (('view_fxrate', 'Can view fxrate'),),
            },
        ),
    ]
