# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-10 07:00
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productgroup', '0003_auto_20180110_1500'),
        ('locationcategory', '0002_auto_20180110_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productgroupcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('C', 'Cancelled'), ('O', 'Posted'), ('P', 'Printed')], default='A', max_length=1)),
                ('enterdate', models.DateTimeField(auto_now_add=True)),
                ('modifydate', models.DateTimeField(default=datetime.datetime(2018, 1, 10, 15, 0, 11, 825000))),
                ('isdeleted', models.IntegerField(default=0)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productgroupcategory_category', to='locationcategory.Locationcategory')),
                ('enterby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productgroupcategory_enter', to=settings.AUTH_USER_MODEL)),
                ('modifyby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productgroupcategory_modify', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productgroupcategory_product', to='productgroup.Productgroup')),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'productgroupcategory',
                'permissions': (('view_productgroupcategory', 'Can view productgroupcategory'),),
            },
        ),
    ]
