# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-10 07:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccount', '0029_auto_20180110_1515'),
        ('productgroupcategory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroupcategory',
            name='chartofaccount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productgroupcategory_chartofaccount', to='chartofaccount.Chartofaccount'),
        ),
        migrations.AlterField(
            model_name='productgroupcategory',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 10, 15, 15, 25, 806000)),
        ),
    ]
