# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-10 07:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productgroupcategory', '0002_auto_20180110_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgroupcategory',
            name='product',
        ),
        migrations.AlterField(
            model_name='productgroupcategory',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 10, 15, 29, 15, 461000)),
        ),
    ]
