# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-10 07:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productgroup', '0004_auto_20180110_1530'),
        ('productgroupcategory', '0003_auto_20180110_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroupcategory',
            name='productgroup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productgroupcategory_product', to='productgroup.Productgroup'),
        ),
        migrations.AlterField(
            model_name='productgroupcategory',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 10, 15, 30, 5, 550000)),
        ),
    ]
