# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-10 15:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtax', '0004_auto_20170516_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wtax',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 10, 15, 55, 30, 687000)),
        ),
    ]
