# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-18 10:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oftype', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oftype',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 18, 10, 19, 21, 588000)),
        ),
    ]
