# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-08-18 08:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccount', '0018_auto_20170818_1614'),
        ('oftype', '0005_auto_20170818_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='oftype',
            name='creditchartofaccount',
            field=models.ForeignKey(default=30, on_delete=django.db.models.deletion.CASCADE, related_name='oftype_creditchartofaccount', to='chartofaccount.Chartofaccount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oftype',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 18, 16, 14, 24, 663000)),
        ),
    ]
