# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-08-18 08:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oftype', '0006_auto_20170818_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oftype',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 18, 16, 40, 24, 842000)),
        ),
    ]
