# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-28 10:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccount', '0006_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 28, 10, 48, 48, 299000)),
        ),
    ]
