# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-08-17 10:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccount', '0011_auto_20170807_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 17, 18, 5, 8, 97000)),
        ),
    ]
