# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-11-08 01:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccount', '0016_auto_20171107_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 9, 24, 42, 45000)),
        ),
    ]
