# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-09-19 02:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replenish_rfv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reprfvdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 19, 10, 53, 35, 797000)),
        ),
        migrations.AlterField(
            model_name='reprfvmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 19, 10, 53, 35, 796000)),
        ),
    ]
