# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-23 06:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replenish_rfv', '0002_auto_20170919_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='reprfvmain',
            name='finalapproverremarks',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='reprfvmain',
            name='finalapproverresponse',
            field=models.CharField(blank=True, choices=[('A', 'Approved'), ('D', 'Disapproved')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='reprfvmain',
            name='finalapproverresponsedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reprfvmain',
            name='initialapproverremarks',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='reprfvmain',
            name='initialapproverresponse',
            field=models.CharField(blank=True, choices=[('A', 'Approved'), ('D', 'Disapproved')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='reprfvmain',
            name='initialapproverresponsedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reprfvdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 23, 14, 25, 25, 574000)),
        ),
        migrations.AlterField(
            model_name='reprfvmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 23, 14, 25, 25, 573000)),
        ),
    ]
