# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-23 07:55
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('replenish_rfv', '0003_auto_20180223_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='reprfvmain',
            name='finalapprover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfv_finalapprover', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reprfvmain',
            name='initialapprover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfv_initialapprover', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reprfvdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 23, 15, 55, 1, 282000)),
        ),
        migrations.AlterField(
            model_name='reprfvmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 23, 15, 55, 1, 281000)),
        ),
    ]
