# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-03-21 04:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chartofaccountmaingroup', '0001_initial'),
        ('chartofaccountsubgroup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainGroupSubgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('C', 'Cancelled'), ('O', 'Posted'), ('P', 'Printed')], default='A', max_length=1)),
                ('enterdate', models.DateTimeField(auto_now_add=True)),
                ('modifydate', models.DateTimeField(auto_now_add=True)),
                ('isdeleted', models.IntegerField(default=0)),
                ('enterby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='maingroupsubgroup_enter', to=settings.AUTH_USER_MODEL)),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapped_maingroup', to='chartofaccountmaingroup.ChartofAccountMainGroup')),
                ('modifyby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='maingroupsubgroup_modify', to=settings.AUTH_USER_MODEL)),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapped_subgroup', to='chartofaccountsubgroup.ChartofAccountSubGroup')),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'chartofaccountmainsubgroup',
                'permissions': (('view_chartofaccountmainsubgroup', 'Can view chartofaccountmainsubgroup'),),
            },
        ),
    ]
