# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-09 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing_transaction', '0002_poapvtransaction_podetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poapvdetailtemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_counter', models.IntegerField()),
                ('sort_num', models.IntegerField()),
                ('secretkey', models.CharField(blank=True, max_length=255, null=True)),
                ('apmain', models.CharField(blank=True, max_length=10, null=True)),
                ('ap_num', models.CharField(max_length=10)),
                ('ap_date', models.DateTimeField(blank=True, null=True)),
                ('chartofaccount', models.IntegerField(blank=True, null=True)),
                ('bankaccount', models.IntegerField(blank=True, null=True)),
                ('department', models.IntegerField(blank=True, null=True)),
                ('employee', models.IntegerField(blank=True, null=True)),
                ('supplier', models.IntegerField(blank=True, null=True)),
                ('customer', models.IntegerField(blank=True, null=True)),
                ('unit', models.IntegerField(blank=True, null=True)),
                ('branch', models.IntegerField(blank=True, null=True)),
                ('product', models.IntegerField(blank=True, null=True)),
                ('inputvat', models.IntegerField(blank=True, null=True)),
                ('outputvat', models.IntegerField(blank=True, null=True)),
                ('vat', models.IntegerField(blank=True, null=True)),
                ('wtax', models.IntegerField(blank=True, null=True)),
                ('ataxcode', models.IntegerField(blank=True, null=True)),
                ('debitamount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('creditamount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('balancecode', models.CharField(blank=True, max_length=1, null=True)),
                ('isdeleted', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'poapvdetailtemp',
            },
        ),
    ]
