# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-03-07 03:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkvoucher', '0021_auto_20180307_1128'),
        ('processing_transaction', '0003_poapvdetailtemp'),
    ]

    operations = [
        migrations.AddField(
            model_name='poapvtransaction',
            name='cvmain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cvmain_poapvtransaction', to='checkvoucher.Cvmain'),
        ),
        migrations.AlterField(
            model_name='poapvtransaction',
            name='apmain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apmain_poapvtransaction', to='accountspayable.Apmain'),
        ),
    ]
