# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-03-07 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountspayable', '0027_auto_20180307_1757'),
        ('processing_transaction', '0004_auto_20180307_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='apvcvtransaction',
            name='old_apmain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_apmain_apvcvtransaction', to='accountspayable.Apmain'),
        ),
        migrations.AlterField(
            model_name='apvcvtransaction',
            name='cvmain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cvmain_apvcvtransaction', to='checkvoucher.Cvmain'),
        ),
    ]
