# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-11-03 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temp_ormain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orno', models.CharField(blank=True, max_length=500, null=True)),
                ('ordate', models.CharField(blank=True, max_length=500, null=True)),
                ('prno', models.CharField(blank=True, max_length=500, null=True)),
                ('accounttype', models.CharField(blank=True, max_length=500, null=True)),
                ('collector', models.CharField(blank=True, max_length=500, null=True)),
                ('payeetype', models.CharField(blank=True, max_length=500, null=True)),
                ('adtype', models.CharField(blank=True, max_length=500, null=True)),
                ('agencycode', models.CharField(blank=True, max_length=500, null=True)),
                ('clientcode', models.CharField(blank=True, max_length=500, null=True)),
                ('payeename', models.CharField(blank=True, max_length=500, null=True)),
                ('amount', models.CharField(blank=True, max_length=500, null=True)),
                ('amountinwords', models.CharField(blank=True, max_length=500, null=True)),
                ('bankaccount', models.CharField(blank=True, max_length=500, null=True)),
                ('artype', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, max_length=500, null=True)),
                ('statusdate', models.CharField(blank=True, max_length=500, null=True)),
                ('enterby', models.CharField(blank=True, max_length=500, null=True)),
                ('enterdate', models.CharField(blank=True, max_length=500, null=True)),
                ('product', models.CharField(blank=True, max_length=500, null=True)),
                ('initmark', models.CharField(blank=True, max_length=500, null=True)),
                ('glsmark', models.CharField(blank=True, max_length=500, null=True)),
                ('glsdate', models.CharField(blank=True, max_length=500, null=True)),
                ('totalwtax', models.CharField(blank=True, max_length=500, null=True)),
                ('gov', models.CharField(blank=True, max_length=500, null=True)),
                ('branchcode', models.CharField(blank=True, max_length=500, null=True)),
                ('address1', models.CharField(blank=True, max_length=500, null=True)),
                ('address2', models.CharField(blank=True, max_length=500, null=True)),
                ('address3', models.CharField(blank=True, max_length=500, null=True)),
                ('tin', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'temp_ormain',
            },
        ),
    ]
