# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-11-03 07:49
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processing_or', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp_ormain',
            name='importby',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ormain_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='temp_ormain',
            name='importdate',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 11, 3, 7, 49, 40, 685000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temp_ormain',
            name='importkey',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
