# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-11-03 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing_or', '0002_auto_20171103_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temp_ormain',
            name='importkey',
        ),
        migrations.AddField(
            model_name='temp_ormain',
            name='importsequence',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
