# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-11-03 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing_or', '0004_temp_ormain_agentcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp_ormain',
            name='particulars',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
