# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-12-13 06:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processing_or', '0005_temp_ormain_particulars'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs_ormain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orno', models.CharField(blank=True, max_length=500, null=True)),
                ('ordate', models.CharField(blank=True, max_length=500, null=True)),
                ('prno', models.CharField(blank=True, max_length=500, null=True)),
                ('accounttype', models.CharField(blank=True, max_length=500, null=True)),
                ('collector', models.CharField(blank=True, max_length=500, null=True)),
                ('payeetype', models.CharField(blank=True, max_length=500, null=True)),
                ('adtype', models.CharField(blank=True, max_length=500, null=True)),
                ('agencycode', models.CharField(blank=True, max_length=500, null=True)),
                ('clientcode', models.CharField(blank=True, max_length=500, null=True)),
                ('agentcode', models.CharField(blank=True, max_length=500, null=True)),
                ('payeename', models.CharField(blank=True, max_length=500, null=True)),
                ('amount', models.CharField(blank=True, max_length=500, null=True)),
                ('amountinwords', models.CharField(blank=True, max_length=500, null=True)),
                ('bankaccount', models.CharField(blank=True, max_length=500, null=True)),
                ('particulars', models.CharField(blank=True, max_length=500, null=True)),
                ('artype', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, max_length=500, null=True)),
                ('statusdate', models.CharField(blank=True, max_length=500, null=True)),
                ('enterby', models.CharField(blank=True, max_length=500, null=True)),
                ('enterdate', models.CharField(blank=True, max_length=500, null=True)),
                ('product', models.CharField(blank=True, max_length=500, null=True)),
                ('initmark', models.CharField(blank=True, max_length=500, null=True)),
                ('glsmark', models.CharField(blank=True, max_length=500, null=True)),
                ('glsdate', models.CharField(blank=True, max_length=500, null=True)),
                ('totalwtax', models.CharField(blank=True, max_length=500, null=True)),
                ('gov', models.CharField(blank=True, max_length=500, null=True)),
                ('branchcode', models.CharField(blank=True, max_length=500, null=True)),
                ('address1', models.CharField(blank=True, max_length=500, null=True)),
                ('address2', models.CharField(blank=True, max_length=500, null=True)),
                ('address3', models.CharField(blank=True, max_length=500, null=True)),
                ('tin', models.CharField(blank=True, max_length=500, null=True)),
                ('batchkey', models.CharField(blank=True, max_length=255, null=True)),
                ('importdate', models.DateTimeField(auto_now_add=True)),
                ('importby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='logs_ormain_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'logs_ormain',
            },
        ),
    ]
