# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-12-13 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing_or', '0006_logs_ormain'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs_ormain',
            name='importstatus',
            field=models.CharField(choices=[('F', 'Failed'), ('S', 'Success'), ('P', 'Posted')], default='S', max_length=1),
        ),
    ]
