# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-12-18 04:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processing_or', '0008_logs_ormain_importremarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs_ordetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orno', models.CharField(blank=True, max_length=500, null=True)),
                ('doctype', models.CharField(blank=True, max_length=500, null=True)),
                ('docnum', models.CharField(blank=True, max_length=500, null=True)),
                ('balance', models.CharField(blank=True, max_length=500, null=True)),
                ('assignamount', models.CharField(blank=True, max_length=500, null=True)),
                ('assignvatamount', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, max_length=500, null=True)),
                ('statusdate', models.CharField(blank=True, max_length=500, null=True)),
                ('usercode', models.CharField(blank=True, max_length=500, null=True)),
                ('userdate', models.CharField(blank=True, max_length=500, null=True)),
                ('docitem', models.CharField(blank=True, max_length=500, null=True)),
                ('initmark', models.CharField(blank=True, max_length=500, null=True)),
                ('glsmark', models.CharField(blank=True, max_length=500, null=True)),
                ('glsdate', models.CharField(blank=True, max_length=500, null=True)),
                ('assignwtaxamount', models.CharField(blank=True, max_length=500, null=True)),
                ('assignwvatamount', models.CharField(blank=True, max_length=500, null=True)),
                ('batchkey', models.CharField(blank=True, max_length=255, null=True)),
                ('importstatus', models.CharField(choices=[('F', 'Failed'), ('S', 'Success'), ('P', 'Posted')], default='S', max_length=1)),
                ('importremarks', models.CharField(blank=True, max_length=255, null=True)),
                ('importdate', models.DateTimeField(auto_now_add=True)),
                ('importby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='logs_ordetail_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'logs_ordetail',
            },
        ),
    ]
