# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-12-19 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing_or', '0011_logs_ordetail_adtypedesc'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs_ordetail',
            name='vatcode',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='logs_ordetail',
            name='vatrate',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='logs_ormain',
            name='branchdesc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='logs_ormain',
            name='collectordesc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='logs_ormain',
            name='vatcode',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='logs_ormain',
            name='vatrate',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
