# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-12-19 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing_or', '0014_auto_20171219_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp_ordetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orno', models.CharField(blank=True, max_length=500, null=True)),
                ('ordate', models.CharField(blank=True, max_length=500, null=True)),
                ('adtypecode', models.CharField(blank=True, max_length=500, null=True)),
                ('amount', models.CharField(blank=True, max_length=500, null=True)),
                ('vatamount', models.CharField(blank=True, max_length=500, null=True)),
                ('debitamount', models.CharField(blank=True, max_length=500, null=True)),
                ('creditamount', models.CharField(blank=True, max_length=500, null=True)),
                ('balancecode', models.CharField(blank=True, max_length=500, null=True)),
                ('chartofaccountcode', models.CharField(blank=True, max_length=500, null=True)),
                ('vatrate', models.CharField(blank=True, max_length=500, null=True)),
                ('vatcode', models.CharField(blank=True, max_length=500, null=True)),
                ('batchkey', models.CharField(blank=True, max_length=500, null=True)),
                ('postingstatus', models.CharField(choices=[('F', 'Failed'), ('S', 'Success')], default='F', max_length=1)),
                ('postingremarks', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'temp_ordetail',
            },
        ),
        migrations.AddField(
            model_name='temp_ormain',
            name='batchkey',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
