# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-12-19 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing_or', '0015_auto_20171219_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp_ordetail',
            name='payeecode',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='temp_ordetail',
            name='payeename',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
