# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-12-19 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing_or', '0016_auto_20171219_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp_ormain',
            name='productcode',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
