# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-02 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing_or', '0017_temp_ormain_productcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp_ordetail',
            name='bankaccountcode',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
