# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-02 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing_or', '0018_temp_ordetail_bankaccountcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs_ormain',
            name='wtaxrate',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='temp_ormain',
            name='totalwtax',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='temp_ormain',
            name='wtaxrate',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
