# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-15 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing_or', '0022_temp_ordetail_productcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs_ordetail',
            name='product',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='temp_ordetail',
            name='product',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
