# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-12 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing_or', '0024_auto_20180116_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp_ordetail',
            name='status',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='temp_ormain',
            name='status',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
