# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-15 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing_or', '0025_auto_20180212_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp_ormain',
            name='importdate',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
