# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-20 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing_or', '0026_temp_ormain_importdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp_ormain',
            name='enterby',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='temp_ormain',
            name='enterdate',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
