# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-03-27 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing_or', '0027_auto_20180220_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp_ordetail',
            name='customercode',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='temp_ordetail',
            name='outputvatcode',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
