# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-06-29 16:13
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supplier', '0018_auto_20170629_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ofmain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ofnum', models.CharField(max_length=10, unique=True)),
                ('ofdate', models.DateField()),
                ('payee_code', models.CharField(max_length=25)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('particulars', models.TextField()),
                ('ofstatus', models.CharField(choices=[('F', 'For Approval'), ('A', 'Approved'), ('D', 'Disapproved')], default='F', max_length=1)),
                ('approverresponse', models.CharField(blank=True, choices=[('A', 'Approved'), ('D', 'Disapproved')], max_length=1, null=True)),
                ('responsedate', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('C', 'Cancelled'), ('O', 'Posted'), ('P', 'Printed')], default='A', max_length=1)),
                ('enterdate', models.DateTimeField(auto_now_add=True)),
                ('modifydate', models.DateTimeField(default=datetime.datetime(2017, 6, 29, 16, 12, 59, 327000))),
                ('postdate', models.DateTimeField(blank=True, null=True)),
                ('receivedate', models.DateTimeField(blank=True, null=True)),
                ('isdeleted', models.IntegerField(default=0)),
                ('print_ctr', models.IntegerField(default=0)),
                ('actualapprover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofmain_actual_approver', to=settings.AUTH_USER_MODEL)),
                ('designatedapprover', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='ofmain_designated_approver', to=settings.AUTH_USER_MODEL)),
                ('enterby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ofmain_enter', to=settings.AUTH_USER_MODEL)),
                ('modifyby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ofmain_modify', to=settings.AUTH_USER_MODEL)),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofmain_payee_id', to='supplier.Supplier')),
                ('postby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofmain_post', to=settings.AUTH_USER_MODEL)),
                ('receiveby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofmain_receive', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'ofmain',
                'permissions': (('view_operationalfund', 'Can view operational fund'),),
            },
        ),
    ]
