# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-10 15:55
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wtax', '0005_auto_20170710_1555'),
        ('inputvattype', '0005_auto_20170710_1555'),
        ('creditterm', '0005_auto_20170710_1555'),
        ('currency', '0012_auto_20170710_1555'),
        ('vat', '0011_auto_20170710_1555'),
        ('ataxcode', '0008_auto_20170710_1555'),
        ('operationalfund', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofmain',
            name='atc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ofmain_atc_id', to='ataxcode.Ataxcode', validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ofmain',
            name='atcrate',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='ofmain',
            name='creditterm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofmain_creditterm_id', to='creditterm.Creditterm'),
        ),
        migrations.AddField(
            model_name='ofmain',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ofmain_currency_id', to='currency.Currency'),
        ),
        migrations.AddField(
            model_name='ofmain',
            name='deferredvat',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='ofmain',
            name='fxrate',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='ofmain',
            name='inputvattype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ofmain_inputvattype_id', to='inputvattype.Inputvattype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ofmain',
            name='ofsubtype',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        # migrations.AddField(
        #     model_name='ofmain',
        #     name='oftype',
        #     field=models.CharField(choices=[('E', 'Expenses'), ('A', 'Advances')], default='E', max_length=1),
        # ),
        migrations.AddField(
            model_name='ofmain',
            name='payee_name',
            field=models.CharField(default='payee', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ofmain',
            name='refnum',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ofmain',
            name='vat',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='ofmain_vat_id', to='vat.Vat', validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ofmain',
            name='vatrate',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='ofmain',
            name='wtax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofmain_wtax_id', to='wtax.Wtax', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='ofmain',
            name='wtaxamount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='ofmain',
            name='wtaxrate',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='ofmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 10, 15, 55, 30, 899000)),
        ),
    ]
