# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-11 16:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operationalfund', '0002_auto_20170710_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 11, 16, 30, 34, 973000)),
        ),
        migrations.AlterField(
            model_name='ofmain',
            name='payee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofmain_payee_id', to='supplier.Supplier'),
        ),
        migrations.AlterField(
            model_name='ofmain',
            name='payee_code',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
