# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-13 15:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationalfund', '0004_auto_20170713_0957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ofmain',
            options={'ordering': ['-pk'], 'permissions': (('view_operationalfund', 'Can view operational fund'), ('approve_assignedof', 'Can approve assigned of'), ('approve_allof', 'Can approve all of'))},
        ),
        migrations.AlterField(
            model_name='ofmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 13, 15, 16, 7, 646000)),
        ),
    ]
