# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-17 09:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationalfund', '0005_auto_20170713_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ofmain',
            options={'ordering': ['-pk'], 'permissions': (('view_operationalfund', 'Can view operational fund'), ('approve_assignedof', 'Can approve assigned of'), ('approve_allof', 'Can approve all of'), ('is_cashier', "Is from cashier's office"))},
        ),
        migrations.AlterField(
            model_name='ofmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 17, 9, 18, 51, 957000)),
        ),
    ]
