# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-18 10:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operationalfund', '0006_auto_20170717_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 18, 10, 17, 20, 96000)),
        ),
        # migrations.AlterField(
        #     model_name='ofmain',
        #     name='oftype',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofmain_oftype_id', to='oftype.Oftype'),
        # ),
    ]
