# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-18 10:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationalfund', '0011_auto_20170718_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 18, 10, 23, 25, 456000)),
        ),
    ]
