# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-18 13:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ofsubtype', '0002_auto_20170718_1349'),
        ('operationalfund', '0017_auto_20170718_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofmain',
            name='ofsubtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofmain_ofsubtype_id', to='ofsubtype.Ofsubtype'),
        ),
        migrations.AlterField(
            model_name='ofmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 18, 13, 49, 13, 596000)),
        ),
    ]
