# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-18 17:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationalfund', '0018_auto_20170718_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofmain',
            name='deferredvat',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='ofmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 18, 17, 35, 14, 947000)),
        ),
    ]
