# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-19 11:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0021_auto_20170719_1121'),
        ('employee', '0006_auto_20170719_1121'),
        ('operationalfund', '0019_auto_20170718_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofmain',
            name='department',
            field=models.ForeignKey(default=69, on_delete=django.db.models.deletion.CASCADE, related_name='ofmain_department_id', to='department.Department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ofmain',
            name='department_code',
            field=models.CharField(default='IT', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ofmain',
            name='department_name',
            field=models.CharField(default='INFORMATION TECHNOLOGY', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ofmain',
            name='employee',
            field=models.ForeignKey(default=709, on_delete=django.db.models.deletion.CASCADE, related_name='ofmain_employee_id', to='employee.Employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ofmain',
            name='employee_name',
            field=models.CharField(default='REY KENNETH MOLINA', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ofmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 19, 11, 20, 36, 741000)),
        ),
    ]
