# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-19 16:15
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationalfund', '0022_auto_20170719_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofmain',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='ofmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 19, 16, 14, 58, 578000)),
        ),
    ]
