# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-19 17:17
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operationalfund', '0025_auto_20170719_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofmain',
            name='releaseby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofmain_release', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ofmain',
            name='releasedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ofmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 19, 17, 17, 43, 232000)),
        ),
    ]
