# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-20 15:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationalfund', '0026_auto_20170719_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 20, 15, 19, 2, 867000)),
        ),
        migrations.AlterField(
            model_name='ofmain',
            name='ofstatus',
            field=models.CharField(choices=[('F', 'For Approval'), ('A', 'Approved'), ('D', 'Disapproved'), ('I', 'In Process'), ('R', 'RELEASED')], default='F', max_length=1),
        ),
    ]
