# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-20 16:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20170720_1646'),
        ('operationalfund', '0027_auto_20170720_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofmain',
            name='paymentreceivedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofmain_paymentreceived', to='employee.Employee'),
        ),
        migrations.AddField(
            model_name='ofmain',
            name='paymentreceiveddate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ofmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 20, 16, 46, 53, 695000)),
        ),
    ]
