# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-27 15:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0018_auto_20170727_1539'),
        ('operationalfund', '0029_auto_20170727_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofmain',
            name='branch',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='ofmain_branch_id', to='branch.Branch'),
        ),
        migrations.AlterField(
            model_name='ofmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 27, 15, 39, 53, 432000)),
        ),
    ]
