# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-08-18 08:40
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ofsubtype', '0005_auto_20170818_1640'),
        ('inputvattype', '0008_auto_20170818_1640'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('currency', '0015_auto_20170818_1640'),
        ('oftype', '0007_auto_20170818_1640'),
        ('vat', '0019_auto_20170818_1640'),
        ('supplier', '0028_auto_20170818_1640'),
        ('operationalfund', '0032_auto_20170728_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ofitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_counter', models.IntegerField()),
                ('ofnum', models.CharField(max_length=10)),
                ('ofdate', models.DateTimeField()),
                ('payee_code', models.CharField(blank=True, max_length=25, null=True)),
                ('payee_name', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)])),
                ('particulars', models.TextField()),
                ('refnum', models.CharField(blank=True, max_length=150, null=True)),
                ('vatrate', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('deferredvat', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, null=True)),
                ('fxrate', models.DecimalField(blank=True, decimal_places=5, default=1.0, max_digits=18, null=True)),
                ('remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('periodfrom', models.DateTimeField(blank=True, null=True)),
                ('periodto', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('C', 'Cancelled'), ('O', 'Posted'), ('P', 'Printed')], default='A', max_length=1)),
                ('enterdate', models.DateTimeField(auto_now_add=True)),
                ('modifydate', models.DateTimeField(default=datetime.datetime(2017, 8, 18, 16, 40, 25, 46000))),
                ('postdate', models.DateTimeField(default=datetime.datetime(2017, 8, 18, 16, 40, 25, 46000))),
                ('isdeleted', models.IntegerField(default=0)),
                ('currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ofitem_currency_id', to='currency.Currency')),
                ('enterby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ofitem_enter', to=settings.AUTH_USER_MODEL)),
                ('inputvattype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofitem_inputvattype_id', to='inputvattype.Inputvattype')),
                ('modifyby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ofitem_modify', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'ofitem',
            },
        ),
        migrations.CreateModel(
            name='Ofitemtemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_counter', models.IntegerField()),
                ('secretkey', models.CharField(blank=True, max_length=255, null=True)),
                ('ofmain', models.CharField(blank=True, max_length=10, null=True)),
                ('ofitem', models.CharField(blank=True, max_length=10, null=True)),
                ('ofnum', models.CharField(max_length=10)),
                ('ofdate', models.DateTimeField(blank=True, null=True)),
                ('oftype', models.IntegerField(blank=True, null=True)),
                ('ofsubtype', models.IntegerField(blank=True, null=True)),
                ('payee', models.IntegerField(blank=True, null=True)),
                ('payee_code', models.CharField(blank=True, max_length=25, null=True)),
                ('payee_name', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)])),
                ('particulars', models.TextField(blank=True, null=True)),
                ('refnum', models.CharField(blank=True, max_length=150, null=True)),
                ('vat', models.IntegerField(blank=True, null=True)),
                ('vatrate', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('inputvattype', models.IntegerField(blank=True, null=True)),
                ('deferredvat', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, null=True)),
                ('currency', models.IntegerField(blank=True, null=True)),
                ('fxrate', models.DecimalField(blank=True, decimal_places=5, max_digits=18, null=True)),
                ('remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('periodfrom', models.DateTimeField(blank=True, null=True)),
                ('periodto', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('C', 'Cancelled'), ('O', 'Posted'), ('P', 'Printed')], default='A', max_length=1)),
                ('enterdate', models.DateTimeField(auto_now_add=True)),
                ('modifydate', models.DateTimeField(default=datetime.datetime(2017, 8, 18, 16, 40, 25, 56000))),
                ('postdate', models.DateTimeField(default=datetime.datetime(2017, 8, 18, 16, 40, 25, 56000))),
                ('isdeleted', models.IntegerField(default=0)),
                ('enterby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ofitemtemp_enter', to=settings.AUTH_USER_MODEL)),
                ('modifyby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ofitemtemp_modify', to=settings.AUTH_USER_MODEL)),
                ('postby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofitemtemp_post', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'ofitemtemp',
            },
        ),
        migrations.AddField(
            model_name='ofmain',
            name='approvedamount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='ofdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 18, 16, 40, 25, 49000)),
        ),
        migrations.AlterField(
            model_name='ofdetail',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 18, 16, 40, 25, 49000)),
        ),
        migrations.AlterField(
            model_name='ofdetailbreakdown',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 18, 16, 40, 25, 53000)),
        ),
        migrations.AlterField(
            model_name='ofdetailbreakdown',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 18, 16, 40, 25, 53000)),
        ),
        migrations.AlterField(
            model_name='ofdetailbreakdowntemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 18, 16, 40, 25, 61000)),
        ),
        migrations.AlterField(
            model_name='ofdetailbreakdowntemp',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 18, 16, 40, 25, 61000)),
        ),
        migrations.AlterField(
            model_name='ofdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 18, 16, 40, 25, 58000)),
        ),
        migrations.AlterField(
            model_name='ofdetailtemp',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 18, 16, 40, 25, 58000)),
        ),
        migrations.AlterField(
            model_name='ofmain',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofmain_currency_id', to='currency.Currency'),
        ),
        migrations.AlterField(
            model_name='ofmain',
            name='fxrate',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='ofmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 18, 16, 40, 25, 42000)),
        ),
        migrations.AlterField(
            model_name='ofmain',
            name='payee_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ofitem',
            name='ofmain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofitem_ofmain_id', to='operationalfund.Ofmain'),
        ),
        migrations.AddField(
            model_name='ofitem',
            name='ofsubtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofitem_ofsubtype_id', to='ofsubtype.Ofsubtype'),
        ),
        migrations.AddField(
            model_name='ofitem',
            name='oftype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofitem_oftype_id', to='oftype.Oftype'),
        ),
        migrations.AddField(
            model_name='ofitem',
            name='payee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofitem_payee_id', to='supplier.Supplier'),
        ),
        migrations.AddField(
            model_name='ofitem',
            name='postby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofitem_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ofitem',
            name='vat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofitem_vat_id', to='vat.Vat', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
