# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-08-18 09:05
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operationalfund', '0033_auto_20170818_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofmain',
            name='requestor',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='ofmain_requestor_id', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ofmain',
            name='requestor_name',
            field=models.CharField(default='Grace Ann Villanueva', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ofmain',
            name='requestor_username',
            field=models.CharField(default='graceannvillanueva', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ofdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 18, 17, 4, 32, 350000)),
        ),
        migrations.AlterField(
            model_name='ofdetail',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 18, 17, 4, 32, 350000)),
        ),
        migrations.AlterField(
            model_name='ofdetailbreakdown',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 18, 17, 4, 32, 354000)),
        ),
        migrations.AlterField(
            model_name='ofdetailbreakdown',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 18, 17, 4, 32, 354000)),
        ),
        migrations.AlterField(
            model_name='ofdetailbreakdowntemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 18, 17, 4, 32, 363000)),
        ),
        migrations.AlterField(
            model_name='ofdetailbreakdowntemp',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 18, 17, 4, 32, 363000)),
        ),
        migrations.AlterField(
            model_name='ofdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 18, 17, 4, 32, 360000)),
        ),
        migrations.AlterField(
            model_name='ofdetailtemp',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 18, 17, 4, 32, 360000)),
        ),
        migrations.AlterField(
            model_name='ofitem',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 18, 17, 4, 32, 347000)),
        ),
        migrations.AlterField(
            model_name='ofitem',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 18, 17, 4, 32, 347000)),
        ),
        migrations.AlterField(
            model_name='ofitemtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 18, 17, 4, 32, 357000)),
        ),
        migrations.AlterField(
            model_name='ofitemtemp',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 18, 17, 4, 32, 357000)),
        ),
        migrations.AlterField(
            model_name='ofmain',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofmain_employee_id', to='employee.Employee'),
        ),
        migrations.AlterField(
            model_name='ofmain',
            name='employee_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ofmain',
            name='employee_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='ofmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 18, 17, 4, 32, 343000)),
        ),
    ]
