# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-08-23 06:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationalfund', '0035_auto_20170823_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 23, 14, 41, 4, 310000)),
        ),
        migrations.AlterField(
            model_name='ofdetail',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 23, 14, 41, 4, 310000)),
        ),
        migrations.AlterField(
            model_name='ofdetailbreakdown',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 23, 14, 41, 4, 314000)),
        ),
        migrations.AlterField(
            model_name='ofdetailbreakdown',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 23, 14, 41, 4, 314000)),
        ),
        migrations.AlterField(
            model_name='ofdetailbreakdowntemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 23, 14, 41, 4, 328000)),
        ),
        migrations.AlterField(
            model_name='ofdetailbreakdowntemp',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 23, 14, 41, 4, 328000)),
        ),
        migrations.AlterField(
            model_name='ofdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 23, 14, 41, 4, 323000)),
        ),
        migrations.AlterField(
            model_name='ofdetailtemp',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 23, 14, 41, 4, 324000)),
        ),
        migrations.AlterField(
            model_name='ofitem',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 23, 14, 41, 4, 306000)),
        ),
        migrations.AlterField(
            model_name='ofitem',
            name='periodfrom',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ofitem',
            name='periodto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ofitem',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 23, 14, 41, 4, 307000)),
        ),
        migrations.AlterField(
            model_name='ofitemtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 23, 14, 41, 4, 319000)),
        ),
        migrations.AlterField(
            model_name='ofitemtemp',
            name='periodfrom',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ofitemtemp',
            name='periodto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ofitemtemp',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 23, 14, 41, 4, 319000)),
        ),
        migrations.AlterField(
            model_name='ofmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 23, 14, 41, 4, 298000)),
        ),
    ]
