# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-08-23 08:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationalfund', '0037_auto_20170823_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ofitemtemp',
            name='ofsubtype',
        ),
        migrations.AlterField(
            model_name='ofdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 23, 16, 12, 18, 763000)),
        ),
        migrations.AlterField(
            model_name='ofdetail',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 23, 16, 12, 18, 763000)),
        ),
        migrations.AlterField(
            model_name='ofdetailbreakdown',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 23, 16, 12, 18, 768000)),
        ),
        migrations.AlterField(
            model_name='ofdetailbreakdown',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 23, 16, 12, 18, 768000)),
        ),
        migrations.AlterField(
            model_name='ofdetailbreakdowntemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 23, 16, 12, 18, 777000)),
        ),
        migrations.AlterField(
            model_name='ofdetailbreakdowntemp',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 23, 16, 12, 18, 777000)),
        ),
        migrations.AlterField(
            model_name='ofdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 23, 16, 12, 18, 774000)),
        ),
        migrations.AlterField(
            model_name='ofdetailtemp',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 23, 16, 12, 18, 774000)),
        ),
        migrations.AlterField(
            model_name='ofitem',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 23, 16, 12, 18, 759000)),
        ),
        migrations.AlterField(
            model_name='ofitem',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 23, 16, 12, 18, 759000)),
        ),
        migrations.AlterField(
            model_name='ofitemtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 23, 16, 12, 18, 772000)),
        ),
        migrations.AlterField(
            model_name='ofitemtemp',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 23, 16, 12, 18, 772000)),
        ),
        migrations.AlterField(
            model_name='ofmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 23, 16, 12, 18, 752000)),
        ),
    ]
