# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-08-23 08:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationalfund', '0040_auto_20170823_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ofmain',
            name='atc',
        ),
        migrations.RemoveField(
            model_name='ofmain',
            name='atcrate',
        ),
        migrations.RemoveField(
            model_name='ofmain',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='ofmain',
            name='deferredvat',
        ),
        migrations.RemoveField(
            model_name='ofmain',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='ofmain',
            name='employee_code',
        ),
        migrations.RemoveField(
            model_name='ofmain',
            name='employee_name',
        ),
        migrations.RemoveField(
            model_name='ofmain',
            name='fxrate',
        ),
        migrations.RemoveField(
            model_name='ofmain',
            name='inputvattype',
        ),
        migrations.RemoveField(
            model_name='ofmain',
            name='ofsubtype',
        ),
        migrations.RemoveField(
            model_name='ofmain',
            name='payee',
        ),
        migrations.RemoveField(
            model_name='ofmain',
            name='payee_code',
        ),
        migrations.RemoveField(
            model_name='ofmain',
            name='payee_name',
        ),
        migrations.RemoveField(
            model_name='ofmain',
            name='vat',
        ),
        migrations.RemoveField(
            model_name='ofmain',
            name='vatrate',
        ),
        migrations.AlterField(
            model_name='ofdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 23, 16, 32, 17, 216000)),
        ),
        migrations.AlterField(
            model_name='ofdetail',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 23, 16, 32, 17, 217000)),
        ),
        migrations.AlterField(
            model_name='ofdetailbreakdown',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 23, 16, 32, 17, 221000)),
        ),
        migrations.AlterField(
            model_name='ofdetailbreakdown',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 23, 16, 32, 17, 221000)),
        ),
        migrations.AlterField(
            model_name='ofdetailbreakdowntemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 23, 16, 32, 17, 235000)),
        ),
        migrations.AlterField(
            model_name='ofdetailbreakdowntemp',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 23, 16, 32, 17, 236000)),
        ),
        migrations.AlterField(
            model_name='ofdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 23, 16, 32, 17, 232000)),
        ),
        migrations.AlterField(
            model_name='ofdetailtemp',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 23, 16, 32, 17, 232000)),
        ),
        migrations.AlterField(
            model_name='ofitem',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 23, 16, 32, 17, 213000)),
        ),
        migrations.AlterField(
            model_name='ofitem',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 23, 16, 32, 17, 213000)),
        ),
        migrations.AlterField(
            model_name='ofitemtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 23, 16, 32, 17, 226000)),
        ),
        migrations.AlterField(
            model_name='ofitemtemp',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 23, 16, 32, 17, 228000)),
        ),
        migrations.AlterField(
            model_name='ofmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 23, 16, 32, 17, 209000)),
        ),
    ]
