# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-09-05 02:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operationalfund', '0046_auto_20170904_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofdetail',
            name='ofitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofitem_ofdetail_id', to='operationalfund.Ofitem'),
        ),
        migrations.AddField(
            model_name='ofdetailtemp',
            name='ofitem',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ofdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 5, 10, 27, 15, 849000)),
        ),
        migrations.AlterField(
            model_name='ofdetailbreakdown',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 5, 10, 27, 15, 853000)),
        ),
        migrations.AlterField(
            model_name='ofdetailbreakdowntemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 5, 10, 27, 15, 861000)),
        ),
        migrations.AlterField(
            model_name='ofdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 5, 10, 27, 15, 858000)),
        ),
        migrations.AlterField(
            model_name='ofitem',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 5, 10, 27, 15, 846000)),
        ),
        migrations.AlterField(
            model_name='ofitemtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 5, 10, 27, 15, 856000)),
        ),
        migrations.AlterField(
            model_name='ofmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 5, 10, 27, 15, 842000)),
        ),
    ]
