# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-09-06 10:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkvoucher', '0013_auto_20170906_1838'),
        ('replenish_pcv', '0002_auto_20170906_1838'),
        ('operationalfund', '0050_auto_20170906_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofmain',
            name='cvmain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofmain_cvmain_id', to='checkvoucher.Cvmain'),
        ),
        migrations.AddField(
            model_name='ofmain',
            name='reppcvdetail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofmain_reppcvdetail_id', to='replenish_pcv.Reppcvdetail'),
        ),
        migrations.AddField(
            model_name='ofmain',
            name='reppcvmain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofmain_reppcvmain_id', to='replenish_pcv.Reppcvmain'),
        ),
        migrations.AlterField(
            model_name='ofdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 6, 18, 38, 42, 440000)),
        ),
        migrations.AlterField(
            model_name='ofdetailbreakdown',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 6, 18, 38, 42, 444000)),
        ),
        migrations.AlterField(
            model_name='ofdetailbreakdowntemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 6, 18, 38, 42, 453000)),
        ),
        migrations.AlterField(
            model_name='ofdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 6, 18, 38, 42, 450000)),
        ),
        migrations.AlterField(
            model_name='ofitem',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 6, 18, 38, 42, 436000)),
        ),
        migrations.AlterField(
            model_name='ofitemtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 6, 18, 38, 42, 447000)),
        ),
        migrations.AlterField(
            model_name='ofmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 6, 18, 38, 42, 432000)),
        ),
    ]
