# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-09-19 02:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountspayable', '0009_auto_20170919_1053'),
        ('replenish_rfv', '0002_auto_20170919_1053'),
        ('operationalfund', '0053_auto_20170919_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofmain',
            name='apmain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofmain_apmain_id', to='accountspayable.Apmain'),
        ),
        migrations.AddField(
            model_name='ofmain',
            name='reprfvdetail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofmain_reprfvdetail_id', to='replenish_rfv.Reprfvdetail'),
        ),
        migrations.AddField(
            model_name='ofmain',
            name='reprfvmain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofmain_reprfvmain_id', to='replenish_rfv.Reprfvmain'),
        ),
        migrations.AlterField(
            model_name='ofdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 19, 10, 53, 35, 752000)),
        ),
        migrations.AlterField(
            model_name='ofdetailbreakdown',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 19, 10, 53, 35, 756000)),
        ),
        migrations.AlterField(
            model_name='ofdetailbreakdowntemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 19, 10, 53, 35, 765000)),
        ),
        migrations.AlterField(
            model_name='ofdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 19, 10, 53, 35, 762000)),
        ),
        migrations.AlterField(
            model_name='ofitem',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 19, 10, 53, 35, 749000)),
        ),
        migrations.AlterField(
            model_name='ofitemtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 19, 10, 53, 35, 759000)),
        ),
        migrations.AlterField(
            model_name='ofmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 19, 10, 53, 35, 744000)),
        ),
    ]
