# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-10-20 05:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationalfund', '0057_auto_20171019_1134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ofmain',
            options={'ordering': ['-pk'], 'permissions': (('view_operationalfund', 'Can view operational fund'), ('approve_assignedof', 'Can approve assigned of'), ('approve_allof', 'Can approve all of'), ('is_cashier', "Is from cashier's office"), ('assign_requestor', 'Can assign requestor'))},
        ),
        migrations.AlterField(
            model_name='ofdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 20, 13, 6, 52, 279000)),
        ),
        migrations.AlterField(
            model_name='ofdetailbreakdown',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 20, 13, 6, 52, 286000)),
        ),
        migrations.AlterField(
            model_name='ofdetailbreakdowntemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 20, 13, 6, 52, 298000)),
        ),
        migrations.AlterField(
            model_name='ofdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 20, 13, 6, 52, 296000)),
        ),
        migrations.AlterField(
            model_name='ofitem',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 20, 13, 6, 52, 275000)),
        ),
        migrations.AlterField(
            model_name='ofitemtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 20, 13, 6, 52, 292000)),
        ),
        migrations.AlterField(
            model_name='ofmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 20, 13, 6, 52, 266000)),
        ),
    ]
