# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-03-08 08:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationalfund', '0059_auto_20171023_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofitem',
            name='noofpax',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ofitemtemp',
            name='noofpax',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ofdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 8, 16, 46, 12, 17000)),
        ),
        migrations.AlterField(
            model_name='ofdetailbreakdown',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 8, 16, 46, 12, 21000)),
        ),
        migrations.AlterField(
            model_name='ofdetailbreakdowntemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 8, 16, 46, 12, 29000)),
        ),
        migrations.AlterField(
            model_name='ofdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 8, 16, 46, 12, 29000)),
        ),
        migrations.AlterField(
            model_name='ofitem',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 8, 16, 46, 12, 17000)),
        ),
        migrations.AlterField(
            model_name='ofitemtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 8, 16, 46, 12, 25000)),
        ),
        migrations.AlterField(
            model_name='ofmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 8, 16, 46, 12, 13000)),
        ),
    ]
