# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-05-15 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationalfund', '0062_auto_20180322_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofmain',
            name='ofstatus',
            field=models.CharField(choices=[('F', 'For Approval'), ('A', 'Approved'), ('D', 'Disapproved'), ('I', 'In Process'), ('P', 'For JV'), ('R', 'Released')], default='F', max_length=1),
        ),
    ]
