# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-06-19 05:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 19, 13, 5, 49, 301000)),
        ),
    ]
