# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-10 12:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unitofmeasure', '0002_auto_20170322_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitofmeasure',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 10, 12, 48, 34, 66000)),
        ),
    ]
