# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-11 14:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unitofmeasure', '0003_auto_20170410_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitofmeasure',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 11, 14, 33, 36, 575000)),
        ),
    ]
