# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-05-19 03:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unitofmeasure', '0005_auto_20170421_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitofmeasure',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 19, 11, 25, 26, 776000)),
        ),
    ]
