# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-04-02 08:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs_closed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datefrom', models.DateTimeField()),
                ('dateto', models.DateTimeField()),
                ('transactioncount', models.IntegerField(default=0)),
                ('closedon', models.DateTimeField()),
                ('status', models.CharField(choices=[('P', 'Passed'), ('F', 'Failed')], max_length=1)),
                ('closedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_closedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'logs_closed',
                'permissions': (('view_logs_closed', 'Can view logs_closed'),),
            },
        ),
    ]
