# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-11-20 01:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcartype', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcartype',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 20, 9, 26, 55, 917000)),
        ),
    ]
