# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-11-20 01:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outputvattype', '0002_auto_20171010_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outputvattype',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 20, 9, 19, 36, 695000)),
        ),
    ]
