# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-05-04 17:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputvattype', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputvattype',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 4, 17, 52, 23, 328000)),
        ),
    ]
