# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-04 03:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputvattype', '0004_auto_20170620_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputvattype',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 4, 11, 54, 49, 742000)),
        ),
    ]
