# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-22 13:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccount', '0008_auto_20170322_1356'),
        ('inventoryitemclass', '0003_auto_20170322_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitemclass',
            name='chartofaccountinventory',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='invclass_chartofaccountinv_id', to='chartofaccount.Chartofaccount'),
        ),
        migrations.AlterField(
            model_name='inventoryitemclass',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 22, 13, 56, 46, 732561)),
        ),
    ]
