# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-11-09 01:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryitemclass', '0005_auto_20171108_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitemclass',
            name='chartofaccountinventory',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invclass_chartofaccountinv_id', to='chartofaccount.Chartofaccount'),
        ),
        migrations.AlterField(
            model_name='inventoryitemclass',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 9, 9, 56, 48, 28000)),
        ),
    ]
