# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-10 07:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productgroup', '0002_auto_20171107_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgroup',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 10, 15, 0, 11, 390000)),
        ),
    ]
