# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-10 07:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productgroup', '0003_auto_20180110_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgroup',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 10, 15, 30, 5, 79000)),
        ),
    ]
