# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-21 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryitemtype', '0002_auto_20170321_0928'),
        ('inventoryitemtype', '0002_auto_20170321_1255'),
    ]

    operations = [
    ]
