# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-27 13:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryitemtype', '0007_auto_20170323_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitemtype',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 27, 13, 37, 10, 675000)),
        ),
    ]
