# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-31 09:15
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chartofaccount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productbudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(2100), django.core.validators.MinValueValidator(1980)])),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('formula', models.CharField(blank=True, max_length=255, null=True)),
                ('method', models.CharField(blank=True, max_length=255, null=True)),
                ('mjan', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('mfeb', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('mmar', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('mapr', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('mmay', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('mjun', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('mjul', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('maug', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('msep', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('moct', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('mnov', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('mdec', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('C', 'Cancelled'), ('O', 'Posted'), ('P', 'Printed')], default='A', max_length=1)),
                ('enterdate', models.DateTimeField(auto_now_add=True)),
                ('modifydate', models.DateTimeField(default=datetime.datetime(2017, 1, 31, 17, 15, 47, 652069))),
                ('isdeleted', models.IntegerField(default=0)),
                ('chartofaccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chartofaccount_productbudget_id', to='chartofaccount.Chartofaccount')),
                ('enterby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productbudget_enter', to=settings.AUTH_USER_MODEL)),
                ('modifyby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productbudget_modify', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_productbudget_id', to='product.Product')),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'productbudget',
                'permissions': (('view_productbudget', 'Can view productbudget'),),
            },
        ),
        migrations.AlterUniqueTogether(
            name='productbudget',
            unique_together=set([('year', 'product', 'chartofaccount')]),
        ),
    ]
