# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-27 13:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0016_auto_20170327_1338'),
        ('inventoryitemtype', '0008_auto_20170327_1338'),
        ('purchaserequisitionform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prfmain',
            name='department',
            field=models.ForeignKey(default=69, on_delete=django.db.models.deletion.CASCADE, related_name='prfmain_department_id', to='department.Department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prfmain',
            name='inventoryitemtype',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='prfmain_inventoryitemtype_id', to='inventoryitemtype.Inventoryitemtype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prfmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 27, 13, 37, 10, 594000)),
        ),
        migrations.AlterField(
            model_name='prfmain',
            name='prftype',
            field=models.CharField(choices=[('MSRF', 'MSRF')], default='MSRF', max_length=10),
        ),
    ]
