# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-27 13:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaserequisitionform', '0002_auto_20170327_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prfmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 27, 13, 41, 22, 76000)),
        ),
    ]
