# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-27 16:57
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchaserequisitionform', '0004_auto_20170327_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prfdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 27, 16, 57, 10, 11000)),
        ),
        migrations.AlterField(
            model_name='prfdetail',
            name='postby',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prfdetail_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prfdetail',
            name='postdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 3, 27, 16, 57, 10, 11000), null=True),
        ),
        migrations.AlterField(
            model_name='prfdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 27, 16, 57, 10, 14000)),
        ),
        migrations.AlterField(
            model_name='prfmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 27, 16, 57, 10, 8000)),
        ),
    ]
