# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-28 15:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaserequisitionform', '0005_auto_20170327_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='prfmain',
            name='dateneeded',
            field=models.DateField(default=datetime.datetime(2017, 3, 28, 15, 14, 8, 995000)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prfmain',
            name='urgencytype',
            field=models.CharField(choices=[('N', 'Normal'), ('R', 'Rush')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='prfdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 28, 15, 13, 29, 516000)),
        ),
        migrations.AlterField(
            model_name='prfdetail',
            name='postdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 3, 28, 15, 13, 29, 516000), null=True),
        ),
        migrations.AlterField(
            model_name='prfdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 28, 15, 13, 29, 519000)),
        ),
        migrations.AlterField(
            model_name='prfmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 28, 15, 13, 29, 513000)),
        ),
    ]
