# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-31 14:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaserequisitionform', '0006_auto_20170328_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='prfdetail',
            name='remarks',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='prfdetailtemp',
            name='remarks',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='prfdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 31, 14, 8, 36, 933000)),
        ),
        migrations.AlterField(
            model_name='prfdetail',
            name='postdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 3, 31, 14, 8, 36, 933000), null=True),
        ),
        migrations.AlterField(
            model_name='prfdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 31, 14, 8, 36, 935000)),
        ),
        migrations.AlterField(
            model_name='prfmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 31, 14, 8, 36, 930000)),
        ),
    ]
