# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-03 13:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaserequisitionform', '0007_auto_20170331_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prfdetail',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='prfdetailtemp',
            name='remarks',
        ),
        migrations.AlterField(
            model_name='prfdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 3, 13, 42, 58, 282000)),
        ),
        migrations.AlterField(
            model_name='prfdetail',
            name='postdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 3, 13, 42, 58, 282000), null=True),
        ),
        migrations.AlterField(
            model_name='prfdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 3, 13, 42, 58, 283000)),
        ),
        migrations.AlterField(
            model_name='prfmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 3, 13, 42, 58, 279000)),
        ),
    ]
