# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-10 13:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_auto_20170410_1333'),
        ('purchaserequisitionform', '0011_auto_20170410_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='prfdetail',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='prfdetail',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prfdetail_currency', to='currency.Currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prfdetailtemp',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='prfdetailtemp',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prfdetailtemp_currency', to='currency.Currency'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prfdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 10, 13, 32, 38, 845000)),
        ),
        migrations.AlterField(
            model_name='prfdetail',
            name='postdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 10, 13, 32, 38, 845000), null=True),
        ),
        migrations.AlterField(
            model_name='prfdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 10, 13, 32, 38, 850000)),
        ),
        migrations.AlterField(
            model_name='prfmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 10, 13, 32, 38, 843000)),
        ),
    ]
