# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-11 14:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unitofmeasure', '0004_auto_20170411_1434'),
        ('purchaserequisitionform', '0012_auto_20170410_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='prfdetail',
            name='invitem_unitofmeasure',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='prfdetail_unitofmeasure_id', to='unitofmeasure.Unitofmeasure'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prfdetail',
            name='invitem_unitofmeasure_code',
            field=models.CharField(default='pc', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prfdetailtemp',
            name='invitem_unitofmeasure',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='prfdetailtemp_unitofmeasure_id', to='unitofmeasure.Unitofmeasure'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prfdetailtemp',
            name='invitem_unitofmeasure_code',
            field=models.CharField(default='pc', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prfdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 11, 14, 33, 36, 755000)),
        ),
        migrations.AlterField(
            model_name='prfdetail',
            name='postdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 11, 14, 33, 36, 758000), null=True),
        ),
        migrations.AlterField(
            model_name='prfdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 11, 14, 33, 36, 761000)),
        ),
        migrations.AlterField(
            model_name='prfmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 11, 14, 33, 36, 749000)),
        ),
    ]
