# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-12 14:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaserequisitionform', '0014_auto_20170412_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='prfdetailtemp',
            name='grossamount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='prfdetailtemp',
            name='netamount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='prfdetailtemp',
            name='vatable',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='prfdetailtemp',
            name='vatamount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='prfdetailtemp',
            name='vatexempt',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='prfdetailtemp',
            name='vatzerorated',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='prfdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 12, 14, 22, 21, 824000)),
        ),
        migrations.AlterField(
            model_name='prfdetail',
            name='postdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 12, 14, 22, 21, 824000), null=True),
        ),
        migrations.AlterField(
            model_name='prfdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 12, 14, 22, 21, 828000)),
        ),
        migrations.AlterField(
            model_name='prfmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 12, 14, 22, 21, 816000)),
        ),
    ]
