# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-17 10:05
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vat', '0005_auto_20170417_1005'),
        ('supplier', '0007_auto_20170417_1005'),
        ('purchaserequisitionform', '0015_auto_20170412_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='prfdetail',
            name='cscost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='prfdetail',
            name='csdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 17, 10, 5, 5, 674000), null=True),
        ),
        migrations.AddField(
            model_name='prfdetail',
            name='csnum',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='prfdetail',
            name='cssupplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cssupplier_id', to='supplier.Supplier', validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='prfdetail',
            name='cssuppliercode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='prfdetail',
            name='cssuppliername',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='prfdetail',
            name='csvat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='csvat_id', to='vat.Vat', validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='prfdetail',
            name='csvatrate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prfdetailtemp',
            name='cscost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='prfdetailtemp',
            name='csdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 17, 10, 5, 5, 678000), null=True),
        ),
        migrations.AddField(
            model_name='prfdetailtemp',
            name='csnum',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='prfdetailtemp',
            name='cssupplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cssuppliertemp_id', to='supplier.Supplier', validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='prfdetailtemp',
            name='cssuppliercode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='prfdetailtemp',
            name='cssuppliername',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='prfdetailtemp',
            name='csvat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='csvattemp_id', to='vat.Vat', validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='prfdetailtemp',
            name='csvatrate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prfdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 17, 10, 5, 5, 674000)),
        ),
        migrations.AlterField(
            model_name='prfdetail',
            name='postdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 17, 10, 5, 5, 674000), null=True),
        ),
        migrations.AlterField(
            model_name='prfdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 17, 10, 5, 5, 678000)),
        ),
        migrations.AlterField(
            model_name='prfmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 17, 10, 5, 5, 670000)),
        ),
    ]
