# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-20 14:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaserequisitionform', '0016_auto_20170417_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prfdetail',
            name='csdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 20, 14, 0, 4, 407000), null=True),
        ),
        migrations.AlterField(
            model_name='prfdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 20, 14, 0, 4, 406000)),
        ),
        migrations.AlterField(
            model_name='prfdetail',
            name='postdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 20, 14, 0, 4, 407000), null=True),
        ),
        migrations.AlterField(
            model_name='prfdetailtemp',
            name='csdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 20, 14, 0, 4, 413000), null=True),
        ),
        migrations.AlterField(
            model_name='prfdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 20, 14, 0, 4, 412000)),
        ),
        migrations.AlterField(
            model_name='prfmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 20, 14, 0, 4, 400000)),
        ),
    ]
