# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-05-03 15:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaserequisitionform', '0017_auto_20170420_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prfdetail',
            name='cscost',
        ),
        migrations.RemoveField(
            model_name='prfdetail',
            name='csdate',
        ),
        migrations.RemoveField(
            model_name='prfdetail',
            name='csnum',
        ),
        migrations.RemoveField(
            model_name='prfdetail',
            name='cssupplier',
        ),
        migrations.RemoveField(
            model_name='prfdetail',
            name='cssuppliercode',
        ),
        migrations.RemoveField(
            model_name='prfdetail',
            name='cssuppliername',
        ),
        migrations.RemoveField(
            model_name='prfdetail',
            name='csvat',
        ),
        migrations.RemoveField(
            model_name='prfdetail',
            name='csvatrate',
        ),
        migrations.RemoveField(
            model_name='prfdetailtemp',
            name='cscost',
        ),
        migrations.RemoveField(
            model_name='prfdetailtemp',
            name='csdate',
        ),
        migrations.RemoveField(
            model_name='prfdetailtemp',
            name='csnum',
        ),
        migrations.RemoveField(
            model_name='prfdetailtemp',
            name='cssupplier',
        ),
        migrations.RemoveField(
            model_name='prfdetailtemp',
            name='cssuppliercode',
        ),
        migrations.RemoveField(
            model_name='prfdetailtemp',
            name='cssuppliername',
        ),
        migrations.RemoveField(
            model_name='prfdetailtemp',
            name='csvat',
        ),
        migrations.RemoveField(
            model_name='prfdetailtemp',
            name='csvatrate',
        ),
        migrations.AlterField(
            model_name='prfdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 3, 15, 25, 46, 642000)),
        ),
        migrations.AlterField(
            model_name='prfdetail',
            name='postdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 5, 3, 15, 25, 46, 643000), null=True),
        ),
        migrations.AlterField(
            model_name='prfdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 3, 15, 25, 46, 645000)),
        ),
        migrations.AlterField(
            model_name='prfmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 3, 15, 25, 46, 635000)),
        ),
    ]
