# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-05-02 09:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaserequisitionform', '0017_auto_20170420_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prfdetail',
            name='csdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 5, 2, 9, 30, 13, 673000), null=True),
        ),
        migrations.AlterField(
            model_name='prfdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 2, 9, 30, 13, 673000)),
        ),
        migrations.AlterField(
            model_name='prfdetail',
            name='postdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 5, 2, 9, 30, 13, 673000), null=True),
        ),
        migrations.AlterField(
            model_name='prfdetailtemp',
            name='csdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 5, 2, 9, 30, 13, 676000), null=True),
        ),
        migrations.AlterField(
            model_name='prfdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 2, 9, 30, 13, 676000)),
        ),
        migrations.AlterField(
            model_name='prfmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 2, 9, 30, 13, 670000)),
        ),
    ]
