# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-05-04 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchaserequisitionform', '0018_auto_20170502_0930'),
        ('purchaserequisitionform', '0019_auto_20170503_1643'),
    ]

    operations = [
    ]
