# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-05-04 13:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requisitionform', '0030_auto_20170504_1358'),
        ('purchaserequisitionform', '0020_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='rfprftransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prfquantity', models.IntegerField()),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('C', 'Cancelled'), ('O', 'Posted'), ('P', 'Printed')], default='A', max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='prfdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 4, 13, 58, 23, 422000)),
        ),
        migrations.AlterField(
            model_name='prfdetail',
            name='postdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 5, 4, 13, 58, 23, 422000), null=True),
        ),
        migrations.AlterField(
            model_name='prfdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 4, 13, 58, 23, 437000)),
        ),
        migrations.AlterField(
            model_name='prfmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 4, 13, 58, 23, 422000)),
        ),
        migrations.AddField(
            model_name='rfprftransaction',
            name='prfdetail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prfdetail_rfprftransaction', to='purchaserequisitionform.Prfdetail'),
        ),
        migrations.AddField(
            model_name='rfprftransaction',
            name='prfmain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prfmain_rfprftransaction', to='purchaserequisitionform.Prfmain'),
        ),
        migrations.AddField(
            model_name='rfprftransaction',
            name='rfdetail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfdetail_rfprftransaction', to='requisitionform.Rfdetail'),
        ),
        migrations.AddField(
            model_name='rfprftransaction',
            name='rfmain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfmain_rfprftransaction', to='requisitionform.Rfmain'),
        ),
    ]
