# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-05-04 14:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaserequisitionform', '0022_auto_20170504_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rfprftransaction',
            old_name='status',
            new_name='prfstatus',
        ),
        migrations.AlterField(
            model_name='prfdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 4, 14, 5, 10, 405000)),
        ),
        migrations.AlterField(
            model_name='prfdetail',
            name='postdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 5, 4, 14, 5, 10, 405000), null=True),
        ),
        migrations.AlterField(
            model_name='prfdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 4, 14, 5, 10, 407000)),
        ),
        migrations.AlterField(
            model_name='prfmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 4, 14, 5, 10, 398000)),
        ),
    ]
