# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-05-04 16:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requisitionform', '0031_auto_20170504_1635'),
        ('purchaserequisitionform', '0023_auto_20170504_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='prfdetail',
            name='rfmain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfmain_prfdetail', to='requisitionform.Rfmain'),
        ),
        migrations.AddField(
            model_name='prfdetailtemp',
            name='rfmain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfmain_prfdetailtemp', to='requisitionform.Rfmain'),
        ),
        migrations.AlterField(
            model_name='prfdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 4, 16, 35, 20, 756000)),
        ),
        migrations.AlterField(
            model_name='prfdetail',
            name='postdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 5, 4, 16, 35, 20, 756000), null=True),
        ),
        migrations.AlterField(
            model_name='prfdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 4, 16, 35, 20, 772000)),
        ),
        migrations.AlterField(
            model_name='prfmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 4, 16, 35, 20, 756000)),
        ),
    ]
