# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-05-05 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchaserequisitionform', '0026_auto_20170505_1717'),
        ('purchaserequisitionform', '0025_auto_20170504_1644'),
    ]

    operations = [
    ]
