# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-05-09 10:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaserequisitionform', '0031_auto_20170505_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='prfmain',
            name='print_ctr',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prfdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 9, 10, 49, 28, 774000)),
        ),
        migrations.AlterField(
            model_name='prfdetail',
            name='postdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 5, 9, 10, 49, 28, 774000), null=True),
        ),
        migrations.AlterField(
            model_name='prfdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 9, 10, 49, 28, 778000)),
        ),
        migrations.AlterField(
            model_name='prfmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 9, 10, 49, 28, 767000)),
        ),
    ]
