# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-05-09 14:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaserequisitionform', '0032_auto_20170509_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prfdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 9, 14, 16, 57, 339000)),
        ),
        migrations.AlterField(
            model_name='prfdetail',
            name='postdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 5, 9, 14, 16, 57, 339000), null=True),
        ),
        migrations.AlterField(
            model_name='prfdetail',
            name='remarks',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='prfdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 9, 14, 16, 57, 343000)),
        ),
        migrations.AlterField(
            model_name='prfdetailtemp',
            name='remarks',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='prfmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 9, 14, 16, 57, 332000)),
        ),
        migrations.AlterField(
            model_name='prfmain',
            name='remarks',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
