# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-05-10 10:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0019_auto_20170510_1053'),
        ('purchaserequisitionform', '0033_auto_20170509_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prfmain',
            name='department',
        ),
        migrations.AddField(
            model_name='prfdetail',
            name='department',
            field=models.ForeignKey(default=69, on_delete=django.db.models.deletion.CASCADE, related_name='prfdetail_department_id', to='department.Department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prfdetail',
            name='department_code',
            field=models.CharField(default='IT', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prfdetail',
            name='department_name',
            field=models.CharField(default='INFORMATION TECHNOLOGY', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prfdetailtemp',
            name='department',
            field=models.ForeignKey(default=69, on_delete=django.db.models.deletion.CASCADE, related_name='prfdetailtemp_department_id', to='department.Department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prfdetailtemp',
            name='department_code',
            field=models.CharField(default='INFORMATION TECHNOLOGY', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prfdetailtemp',
            name='department_name',
            field=models.CharField(default='INFORMATION TECHNOLOGY', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prfdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 10, 10, 49, 9, 908000)),
        ),
        migrations.AlterField(
            model_name='prfdetail',
            name='postdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 5, 10, 10, 49, 9, 908000), null=True),
        ),
        migrations.AlterField(
            model_name='prfdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 10, 10, 49, 9, 923000)),
        ),
        migrations.AlterField(
            model_name='prfmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 10, 10, 49, 9, 908000)),
        ),
    ]
