# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-05-24 03:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canvasssheet', '0030_auto_20170524_1107'),
        ('supplier', '0016_auto_20170524_1107'),
        ('purchaserequisitionform', '0037_auto_20170523_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='prfdetail',
            name='csdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prfdetail',
            name='csdetail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prfdetail_csdetail_id', to='canvasssheet.Csdetail'),
        ),
        migrations.AddField(
            model_name='prfdetail',
            name='csmain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prfdetail_csmain_id', to='canvasssheet.Csmain'),
        ),
        migrations.AddField(
            model_name='prfdetail',
            name='csnum',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='prfdetail',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prfdetail_supplier_id', to='supplier.Supplier'),
        ),
        migrations.AddField(
            model_name='prfdetail',
            name='suppliercode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='prfdetail',
            name='suppliername',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='prfdetailtemp',
            name='csdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prfdetailtemp',
            name='csdetail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prfdetailtemp_csdetail_id', to='canvasssheet.Csdetail'),
        ),
        migrations.AddField(
            model_name='prfdetailtemp',
            name='csmain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prfdetailtemp_csmain_id', to='canvasssheet.Csmain'),
        ),
        migrations.AddField(
            model_name='prfdetailtemp',
            name='csnum',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='prfdetailtemp',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prfdetailtemp_supplier_id', to='supplier.Supplier'),
        ),
        migrations.AddField(
            model_name='prfdetailtemp',
            name='suppliercode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='prfdetailtemp',
            name='suppliername',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='prfdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 24, 11, 7, 21, 643000)),
        ),
        migrations.AlterField(
            model_name='prfdetail',
            name='postdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 5, 24, 11, 7, 21, 643000), null=True),
        ),
        migrations.AlterField(
            model_name='prfdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 24, 11, 7, 21, 649000)),
        ),
        migrations.AlterField(
            model_name='prfmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 24, 11, 7, 21, 638000)),
        ),
    ]
