# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-05-26 02:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaserequisitionform', '0043_auto_20170526_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='prfdetail',
            name='isfullypo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prfdetail',
            name='poremainingquantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prfdetail',
            name='pototalquantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prfdetailtemp',
            name='isfullypo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prfdetailtemp',
            name='poremainingquantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prfdetailtemp',
            name='pototalquantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prfmain',
            name='totalquantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prfmain',
            name='totalremainingquantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prfdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 26, 10, 40, 26, 359000)),
        ),
        migrations.AlterField(
            model_name='prfdetail',
            name='postdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 5, 26, 10, 40, 26, 359000), null=True),
        ),
        migrations.AlterField(
            model_name='prfdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 26, 10, 40, 26, 363000)),
        ),
        migrations.AlterField(
            model_name='prfmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 26, 10, 40, 26, 354000)),
        ),
    ]
