# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-06-05 08:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaserequisitionform', '0045_auto_20170526_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prfdetail',
            name='csmain',
        ),
        migrations.RemoveField(
            model_name='prfdetailtemp',
            name='csmain',
        ),
        migrations.AlterField(
            model_name='prfdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 5, 16, 0, 24, 137000)),
        ),
        migrations.AlterField(
            model_name='prfdetail',
            name='postdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 6, 5, 16, 0, 24, 137000), null=True),
        ),
        migrations.AlterField(
            model_name='prfdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 5, 16, 0, 24, 141000)),
        ),
        migrations.AlterField(
            model_name='prfmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 5, 16, 0, 24, 130000)),
        ),
    ]
