# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-06-05 08:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaserequisitionform', '0046_auto_20170605_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prfdetail',
            name='csdetail',
        ),
        migrations.RemoveField(
            model_name='prfdetailtemp',
            name='csdetail',
        ),
        migrations.AddField(
            model_name='prfdetail',
            name='csmain',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prfdetailtemp',
            name='csmain',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prfdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 5, 16, 2, 43, 296000)),
        ),
        migrations.AlterField(
            model_name='prfdetail',
            name='postdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 6, 5, 16, 2, 43, 296000), null=True),
        ),
        migrations.AlterField(
            model_name='prfdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 5, 16, 2, 43, 301000)),
        ),
        migrations.AlterField(
            model_name='prfmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 5, 16, 2, 43, 288000)),
        ),
    ]
