# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-31 09:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vat', '0023_auto_20180131_1741'),
        ('purchaserequisitionform', '0048_auto_20170605_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='prfdetailtemp',
            name='vat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_vat_id', to='vat.Vat'),
        ),
        migrations.AlterField(
            model_name='prfdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 31, 17, 40, 42, 31000)),
        ),
        migrations.AlterField(
            model_name='prfdetail',
            name='postdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 1, 31, 17, 40, 42, 31000), null=True),
        ),
        migrations.AlterField(
            model_name='prfdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 31, 17, 40, 42, 35000)),
        ),
        migrations.AlterField(
            model_name='prfmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 31, 17, 40, 42, 26000)),
        ),
    ]
