# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-31 11:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vat', '0024_auto_20180131_1911'),
        ('purchaserequisitionform', '0049_auto_20180131_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='prfdetail',
            name='vat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_vatmain_id', to='vat.Vat'),
        ),
        migrations.AlterField(
            model_name='prfdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 31, 19, 11, 15, 379000)),
        ),
        migrations.AlterField(
            model_name='prfdetail',
            name='postdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 1, 31, 19, 11, 15, 379000), null=True),
        ),
        migrations.AlterField(
            model_name='prfdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 31, 19, 11, 15, 383000)),
        ),
        migrations.AlterField(
            model_name='prfmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 31, 19, 11, 15, 373000)),
        ),
    ]
