# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-08 07:30
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchaserequisitionform', '0051_auto_20180208_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='prfmain',
            name='approverlevel1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prf_approverlevel1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prfmain',
            name='approverlevel1_response',
            field=models.CharField(blank=True, choices=[('A', 'Approved'), ('D', 'Disapproved')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='prfmain',
            name='approverlevel1_responsedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prfmain',
            name='approverlevel2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prf_approverlevel2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prfmain',
            name='approverlevel2_response',
            field=models.CharField(blank=True, choices=[('A', 'Approved'), ('D', 'Disapproved')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='prfmain',
            name='approverlevel2_responsedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prfmain',
            name='approverlevel3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prf_approverlevel3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prfmain',
            name='approverlevel3_response',
            field=models.CharField(blank=True, choices=[('A', 'Approved'), ('D', 'Disapproved')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='prfmain',
            name='approverlevel3_responsedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prfmain',
            name='approverlevel4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prf_approverlevel4', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prfmain',
            name='approverlevel4_response',
            field=models.CharField(blank=True, choices=[('A', 'Approved'), ('D', 'Disapproved')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='prfmain',
            name='approverlevel4_responsedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prfmain',
            name='approverlevel5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prf_approverlevel5', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prfmain',
            name='approverlevel5_response',
            field=models.CharField(blank=True, choices=[('A', 'Approved'), ('D', 'Disapproved')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='prfmain',
            name='approverlevel5_responsedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prfmain',
            name='approverlevel6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prf_approverlevel6', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prfmain',
            name='approverlevel6_response',
            field=models.CharField(blank=True, choices=[('A', 'Approved'), ('D', 'Disapproved')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='prfmain',
            name='approverlevel6_responsedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prfmain',
            name='approverlevelbudget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prf_approverlevelbudget', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prfmain',
            name='approverlevelbudget_response',
            field=models.CharField(blank=True, choices=[('A', 'Approved'), ('D', 'Disapproved')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='prfmain',
            name='approverlevelbudget_responsedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prfdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 8, 15, 30, 46, 682000)),
        ),
        migrations.AlterField(
            model_name='prfdetail',
            name='postdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 2, 8, 15, 30, 46, 682000), null=True),
        ),
        migrations.AlterField(
            model_name='prfdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 8, 15, 30, 46, 686000)),
        ),
        migrations.AlterField(
            model_name='prfmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 8, 15, 30, 46, 677000)),
        ),
    ]
