# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-03-21 08:27
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchaserequisitionform', '0053_auto_20180209_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='prfdetail',
            name='closeby',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prfdetail_close', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prfdetail',
            name='closedate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 21, 16, 27, 40, 906000), null=True),
        ),
        migrations.AddField(
            model_name='prfdetailtemp',
            name='closeby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prfdetailtemp_close', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prfdetailtemp',
            name='closedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prfmain',
            name='closeby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prfmain_close', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prfmain',
            name='closedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prfdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 16, 27, 40, 905000)),
        ),
        migrations.AlterField(
            model_name='prfdetail',
            name='postdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 21, 16, 27, 40, 905000), null=True),
        ),
        migrations.AlterField(
            model_name='prfdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 16, 27, 40, 908000)),
        ),
        migrations.AlterField(
            model_name='prfmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 16, 27, 40, 901000)),
        ),
    ]
