# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-10-02 07:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvsubtype', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jvsubtype',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 2, 15, 38, 19, 220000)),
        ),
    ]
