# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-14 14:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyparameter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyparameter',
            old_name='address',
            new_name='address1',
        ),
        migrations.AddField(
            model_name='companyparameter',
            name='address2',
            field=models.CharField(default=' ', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companyparameter',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 14, 14, 18, 40, 646000)),
        ),
    ]
