# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-14 14:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyparameter', '0002_auto_20170314_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyparameter',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 14, 14, 20, 42, 484000)),
        ),
    ]
