# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-08-17 09:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccount', '0015_auto_20170817_1734'),
        ('companyparameter', '0003_auto_20170314_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyparameter',
            name='coa_cashinbank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameter_coa_cashinbank', to='chartofaccount.Chartofaccount'),
        ),
        migrations.AddField(
            model_name='companyparameter',
            name='coa_inputtax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameter_coa_inputtax', to='chartofaccount.Chartofaccount'),
        ),
        migrations.AlterField(
            model_name='companyparameter',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 17, 17, 34, 8, 801000)),
        ),
    ]
