# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-08-17 10:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccount', '0012_auto_20170817_1805'),
        ('companyparameter', '0006_auto_20170817_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyparameter',
            name='def_bankaccount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parameter_def_bankaccount', to='bankaccount.Bankaccount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companyparameter',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 17, 18, 5, 8, 226000)),
        ),
    ]
