# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-08-31 02:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyparameter', '0007_auto_20170817_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyparameter',
            name='report_footer1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='companyparameter',
            name='report_footer10',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='companyparameter',
            name='report_footer11',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='companyparameter',
            name='report_footer12',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='companyparameter',
            name='report_footer2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='companyparameter',
            name='report_footer3',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='companyparameter',
            name='report_footer4',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='companyparameter',
            name='report_footer5',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='companyparameter',
            name='report_footer6',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='companyparameter',
            name='report_footer7',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='companyparameter',
            name='report_footer8',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='companyparameter',
            name='report_footer9',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='companyparameter',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 31, 10, 37, 14, 30000)),
        ),
    ]
