# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-12-19 08:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccount', '0027_auto_20171219_1640'),
        ('companyparameter', '0008_auto_20170831_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyparameter',
            name='coa_outputvat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameter_coa_outputvat', to='chartofaccount.Chartofaccount'),
        ),
        migrations.AlterField(
            model_name='companyparameter',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 19, 16, 39, 58, 8000)),
        ),
    ]
