# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-03 03:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccount', '0028_auto_20180103_1119'),
        ('companyparameter', '0009_auto_20171219_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyparameter',
            name='coa_unsubscribe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameter_coa_unsubscribe', to='chartofaccount.Chartofaccount'),
        ),
        migrations.AlterField(
            model_name='companyparameter',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 3, 11, 18, 46, 307000)),
        ),
    ]
