# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-10 04:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyparameter', '0010_auto_20180103_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyparameter',
            name='report_footer13',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='companyparameter',
            name='report_footer14',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='companyparameter',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 10, 12, 11, 3, 140000)),
        ),
    ]
