# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-12 02:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyparameter', '0012_auto_20180110_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyparameter',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 12, 10, 20, 17, 444000)),
        ),
    ]
