# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-12 02:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccount', '0031_auto_20180212_1020'),
        ('companyparameter', '0013_auto_20180212_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyparameter',
            name='coa_deferredinputvat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameter_coa_deferredinputvat', to='chartofaccount.Chartofaccount'),
        ),
        migrations.AlterField(
            model_name='companyparameter',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 12, 10, 20, 43, 175000)),
        ),
    ]
