# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-12 03:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyparameter', '0013_auto_20180205_1645'),
        ('companyparameter', '0015_auto_20180212_1021'),
    ]

    operations = [
    ]
