# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-22 06:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccount', '0032_auto_20180222_1431'),
        ('companyparameter', '0016_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyparameter',
            name='coa_subsrev',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameter_coa_subsrev', to='chartofaccount.Chartofaccount'),
        ),
        migrations.AlterField(
            model_name='companyparameter',
            name='modifydate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
