# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-05-22 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyparameter', '0019_auto_20180228_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyparameter',
            name='last_closed_date',
            field=models.DateField(null=True),
        ),
    ]
