# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-05-22 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyparameter', '0020_companyparameter_last_closed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyparameter',
            name='income_tax_rate',
            field=models.IntegerField(null=True),
        ),
    ]
