# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-05-22 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccount', '0038_auto_20180323_1137'),
        ('companyparameter', '0021_companyparameter_income_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyparameter',
            name='coa_incometaxespayable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='param_incometaxespayable', to='chartofaccount.Chartofaccount'),
        ),
        migrations.AddField(
            model_name='companyparameter',
            name='coa_provisionincometax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='param_provisionincometax', to='chartofaccount.Chartofaccount'),
        ),
    ]
