# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-06-07 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccount', '0038_auto_20180323_1137'),
        ('companyparameter', '0023_companyparameter_coa_retainedearnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyparameter',
            name='coa_currentearnings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='param_coa_currentearnings', to='chartofaccount.Chartofaccount'),
        ),
    ]
