# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-11-26 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyparameter', '0024_add_companyparameters_currentearnings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyparameter',
            name='wtaxsign_name',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='companyparameter',
            name='wtaxsign_position',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
