# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-03-21 04:10
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('module', '0002_auto_20180321_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reportmaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('enterdate', models.DateTimeField(auto_now_add=True)),
                ('modifydate', models.DateTimeField(default=datetime.datetime(2018, 3, 21, 12, 10, 54, 100000))),
                ('isdeleted', models.IntegerField(default=0)),
                ('enterby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reportmaintenance_enter', to=settings.AUTH_USER_MODEL)),
                ('modifyby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reportmaintenance_modify', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'reportmaintenance',
                'permissions': (('view_reportmaintenance', 'Can view reportmaintenance'),),
            },
        ),
        migrations.CreateModel(
            name='Reportmaintenancemodule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterdate', models.DateTimeField(auto_now_add=True)),
                ('modifydate', models.DateTimeField(default=datetime.datetime(2018, 3, 21, 12, 10, 54, 101000))),
                ('isdeleted', models.IntegerField(default=0)),
                ('enterby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reportmaintenancemodule_enter', to=settings.AUTH_USER_MODEL)),
                ('modifyby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reportmaintenancemodule_modify', to=settings.AUTH_USER_MODEL)),
                ('reportmaintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportmaintenancemodule_reportdashboard', to='reportdashboard.Reportmaintenance')),
                ('reportmodule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportmaintenancemodule_module', to='module.Module')),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'reportmaintenancemodule',
                'permissions': (('view_reportmaintenancemodule', 'Can view reportmaintenancemodule'),),
            },
        ),
    ]
