# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-03-21 04:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportdashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmaintenance',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 12, 16, 52, 887000)),
        ),
        migrations.AlterField(
            model_name='reportmaintenancemodule',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 12, 16, 52, 888000)),
        ),
    ]
