# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-03-26 02:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportdashboard', '0002_auto_20180321_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmaintenance',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 26, 10, 35, 31, 998000)),
        ),
        migrations.AlterField(
            model_name='reportmaintenancemodule',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 26, 10, 35, 31, 999000)),
        ),
    ]
