# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-11-26 02:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportdashboard', '0003_auto_20180326_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmaintenance',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 26, 10, 39, 2, 885000)),
        ),
        migrations.AlterField(
            model_name='reportmaintenancemodule',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 26, 10, 39, 2, 886000)),
        ),
    ]
