# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-11-26 03:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportdashboard', '0005_auto_20181126_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmaintenance',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 26, 11, 25, 30, 282000)),
        ),
        migrations.AlterField(
            model_name='reportmaintenancemodule',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 26, 11, 25, 30, 297000)),
        ),
    ]
