# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-13 05:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adtype', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adtype',
            name='chartofaccount_arcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chartofaccount_arcode_id', to='chartofaccount.Chartofaccount'),
        ),
        migrations.AlterField(
            model_name='adtype',
            name='chartofaccount_revcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chartofaccount_revcode_id', to='chartofaccount.Chartofaccount'),
        ),
        migrations.AlterField(
            model_name='adtype',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 13, 13, 25, 18, 680000)),
        ),
    ]
