# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-11-08 06:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adtype', '0003_auto_20171010_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adtype',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 14, 44, 36, 503000)),
        ),
    ]
