# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-11-22 06:28
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0014_auto_20171122_1428'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cmitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_counter', models.IntegerField()),
                ('cmnum', models.CharField(max_length=10)),
                ('cmdate', models.DateTimeField()),
                ('product_code', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('C', 'Cancelled'), ('O', 'Posted'), ('P', 'Printed')], default='A', max_length=1)),
                ('enterdate', models.DateTimeField(auto_now_add=True)),
                ('modifydate', models.DateTimeField(default=datetime.datetime(2017, 11, 22, 14, 28, 46, 578000))),
                ('postdate', models.DateTimeField(blank=True, null=True)),
                ('isdeleted', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'cmitem',
            },
        ),
        migrations.CreateModel(
            name='Cmitemtemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_counter', models.IntegerField()),
                ('cmmain', models.CharField(blank=True, max_length=10, null=True)),
                ('cmitem', models.CharField(blank=True, max_length=10, null=True)),
                ('cmnum', models.CharField(blank=True, max_length=10, null=True)),
                ('cmdate', models.DateTimeField(blank=True, null=True)),
                ('product_code', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('secretkey', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('C', 'Cancelled'), ('O', 'Posted'), ('P', 'Printed')], default='A', max_length=1)),
                ('enterdate', models.DateTimeField(auto_now_add=True)),
                ('modifydate', models.DateTimeField(default=datetime.datetime(2017, 11, 22, 14, 28, 46, 580000))),
                ('postdate', models.DateTimeField(blank=True, null=True)),
                ('isdeleted', models.IntegerField(default=0)),
                ('enterby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cmitemtemp_enter', to=settings.AUTH_USER_MODEL)),
                ('modifyby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cmitemtemp_modify', to=settings.AUTH_USER_MODEL)),
                ('postby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmitemtemp_post', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmitemtemp_product_id', to='product.Product')),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'cmitemtemp',
            },
        ),
        migrations.CreateModel(
            name='Cmmain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmnum', models.CharField(max_length=10, unique=True)),
                ('cmdate', models.DateField()),
                ('particulars', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('cmstatus', models.CharField(choices=[('F', 'For Approval'), ('A', 'Approved'), ('D', 'Disapproved'), ('R', 'Released')], default='F', max_length=1)),
                ('approverresponse', models.CharField(blank=True, choices=[('A', 'Approved'), ('D', 'Disapproved')], max_length=1, null=True)),
                ('responsedate', models.DateTimeField(blank=True, null=True)),
                ('approverremarks', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('C', 'Cancelled'), ('O', 'Posted'), ('P', 'Printed')], default='A', max_length=1)),
                ('enterdate', models.DateTimeField(auto_now_add=True)),
                ('modifydate', models.DateTimeField(default=datetime.datetime(2017, 11, 22, 14, 28, 46, 576000))),
                ('postdate', models.DateTimeField(blank=True, null=True)),
                ('releasedate', models.DateTimeField(blank=True, null=True)),
                ('isdeleted', models.IntegerField(default=0)),
                ('print_ctr', models.IntegerField(default=0)),
                ('actualapprover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmmain_actual_approver', to=settings.AUTH_USER_MODEL)),
                ('designatedapprover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmmain_designated_approver', to=settings.AUTH_USER_MODEL)),
                ('enterby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cmmain_enter', to=settings.AUTH_USER_MODEL)),
                ('modifyby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cmmain_modify', to=settings.AUTH_USER_MODEL)),
                ('postby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmmain_post', to=settings.AUTH_USER_MODEL)),
                ('releaseby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmmain_release', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'cmmain',
                'permissions': (('view_cmsadjustment', 'Can view cms adjustment'),),
            },
        ),
        migrations.AddField(
            model_name='cmitem',
            name='cmmain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmitem_cmmain_id', to='cmsadjustment.Cmmain'),
        ),
        migrations.AddField(
            model_name='cmitem',
            name='enterby',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cmitem_enter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmitem',
            name='modifyby',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cmitem_modify', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmitem',
            name='postby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmitem_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmitem_product_id', to='product.Product'),
        ),
    ]
