# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-11-22 06:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsadjustment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmmain',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='cmitem',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 22, 14, 32, 46, 732000)),
        ),
        migrations.AlterField(
            model_name='cmitemtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 22, 14, 32, 46, 735000)),
        ),
        migrations.AlterField(
            model_name='cmmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 22, 14, 32, 46, 730000)),
        ),
    ]
