# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-11-22 08:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsadjustment', '0002_auto_20171122_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmitemtemp',
            name='enterby',
        ),
        migrations.RemoveField(
            model_name='cmitemtemp',
            name='modifyby',
        ),
        migrations.RemoveField(
            model_name='cmitemtemp',
            name='postby',
        ),
        migrations.RemoveField(
            model_name='cmitemtemp',
            name='product',
        ),
        migrations.AlterField(
            model_name='cmitem',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 22, 16, 46, 33, 218000)),
        ),
        migrations.AlterField(
            model_name='cmmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 22, 16, 46, 33, 216000)),
        ),
        migrations.DeleteModel(
            name='Cmitemtemp',
        ),
    ]
