# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-19 11:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20170516_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 19, 11, 20, 36, 664000)),
        ),
    ]
