# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-27 02:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20170720_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 27, 10, 46, 19, 368000)),
        ),
    ]
