# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-08-11 13:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_auto_20170807_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 11, 13, 23, 35, 355000)),
        ),
    ]
