# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-10-19 02:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_auto_20171019_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newusermodel',
            name='user',
        ),
        migrations.AddField(
            model_name='employee',
            name='cellphone_subsidize_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 19, 10, 54, 13, 458000)),
        ),
        migrations.DeleteModel(
            name='NewUserModel',
        ),
    ]
