# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-10-23 07:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0018_auto_20171019_1134'),
        ('employee', '0018_auto_20171019_1142'),
    ]

    operations = [
    ]
