# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-15 03:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccount', '0002_auto_20170203_1640'),
        ('chartofaccount', '0002_auto_20170215_1025'),
    ]

    operations = [
    ]
