# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-15 03:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccount', '0003_merge'),
        ('chartofaccount', '0003_auto_20170215_1104'),
    ]

    operations = [
    ]
