# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-01 10:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccount', '0005_auto_20170227_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccount',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 1, 10, 56, 0, 572000)),
        ),
    ]
