# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-21 12:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccount', '0006_auto_20170301_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccount',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 21, 12, 55, 18, 245727)),
        ),
    ]
