# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-08-17 09:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccount', '0014_auto_20170807_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccount',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 17, 17, 34, 8, 728000)),
        ),
    ]
