# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-08-24 07:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccount', '0018_auto_20170818_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccount',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 24, 15, 9, 1, 934000)),
        ),
    ]
