# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-11-07 01:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccount', '0022_auto_20171106_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccount',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 7, 9, 38, 16, 273000)),
        ),
    ]
