# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-11-07 10:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccount', '0023_auto_20171107_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccount',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 7, 18, 6, 8, 945000)),
        ),
    ]
