# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-12-19 08:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccount', '0026_auto_20171108_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccount',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 19, 16, 39, 57, 925000)),
        ),
    ]
