# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-10 08:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccount', '0028_auto_20180103_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccount',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 10, 16, 49, 14, 498000)),
        ),
    ]
