# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-15 08:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccount', '0029_auto_20180110_1515'),
        ('chartofaccount', '0029_auto_20180110_1649'),
    ]

    operations = [
    ]
