# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-22 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccount', '0031_auto_20180212_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccount',
            name='modifydate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
