# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-26 03:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccount', '0033_auto_20180226_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chartofaccount',
            name='refdate',
        ),
        migrations.RemoveField(
            model_name='chartofaccount',
            name='refnum',
        ),
        migrations.RemoveField(
            model_name='chartofaccount',
            name='reftype',
        ),
    ]
