# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-26 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccount', '0034_auto_20180226_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccount',
            name='refdate_enable',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='refnum_enable',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='reftype_enable',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
        ),
    ]
