# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-03-21 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccountsubgroup', '0001_initial'),
        ('chartofaccount', '0035_auto_20180226_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccount',
            name='sub_group',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='chartofaccount_subgroup', to='chartofaccountsubgroup.ChartofAccountSubGroup'),
            preserve_default=False,
        ),
    ]
