# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-03-21 08:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccount', '0036_chartofaccount_sub_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chartofaccount',
            old_name='sub_group',
            new_name='subgroup',
        ),
    ]
