# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-16 10:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_auto_20170203_1640'),
        ('department', '0003_auto_20170215_1104'),
    ]

    operations = [
    ]
