# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-23 10:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0007_auto_20170322_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 23, 10, 33, 16, 526000)),
        ),
    ]
