# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-05-10 10:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0018_auto_20170407_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 10, 10, 49, 9, 861000)),
        ),
    ]
