# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-05-19 03:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0019_auto_20170510_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 19, 11, 25, 26, 860000)),
        ),
    ]
