# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-19 11:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0020_auto_20170519_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 19, 11, 20, 36, 638000)),
        ),
    ]
