# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-10-12 08:53
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20171012_1653'),
        ('department', '0028_auto_20171012_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_product_id', to='product.Product', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='department',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 12, 16, 53, 35, 53000)),
        ),
    ]
