# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-04 03:54
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inputvattype', '0005_auto_20170704_1154'),
        ('creditterm', '0005_auto_20170704_1154'),
        ('currency', '0012_auto_20170704_1154'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vat', '0011_auto_20170704_1154'),
        ('ataxcode', '0008_auto_20170704_1154'),
        ('bankbranchdisburse', '0005_auto_20170704_1154'),
        ('branch', '0014_auto_20170704_1154'),
        ('supplier', '0018_auto_20170704_1154'),
        ('accountspayable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apmain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apnum', models.CharField(max_length=10, unique=True)),
                ('apdate', models.DateField()),
                ('aptype', models.CharField(choices=[('PO', 'PO')], default='PO', max_length=10)),
                ('apstatus', models.CharField(choices=[('V', 'Verified')], default='V', max_length=1)),
                ('payeecode', models.CharField(max_length=10)),
                ('vatcode', models.CharField(blank=True, max_length=10, null=True)),
                ('vatrate', models.IntegerField(blank=True, default=0, null=True)),
                ('ataxcode', models.CharField(blank=True, max_length=10, null=True)),
                ('ataxrate', models.IntegerField(blank=True, default=0, null=True)),
                ('bankbranchdisbursebranch', models.CharField(max_length=10)),
                ('duedate', models.DateField()),
                ('refno', models.CharField(max_length=250)),
                ('particulars', models.CharField(max_length=250)),
                ('deferred', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('fxrate', models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=18, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('C', 'Cancelled'), ('O', 'Posted'), ('P', 'Printed')], default='A', max_length=1)),
                ('enterdate', models.DateTimeField(auto_now_add=True)),
                ('modifydate', models.DateTimeField(default=datetime.datetime(2017, 7, 4, 11, 54, 49, 940000))),
                ('isdeleted', models.IntegerField(default=0)),
                ('atax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ap_ataxcode_id', to='ataxcode.Ataxcode')),
                ('bankbranchdisburse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ap_bankbranchdisburse_id', to='bankbranchdisburse.Bankbranchdisburse')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ap_branch_id', to='branch.Branch')),
                ('creditterm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ap_creditterm_id', to='creditterm.Creditterm')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ap_currency_id', to='currency.Currency')),
                ('enterby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ap_enter', to=settings.AUTH_USER_MODEL)),
                ('inputvattype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ap_inputvattype_id', to='inputvattype.Inputvattype')),
                ('modifyby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ap_modify', to=settings.AUTH_USER_MODEL)),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ap_supplier_id', to='supplier.Supplier')),
                ('vat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ap_vat_id', to='vat.Vat')),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'apmain',
                'permissions': (('view_accountspayable', 'Can view accountspayable'),),
            },
        ),
        migrations.RemoveField(
            model_name='accountspayable',
            name='atax',
        ),
        migrations.RemoveField(
            model_name='accountspayable',
            name='bankbranchdisburse',
        ),
        migrations.RemoveField(
            model_name='accountspayable',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='accountspayable',
            name='creditterm',
        ),
        migrations.RemoveField(
            model_name='accountspayable',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='accountspayable',
            name='enterby',
        ),
        migrations.RemoveField(
            model_name='accountspayable',
            name='inputvattype',
        ),
        migrations.RemoveField(
            model_name='accountspayable',
            name='modifyby',
        ),
        migrations.RemoveField(
            model_name='accountspayable',
            name='payee',
        ),
        migrations.RemoveField(
            model_name='accountspayable',
            name='vat',
        ),
        migrations.DeleteModel(
            name='Accountspayable',
        ),
    ]
