# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-27 02:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aptype', '0002_auto_20170727_1040'),
        ('accountspayable', '0003_auto_20170727_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='apmain',
            name='aptype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='aptype_apmain_id', to='aptype.Aptype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 27, 10, 40, 19, 426000)),
        ),
    ]
