# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-27 02:46
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wtax', '0006_auto_20170727_1046'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bankaccount', '0004_auto_20170727_1046'),
        ('product', '0004_auto_20170727_1046'),
        ('employee', '0008_auto_20170727_1046'),
        ('outputvat', '0004_auto_20170727_1046'),
        ('chartofaccount', '0010_auto_20170727_1046'),
        ('ataxcode', '0010_auto_20170727_1046'),
        ('vat', '0013_auto_20170727_1046'),
        ('department', '0022_auto_20170727_1046'),
        ('customer', '0007_auto_20170727_1046'),
        ('inputvat', '0005_auto_20170727_1046'),
        ('unit', '0010_auto_20170727_1046'),
        ('branch', '0015_auto_20170727_1046'),
        ('supplier', '0020_auto_20170727_1046'),
        ('accountspayable', '0004_auto_20170727_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_counter', models.IntegerField()),
                ('ap_num', models.CharField(max_length=10)),
                ('ap_date', models.DateTimeField()),
                ('debitamount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('creditamount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('balancecode', models.CharField(blank=True, max_length=1, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('C', 'Cancelled'), ('O', 'Posted'), ('P', 'Printed')], default='A', max_length=1)),
                ('enterdate', models.DateTimeField(auto_now_add=True)),
                ('modifydate', models.DateTimeField(default=datetime.datetime(2017, 7, 27, 10, 46, 19, 460000))),
                ('postdate', models.DateTimeField(default=datetime.datetime(2017, 7, 27, 10, 46, 19, 460000))),
                ('isdeleted', models.IntegerField(default=0)),
                ('customerbreakstatus', models.IntegerField(blank=True, null=True)),
                ('supplierbreakstatus', models.IntegerField(blank=True, null=True)),
                ('employeebreakstatus', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'apdetail',
            },
        ),
        migrations.AlterField(
            model_name='apmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 27, 10, 46, 19, 456000)),
        ),
        migrations.AddField(
            model_name='apdetail',
            name='apmain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apmain_apdetail_id', to='accountspayable.Apmain'),
        ),
        migrations.AddField(
            model_name='apdetail',
            name='ataxcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ataxcode_apdetail_id', to='ataxcode.Ataxcode'),
        ),
        migrations.AddField(
            model_name='apdetail',
            name='bankaccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bankaccount_apdetail_id', to='bankaccount.Bankaccount'),
        ),
        migrations.AddField(
            model_name='apdetail',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_apdetail_id', to='branch.Branch'),
        ),
        migrations.AddField(
            model_name='apdetail',
            name='chartofaccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chartofaccount_apdetail_id', to='chartofaccount.Chartofaccount'),
        ),
        migrations.AddField(
            model_name='apdetail',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_apdetail_id', to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='apdetail',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_apdetail_id', to='department.Department'),
        ),
        migrations.AddField(
            model_name='apdetail',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_apdetail_id', to='employee.Employee'),
        ),
        migrations.AddField(
            model_name='apdetail',
            name='enterby',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='apdetail_enter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apdetail',
            name='inputvat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inputvat_apdetail_id', to='inputvat.Inputvat'),
        ),
        migrations.AddField(
            model_name='apdetail',
            name='modifyby',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='apdetail_modify', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apdetail',
            name='outputvat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outputvat_apdetail_id', to='outputvat.Outputvat'),
        ),
        migrations.AddField(
            model_name='apdetail',
            name='postby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apdetail_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apdetail',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_apdetail_id', to='product.Product'),
        ),
        migrations.AddField(
            model_name='apdetail',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_apdetail_id', to='supplier.Supplier'),
        ),
        migrations.AddField(
            model_name='apdetail',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_apdetail_id', to='unit.Unit'),
        ),
        migrations.AddField(
            model_name='apdetail',
            name='vat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vat_apdetail_id', to='vat.Vat'),
        ),
        migrations.AddField(
            model_name='apdetail',
            name='wtax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wtax_apdetail_id', to='wtax.Wtax'),
        ),
    ]
