# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-27 03:02
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accountspayable', '0006_auto_20170727_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apdetailbreakdowntemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_counter', models.IntegerField()),
                ('secretkey', models.CharField(blank=True, max_length=255, null=True)),
                ('apdetailtemp', models.CharField(blank=True, max_length=10, null=True)),
                ('datatype', models.CharField(blank=True, max_length=1, null=True)),
                ('apmain', models.CharField(blank=True, max_length=10, null=True)),
                ('apdetail', models.CharField(blank=True, max_length=10, null=True)),
                ('apdetailbreakdown', models.CharField(blank=True, max_length=10, null=True)),
                ('ap_num', models.CharField(max_length=10)),
                ('ap_date', models.DateTimeField(blank=True, null=True)),
                ('chartofaccount', models.IntegerField(blank=True, null=True)),
                ('particular', models.TextField(blank=True, null=True)),
                ('bankaccount', models.IntegerField(blank=True, null=True)),
                ('department', models.IntegerField(blank=True, null=True)),
                ('employee', models.IntegerField(blank=True, null=True)),
                ('supplier', models.IntegerField(blank=True, null=True)),
                ('customer', models.IntegerField(blank=True, null=True)),
                ('unit', models.IntegerField(blank=True, null=True)),
                ('branch', models.IntegerField(blank=True, null=True)),
                ('product', models.IntegerField(blank=True, null=True)),
                ('inputvat', models.IntegerField(blank=True, null=True)),
                ('outputvat', models.IntegerField(blank=True, null=True)),
                ('vat', models.IntegerField(blank=True, null=True)),
                ('wtax', models.IntegerField(blank=True, null=True)),
                ('ataxcode', models.IntegerField(blank=True, null=True)),
                ('debitamount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('creditamount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('balancecode', models.CharField(blank=True, max_length=1, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('customerbreakstatus', models.IntegerField(blank=True, null=True)),
                ('supplierbreakstatus', models.IntegerField(blank=True, null=True)),
                ('employeebreakstatus', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('C', 'Cancelled'), ('O', 'Posted'), ('P', 'Printed')], default='A', max_length=1)),
                ('enterdate', models.DateTimeField(auto_now_add=True)),
                ('modifydate', models.DateTimeField(default=datetime.datetime(2017, 7, 27, 11, 2, 21, 102000))),
                ('postdate', models.DateTimeField(default=datetime.datetime(2017, 7, 27, 11, 2, 21, 102000))),
                ('isdeleted', models.IntegerField(default=0)),
                ('enterby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='apdetailbreakdowntemp_enter', to=settings.AUTH_USER_MODEL)),
                ('modifyby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='apdetailbreakdowntemp_modify', to=settings.AUTH_USER_MODEL)),
                ('postby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apdetailbreakdowntemp_post', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'apdetailbreakdowntemp',
            },
        ),
        migrations.CreateModel(
            name='Apdetailtemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_counter', models.IntegerField()),
                ('secretkey', models.CharField(blank=True, max_length=255, null=True)),
                ('apmain', models.CharField(blank=True, max_length=10, null=True)),
                ('apdetail', models.CharField(blank=True, max_length=10, null=True)),
                ('ap_num', models.CharField(max_length=10)),
                ('ap_date', models.DateTimeField(blank=True, null=True)),
                ('chartofaccount', models.IntegerField(blank=True, null=True)),
                ('bankaccount', models.IntegerField(blank=True, null=True)),
                ('department', models.IntegerField(blank=True, null=True)),
                ('employee', models.IntegerField(blank=True, null=True)),
                ('supplier', models.IntegerField(blank=True, null=True)),
                ('customer', models.IntegerField(blank=True, null=True)),
                ('unit', models.IntegerField(blank=True, null=True)),
                ('branch', models.IntegerField(blank=True, null=True)),
                ('product', models.IntegerField(blank=True, null=True)),
                ('inputvat', models.IntegerField(blank=True, null=True)),
                ('outputvat', models.IntegerField(blank=True, null=True)),
                ('vat', models.IntegerField(blank=True, null=True)),
                ('wtax', models.IntegerField(blank=True, null=True)),
                ('ataxcode', models.IntegerField(blank=True, null=True)),
                ('debitamount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('creditamount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('balancecode', models.CharField(blank=True, max_length=1, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('customerbreakstatus', models.IntegerField(blank=True, null=True)),
                ('supplierbreakstatus', models.IntegerField(blank=True, null=True)),
                ('employeebreakstatus', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('C', 'Cancelled'), ('O', 'Posted'), ('P', 'Printed')], default='A', max_length=1)),
                ('enterdate', models.DateTimeField(auto_now_add=True)),
                ('modifydate', models.DateTimeField(default=datetime.datetime(2017, 7, 27, 11, 2, 21, 99000))),
                ('postdate', models.DateTimeField(default=datetime.datetime(2017, 7, 27, 11, 2, 21, 99000))),
                ('isdeleted', models.IntegerField(default=0)),
                ('enterby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='apdetailtemp_enter', to=settings.AUTH_USER_MODEL)),
                ('modifyby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='apdetailtemp_modify', to=settings.AUTH_USER_MODEL)),
                ('postby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apdetailtemp_post', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'apdetailtemp',
            },
        ),
        migrations.AlterField(
            model_name='apdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 27, 11, 2, 21, 92000)),
        ),
        migrations.AlterField(
            model_name='apdetail',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 27, 11, 2, 21, 92000)),
        ),
        migrations.AlterField(
            model_name='apdetailbreakdown',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 27, 11, 2, 21, 96000)),
        ),
        migrations.AlterField(
            model_name='apdetailbreakdown',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 27, 11, 2, 21, 96000)),
        ),
        migrations.AlterField(
            model_name='apmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 27, 11, 2, 21, 89000)),
        ),
    ]
