# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-10 09:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountspayable', '0024_auto_20180102_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='apdetailtemp',
            name='isautogenerated',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='apdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 10, 17, 19, 26, 518000)),
        ),
        migrations.AlterField(
            model_name='apdetail',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 10, 17, 19, 26, 518000)),
        ),
        migrations.AlterField(
            model_name='apdetailbreakdown',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 10, 17, 19, 26, 522000)),
        ),
        migrations.AlterField(
            model_name='apdetailbreakdown',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 10, 17, 19, 26, 522000)),
        ),
        migrations.AlterField(
            model_name='apdetailbreakdowntemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 10, 17, 19, 26, 528000)),
        ),
        migrations.AlterField(
            model_name='apdetailbreakdowntemp',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 10, 17, 19, 26, 528000)),
        ),
        migrations.AlterField(
            model_name='apdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 10, 17, 19, 26, 525000)),
        ),
        migrations.AlterField(
            model_name='apdetailtemp',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 10, 17, 19, 26, 525000)),
        ),
        migrations.AlterField(
            model_name='apmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 10, 17, 19, 26, 514000)),
        ),
    ]
