# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-10 09:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountspayable', '0025_auto_20180110_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='apdetail',
            name='isautogenerated',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='apdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 10, 17, 45, 41, 603000)),
        ),
        migrations.AlterField(
            model_name='apdetail',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 10, 17, 45, 41, 603000)),
        ),
        migrations.AlterField(
            model_name='apdetailbreakdown',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 10, 17, 45, 41, 610000)),
        ),
        migrations.AlterField(
            model_name='apdetailbreakdown',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 10, 17, 45, 41, 610000)),
        ),
        migrations.AlterField(
            model_name='apdetailbreakdowntemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 10, 17, 45, 41, 618000)),
        ),
        migrations.AlterField(
            model_name='apdetailbreakdowntemp',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 10, 17, 45, 41, 618000)),
        ),
        migrations.AlterField(
            model_name='apdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 10, 17, 45, 41, 614000)),
        ),
        migrations.AlterField(
            model_name='apdetailtemp',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 10, 17, 45, 41, 614000)),
        ),
        migrations.AlterField(
            model_name='apmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 10, 17, 45, 41, 597000)),
        ),
    ]
