# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-05-04 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccount', '0020_auto_20180322_1106'),
        ('accountspayable', '0032_auto_20180503_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='apmain',
            name='bankaccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apmain_bankaccount_id', to='bankaccount.Bankaccount'),
        ),
    ]
