# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-03-23 03:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0002_auto_20180321_1210'),
        ('module', '0003_auto_20180322_1106'),
    ]

    operations = [
    ]
