# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-03-26 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0004_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='modifydate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
