# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-06 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_auto_20170403_1552'),
        ('supplier', '0004_auto_20170404_2011'),
    ]

    operations = [
    ]
