# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-17 10:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0006_auto_20170407_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 17, 10, 5, 5, 602000)),
        ),
    ]
