# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-20 11:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0009_auto_20170420_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 20, 11, 10, 45, 623000)),
        ),
    ]
