# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-05-04 17:53
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ataxcode', '0005_auto_20170504_1753'),
        ('inputvattype', '0002_auto_20170504_1753'),
        ('creditterm', '0003_auto_20170504_1753'),
        ('supplier', '0010_auto_20170420_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='ataxcode',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='inputvat',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='inputvatrate',
        ),
        migrations.AddField(
            model_name='supplier',
            name='atc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_atc_id', to='ataxcode.Ataxcode', validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='atcrate',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contactperson',
            field=models.CharField(default='Test Contact Person', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='creditterm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_creditterm_id', to='creditterm.Creditterm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='inputvattype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_inputvattype_id', to='inputvattype.Inputvattype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='inputvattype_deferred',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='supplier',
            name='vatrate',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 4, 17, 52, 23, 422000)),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='vat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_vat_id', to='vat.Vat', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
