# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-05-04 18:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0009_auto_20170504_1805'),
        ('supplier', '0011_auto_20170504_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_currency_id', to='currency.Currency'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 4, 18, 5, 46, 814000)),
        ),
    ]
