# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-05-10 09:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0013_auto_20170505_1003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='inputvattype_deferred',
            new_name='deferredvat',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 10, 9, 27, 1, 814000)),
        ),
    ]
