# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-05-11 17:25
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0002_auto_20170511_1725'),
        ('suppliertype', '0002_auto_20170511_1725'),
        ('supplier', '0014_auto_20170510_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='industry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_industry_id', to='industry.Industry', validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='suppliertype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_suppliertype_id', to='suppliertype.Suppliertype', validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplier',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 11, 17, 24, 50, 233000)),
        ),
    ]
