# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-06-29 16:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0017_auto_20170620_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 29, 16, 12, 59, 202000)),
        ),
    ]
