# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-11 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0018_auto_20170629_1613'),
        ('supplier', '0018_auto_20170704_1154'),
    ]

    operations = [
    ]
