# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-27 10:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0021_auto_20170727_1032'),
        ('supplier', '0021_auto_20170727_1051'),
    ]

    operations = [
    ]
