# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-09-05 10:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0028_auto_20170818_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 5, 18, 50, 46, 440000)),
        ),
    ]
