# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-03-26 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0035_auto_20180322_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='ccc_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='ccc_code2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='ccc_code3',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='serv_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
