# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-03-26 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0036_auto_20180326_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='remarks',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
