# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-03-26 06:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inputvat', '0014_auto_20180322_1106'),
        ('supplier', '0037_supplier_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='inputvat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_inputvat_id', to='inputvat.Inputvat'),
        ),
    ]
