# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-03-26 06:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0038_supplier_inputvat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='inputvattype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_inputvattype_id', to='inputvattype.Inputvattype'),
        ),
    ]
