# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-04-24 03:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0039_auto_20180326_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='inputvattype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_inputvattype_id', to='inputvattype.Inputvattype'),
        ),
    ]
