# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-04-24 03:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0040_auto_20180424_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='inputvat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_inputvat_id', to='inputvat.Inputvat'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='inputvattype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_inputvattype_id', to='inputvattype.Inputvattype'),
        ),
    ]
