# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-08-14 14:13
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenttype', '0002_auto_20170814_1413'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('street', models.CharField(max_length=250)),
                ('remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('comments', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('C', 'Cancelled'), ('O', 'Posted'), ('P', 'Printed')], default='A', max_length=1)),
                ('enterdate', models.DateTimeField(auto_now_add=True)),
                ('modifydate', models.DateTimeField(default=datetime.datetime(2017, 8, 14, 14, 13, 9, 524000))),
                ('isdeleted', models.IntegerField(default=0)),
                ('agenttype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_agenttype_id', to='agenttype.Agenttype')),
                ('enterby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agent_enter', to=settings.AUTH_USER_MODEL)),
                ('modifyby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agent_modify', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'agent',
                'permissions': (('view_agent', 'Can view agent'),),
            },
        ),
    ]
