# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-11-16 06:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_auto_20171011_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 16, 14, 18, 3, 430000)),
        ),
        migrations.AlterField(
            model_name='agent',
            name='street',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
