# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-08-23 08:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ataxcode', '0015_auto_20170807_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ataxcode',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 23, 16, 36, 31, 529000)),
        ),
    ]
