# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-05-11 17:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliertype', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliertype',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 11, 17, 24, 50, 196000)),
        ),
    ]
