# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-27 10:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccounttype', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccounttype',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 27, 10, 32, 51, 781000)),
        ),
    ]
