# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-05 03:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetapproverlevels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetapproverlevels',
            name='expwithinbudget',
        ),
        migrations.AlterField(
            model_name='budgetapproverlevels',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 5, 11, 7, 4, 347000)),
        ),
    ]
