# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-05 03:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetapproverlevels', '0003_auto_20180205_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetapproverlevels',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 5, 11, 41, 49, 569000)),
        ),
        migrations.AlterField(
            model_name='budgetapproverlevels',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
