# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-05 06:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetapproverlevels', '0004_auto_20180205_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetapproverlevels',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='budgetapproverlevels',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 5, 14, 5, 53, 798000)),
        ),
    ]
