# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-05 07:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('budgetapproverlevels', '0005_auto_20180205_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetapproverlevels',
            name='level',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budgetapproverlevels',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 5, 15, 36, 3, 135000)),
        ),
    ]
