# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-05 07:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetapproverlevels', '0006_auto_20180205_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetapproverlevels',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 5, 15, 38, 42, 157000)),
        ),
    ]
