# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-05 09:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetapproverlevels', '0009_auto_20180205_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetapproverlevels',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 5, 17, 16, 21, 835000)),
        ),
    ]
