# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-26 12:40
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inputvattype', '0007_auto_20170726_1240'),
        ('currency', '0014_auto_20170726_1240'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vat', '0013_auto_20170726_1240'),
        ('bankaccount', '0004_auto_20170726_1240'),
        ('ataxcode', '0010_auto_20170726_1240'),
        ('bankbranchdisburse', '0006_auto_20170726_1240'),
        ('branch', '0015_auto_20170726_1240'),
        ('supplier', '0020_auto_20170726_1240'),
        ('cvtype', '0002_auto_20170726_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cvmain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cvnum', models.CharField(max_length=10, unique=True)),
                ('cvdate', models.DateField()),
                ('cvstatus', models.CharField(choices=[('I', 'In Process'), ('R', 'RELEASED')], default='I', max_length=1)),
                ('payee_code', models.CharField(blank=True, max_length=25, null=True)),
                ('payee_name', models.CharField(max_length=150)),
                ('checknum', models.CharField(max_length=150)),
                ('checkdate', models.DateTimeField()),
                ('vatrate', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('atcrate', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('fxrate', models.DecimalField(decimal_places=5, default=0.0, max_digits=18)),
                ('deferredvat', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)])),
                ('particulars', models.TextField()),
                ('refnum', models.CharField(blank=True, max_length=150, null=True)),
                ('remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('C', 'Cancelled'), ('O', 'Posted'), ('P', 'Printed')], default='A', max_length=1)),
                ('enterdate', models.DateTimeField(auto_now_add=True)),
                ('modifydate', models.DateTimeField(default=datetime.datetime(2017, 7, 26, 12, 39, 53, 50000))),
                ('postdate', models.DateTimeField(blank=True, null=True)),
                ('releasedate', models.DateTimeField(blank=True, null=True)),
                ('isdeleted', models.IntegerField(default=0)),
                ('print_ctr', models.IntegerField(default=0)),
                ('atc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvmain_atc_id', to='ataxcode.Ataxcode', validators=[django.core.validators.MinValueValidator(1)])),
                ('bankaccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvmain_bankaccount_id', to='bankaccount.Bankaccount')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvmain_branch_id', to='branch.Branch')),
                ('currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cvmain_currency_id', to='currency.Currency')),
                ('cvtype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cvmain_cvtype_id', to='cvtype.Cvtype')),
                ('disbursingbranch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvmain_bankbranchdisburse_id', to='bankbranchdisburse.Bankbranchdisburse')),
                ('enterby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cvmain_enter', to=settings.AUTH_USER_MODEL)),
                ('inputvattype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvmain_inputvattype_id', to='inputvattype.Inputvattype')),
                ('modifyby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cvmain_modify', to=settings.AUTH_USER_MODEL)),
                ('payee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cvmain_payee_id', to='supplier.Supplier')),
                ('postby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cvmain_post', to=settings.AUTH_USER_MODEL)),
                ('releaseby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cvmain_release', to=settings.AUTH_USER_MODEL)),
                ('vat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvmain_vat_id', to='vat.Vat', validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'cvmain',
                'permissions': (('view_checkvoucher', 'Can view check voucher'),),
            },
        ),
    ]
