# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-26 16:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkvoucher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvmain',
            name='branch',
            field=models.ForeignKey(default='5', on_delete=django.db.models.deletion.CASCADE, related_name='cvmain_branch_id', to='branch.Branch'),
        ),
        migrations.AlterField(
            model_name='cvmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 26, 16, 38, 12, 976000)),
        ),
    ]
