# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-27 11:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkvoucher', '0002_auto_20170726_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvmain',
            name='bankaccount',
        ),
        migrations.AlterField(
            model_name='cvmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 27, 11, 19, 35, 530000)),
        ),
    ]
