# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-27 11:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkvoucher', '0003_auto_20170727_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvmain',
            name='bankaccountname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cvmain',
            name='bankaccountnumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cvmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 27, 11, 20, 25, 993000)),
        ),
    ]
