# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-08-03 10:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkvoucher', '0009_auto_20170802_1044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cvmain',
            options={'ordering': ['-pk'], 'permissions': (('view_checkvoucher', 'Can view check voucher'), ('approve_assignedcv', 'Can approve assigned cv'), ('approve_allcv', 'Can approve all cv'))},
        ),
        migrations.AlterField(
            model_name='cvdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 3, 10, 17, 31, 589000)),
        ),
        migrations.AlterField(
            model_name='cvdetail',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 3, 10, 17, 31, 589000)),
        ),
        migrations.AlterField(
            model_name='cvdetailbreakdown',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 3, 10, 17, 31, 593000)),
        ),
        migrations.AlterField(
            model_name='cvdetailbreakdown',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 3, 10, 17, 31, 593000)),
        ),
        migrations.AlterField(
            model_name='cvdetailbreakdowntemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 3, 10, 17, 31, 599000)),
        ),
        migrations.AlterField(
            model_name='cvdetailbreakdowntemp',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 3, 10, 17, 31, 599000)),
        ),
        migrations.AlterField(
            model_name='cvdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 3, 10, 17, 31, 596000)),
        ),
        migrations.AlterField(
            model_name='cvdetailtemp',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 3, 10, 17, 31, 597000)),
        ),
        migrations.AlterField(
            model_name='cvmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 3, 10, 17, 31, 585000)),
        ),
    ]
