# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-08-17 08:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkvoucher', '0010_auto_20170803_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 17, 16, 51, 8, 724000)),
        ),
        migrations.AlterField(
            model_name='cvdetail',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 17, 16, 51, 8, 724000)),
        ),
        migrations.AlterField(
            model_name='cvdetailbreakdown',
            name='cvdetail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cvdetail_cvdetailbreakdown_id', to='checkvoucher.Cvdetail'),
        ),
        migrations.AlterField(
            model_name='cvdetailbreakdown',
            name='cvmain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cvmain_cvdetailbreakdown_id', to='checkvoucher.Cvmain'),
        ),
        migrations.AlterField(
            model_name='cvdetailbreakdown',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 17, 16, 51, 8, 724000)),
        ),
        migrations.AlterField(
            model_name='cvdetailbreakdown',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 17, 16, 51, 8, 724000)),
        ),
        migrations.AlterField(
            model_name='cvdetailbreakdowntemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 17, 16, 51, 8, 740000)),
        ),
        migrations.AlterField(
            model_name='cvdetailbreakdowntemp',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 17, 16, 51, 8, 740000)),
        ),
        migrations.AlterField(
            model_name='cvdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 17, 16, 51, 8, 724000)),
        ),
        migrations.AlterField(
            model_name='cvdetailtemp',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 17, 16, 51, 8, 724000)),
        ),
        migrations.AlterField(
            model_name='cvmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 17, 16, 51, 8, 724000)),
        ),
    ]
