# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-12 01:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkvoucher', '0019_auto_20180111_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 12, 9, 50, 55, 534000)),
        ),
        migrations.AlterField(
            model_name='cvdetail',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 12, 9, 50, 55, 535000)),
        ),
        migrations.AlterField(
            model_name='cvdetailbreakdown',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 12, 9, 50, 55, 538000)),
        ),
        migrations.AlterField(
            model_name='cvdetailbreakdown',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 12, 9, 50, 55, 539000)),
        ),
        migrations.AlterField(
            model_name='cvdetailbreakdowntemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 12, 9, 50, 55, 544000)),
        ),
        migrations.AlterField(
            model_name='cvdetailbreakdowntemp',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 12, 9, 50, 55, 544000)),
        ),
        migrations.AlterField(
            model_name='cvdetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 12, 9, 50, 55, 542000)),
        ),
        migrations.AlterField(
            model_name='cvdetailtemp',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 12, 9, 50, 55, 542000)),
        ),
        migrations.AlterField(
            model_name='cvmain',
            name='cvstatus',
            field=models.CharField(choices=[('F', 'For Approval'), ('A', 'Approved'), ('D', 'Disapproved'), ('I', 'In Process'), ('FR', 'For Release'), ('R', 'Released')], default='F', max_length=2),
        ),
        migrations.AlterField(
            model_name='cvmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 12, 9, 50, 55, 530000)),
        ),
    ]
