# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-05-18 02:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountexpensebalance', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accountexpensebalance',
            unique_together=set([]),
        ),
    ]
