# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-11-08 07:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledgementreceipt', '0002_auto_20171108_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ardetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 15, 46, 23, 799000)),
        ),
        migrations.AlterField(
            model_name='ardetailbreakdown',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 15, 46, 23, 803000)),
        ),
        migrations.AlterField(
            model_name='ardetailbreakdowntemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 15, 46, 23, 812000)),
        ),
        migrations.AlterField(
            model_name='ardetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 15, 46, 23, 809000)),
        ),
        migrations.AlterField(
            model_name='aritem',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 15, 46, 23, 795000)),
        ),
        migrations.AlterField(
            model_name='aritemtemp',
            name='arnum',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='aritemtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 15, 46, 23, 797000)),
        ),
        migrations.AlterField(
            model_name='armain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 15, 46, 23, 791000)),
        ),
    ]
