# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-11-21 07:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledgementreceipt', '0003_auto_20171108_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aritemtemp',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='aritemtemp',
            name='bankbranch',
        ),
        migrations.AlterField(
            model_name='ardetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 21, 15, 18, 8, 378000)),
        ),
        migrations.AlterField(
            model_name='ardetailbreakdown',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 21, 15, 18, 8, 382000)),
        ),
        migrations.AlterField(
            model_name='ardetailbreakdowntemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 21, 15, 18, 8, 388000)),
        ),
        migrations.AlterField(
            model_name='ardetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 21, 15, 18, 8, 386000)),
        ),
        migrations.AlterField(
            model_name='aritem',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 21, 15, 18, 8, 373000)),
        ),
        migrations.AlterField(
            model_name='aritemtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 21, 15, 18, 8, 375000)),
        ),
        migrations.AlterField(
            model_name='armain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 21, 15, 18, 8, 370000)),
        ),
    ]
