# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-11-21 07:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledgementreceipt', '0005_auto_20171121_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aritemtemp',
            name='paytype',
        ),
        migrations.AlterField(
            model_name='ardetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 21, 15, 27, 56, 776000)),
        ),
        migrations.AlterField(
            model_name='ardetailbreakdown',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 21, 15, 27, 56, 780000)),
        ),
        migrations.AlterField(
            model_name='ardetailbreakdowntemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 21, 15, 27, 56, 786000)),
        ),
        migrations.AlterField(
            model_name='ardetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 21, 15, 27, 56, 783000)),
        ),
        migrations.AlterField(
            model_name='aritem',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 21, 15, 27, 56, 771000)),
        ),
        migrations.AlterField(
            model_name='aritemtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 21, 15, 27, 56, 773000)),
        ),
        migrations.AlterField(
            model_name='armain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 21, 15, 27, 56, 767000)),
        ),
    ]
