# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-11-21 07:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paytype', '0006_auto_20171121_1530'),
        ('acknowledgementreceipt', '0006_auto_20171121_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='aritemtemp',
            name='paytype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='aritemtemp_paytype_id', to='paytype.Paytype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ardetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 21, 15, 30, 6, 614000)),
        ),
        migrations.AlterField(
            model_name='ardetailbreakdown',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 21, 15, 30, 6, 621000)),
        ),
        migrations.AlterField(
            model_name='ardetailbreakdowntemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 21, 15, 30, 6, 632000)),
        ),
        migrations.AlterField(
            model_name='ardetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 21, 15, 30, 6, 627000)),
        ),
        migrations.AlterField(
            model_name='aritem',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 21, 15, 30, 6, 605000)),
        ),
        migrations.AlterField(
            model_name='aritemtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 21, 15, 30, 6, 609000)),
        ),
        migrations.AlterField(
            model_name='armain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 21, 15, 30, 6, 601000)),
        ),
    ]
