# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-03-21 08:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledgementreceipt', '0007_auto_20171121_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ardetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 16, 27, 40, 886000)),
        ),
        migrations.AlterField(
            model_name='ardetailbreakdown',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 16, 27, 40, 889000)),
        ),
        migrations.AlterField(
            model_name='ardetailbreakdowntemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 16, 27, 40, 892000)),
        ),
        migrations.AlterField(
            model_name='ardetailtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 16, 27, 40, 891000)),
        ),
        migrations.AlterField(
            model_name='aritem',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 16, 27, 40, 883000)),
        ),
        migrations.AlterField(
            model_name='aritemtemp',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 16, 27, 40, 884000)),
        ),
        migrations.AlterField(
            model_name='armain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 16, 27, 40, 881000)),
        ),
    ]
