# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-10-12 08:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20171011_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 12, 16, 53, 34, 894000)),
        ),
    ]
