# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-09-06 09:42
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkvoucher', '0012_auto_20170906_1742'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operationalfund', '0050_auto_20170906_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reppcvdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('C', 'Cancelled'), ('O', 'Posted'), ('P', 'Printed')], default='A', max_length=1)),
                ('enterdate', models.DateTimeField(auto_now_add=True)),
                ('modifydate', models.DateTimeField(default=datetime.datetime(2017, 9, 6, 17, 42, 33, 899000))),
                ('isdeleted', models.IntegerField(default=0)),
                ('print_ctr', models.IntegerField(default=0)),
                ('cvmain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reppcvdetail_cvmain_id', to='checkvoucher.Cvmain')),
                ('enterby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reppcvdetail_enter', to=settings.AUTH_USER_MODEL)),
                ('modifyby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reppcvdetail_modify', to=settings.AUTH_USER_MODEL)),
                ('ofmain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reppcvdetail_ofmain_id', to='operationalfund.Ofmain')),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'reppcvdetail',
            },
        ),
        migrations.CreateModel(
            name='Reppcvmain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reppcvnum', models.CharField(max_length=10, unique=True)),
                ('reppcvdate', models.DateField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('C', 'Cancelled'), ('O', 'Posted'), ('P', 'Printed')], default='A', max_length=1)),
                ('enterdate', models.DateTimeField(auto_now_add=True)),
                ('modifydate', models.DateTimeField(default=datetime.datetime(2017, 9, 6, 17, 42, 33, 898000))),
                ('isdeleted', models.IntegerField(default=0)),
                ('print_ctr', models.IntegerField(default=0)),
                ('cvmain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reppcvmain_cvmain_id', to='checkvoucher.Cvmain')),
                ('enterby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reppcvmain_enter', to=settings.AUTH_USER_MODEL)),
                ('modifyby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reppcvmain_modify', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'reppcvmain',
                'permissions': (('view_replenish_pcv', 'Can view replenishment of PCV'),),
            },
        ),
        migrations.AddField(
            model_name='reppcvdetail',
            name='reppcvmain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reppcvdetail_reppcvmain_id', to='replenish_pcv.Reppcvmain'),
        ),
    ]
