# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-09-06 10:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replenish_pcv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reppcvdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 6, 18, 38, 42, 476000)),
        ),
        migrations.AlterField(
            model_name='reppcvmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 6, 18, 38, 42, 475000)),
        ),
    ]
