# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-26 08:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replenish_pcv', '0005_auto_20180226_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reppcvdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 26, 16, 16, 16, 326000)),
        ),
        migrations.AlterField(
            model_name='reppcvmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 26, 16, 16, 16, 325000)),
        ),
    ]
