# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-03-21 08:27
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('replenish_pcv', '0006_auto_20180226_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='reppcvdetail',
            name='closeby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reppcvdetail_close', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reppcvdetail',
            name='closedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reppcvdetail',
            name='postby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reppcvdetail_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reppcvdetail',
            name='postdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reppcvmain',
            name='closeby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reppcvmain_close', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reppcvmain',
            name='closedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reppcvmain',
            name='postby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reppcvmain_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reppcvmain',
            name='postdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reppcvdetail',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 16, 27, 41, 15000)),
        ),
        migrations.AlterField(
            model_name='reppcvmain',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 16, 27, 41, 13000)),
        ),
    ]
