# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-20 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vat', '0008_auto_20170420_1110'),
        ('vat', '0006_auto_20170418_0931'),
    ]

    operations = [
    ]
