# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-10 15:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vat', '0010_auto_20170620_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vat',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 10, 15, 55, 30, 684000)),
        ),
    ]
